DROP TABLE IF EXISTS cms.setting;
DROP TABLE IF EXISTS cms.menu_item;
DROP TABLE IF EXISTS cms.banner;
DROP TABLE IF EXISTS cms.faq;
DROP TABLE IF EXISTS cms.page;
DROP TABLE IF EXISTS cms.article;
DROP SCHEMA IF EXISTS cms CASCADE;
