-- Rollback initial schema setup

DROP TABLE IF EXISTS platform.health_check;

DROP SCHEMA IF EXISTS ai CASCADE;
DROP SCHEMA IF EXISTS erp CASCADE;
DROP SCHEMA IF EXISTS platform CASCADE;
DROP SCHEMA IF EXISTS suppliers CASCADE;
DROP SCHEMA IF EXISTS cms CASCADE;
DROP SCHEMA IF EXISTS crm CASCADE;
DROP SCHEMA IF EXISTS promotions CASCADE;
DROP SCHEMA IF EXISTS payments CASCADE;
DROP SCHEMA IF EXISTS commerce CASCADE;
DROP SCHEMA IF EXISTS inventory CASCADE;
DROP SCHEMA IF EXISTS pricing CASCADE;
DROP SCHEMA IF EXISTS catalog CASCADE;
DROP SCHEMA IF EXISTS identity CASCADE;