// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package inventory

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLot = `-- name: CreateLot :one
INSERT INTO inventory.lot (
    code, stock_level_id, lot_number, initial_quantity, available_quantity, reserved_quantity, status, is_quarantined, production_date, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, code, stock_level_id, lot_number, initial_quantity, available_quantity, reserved_quantity, status, is_quarantined, production_date, expires_at, created_at, updated_at, deleted_at
`

type CreateLotParams struct {
	Code              string             `json:"code"`
	StockLevelID      int64              `json:"stock_level_id"`
	LotNumber         string             `json:"lot_number"`
	InitialQuantity   int32              `json:"initial_quantity"`
	AvailableQuantity int32              `json:"available_quantity"`
	ReservedQuantity  int32              `json:"reserved_quantity"`
	Status            InventoryLotStatus `json:"status"`
	IsQuarantined     bool               `json:"is_quarantined"`
	ProductionDate    pgtype.Date        `json:"production_date"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateLot(ctx context.Context, arg CreateLotParams) (InventoryLot, error) {
	row := q.db.QueryRow(ctx, createLot,
		arg.Code,
		arg.StockLevelID,
		arg.LotNumber,
		arg.InitialQuantity,
		arg.AvailableQuantity,
		arg.ReservedQuantity,
		arg.Status,
		arg.IsQuarantined,
		arg.ProductionDate,
		arg.ExpiresAt,
	)
	var i InventoryLot
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.StockLevelID,
		&i.LotNumber,
		&i.InitialQuantity,
		&i.AvailableQuantity,
		&i.ReservedQuantity,
		&i.Status,
		&i.IsQuarantined,
		&i.ProductionDate,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createQuarantineRecord = `-- name: CreateQuarantineRecord :one
INSERT INTO inventory.quarantine_record (
    code, lot_id, reason, status, adjusted_quantity, adjusted_by
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, code, lot_id, reason, status, adjusted_quantity, adjusted_by, created_at, updated_at, deleted_at
`

type CreateQuarantineRecordParams struct {
	Code             string                    `json:"code"`
	LotID            int64                     `json:"lot_id"`
	Reason           string                    `json:"reason"`
	Status           InventoryQuarantineStatus `json:"status"`
	AdjustedQuantity int32                     `json:"adjusted_quantity"`
	AdjustedBy       pgtype.Int8               `json:"adjusted_by"`
}

func (q *Queries) CreateQuarantineRecord(ctx context.Context, arg CreateQuarantineRecordParams) (InventoryQuarantineRecord, error) {
	row := q.db.QueryRow(ctx, createQuarantineRecord,
		arg.Code,
		arg.LotID,
		arg.Reason,
		arg.Status,
		arg.AdjustedQuantity,
		arg.AdjustedBy,
	)
	var i InventoryQuarantineRecord
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.LotID,
		&i.Reason,
		&i.Status,
		&i.AdjustedQuantity,
		&i.AdjustedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO inventory.reservation (
    code, lot_id, order_line_id, request_id, quantity, status, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, code, lot_id, order_line_id, request_id, quantity, status, expires_at, created_at, updated_at, deleted_at
`

type CreateReservationParams struct {
	Code        string                     `json:"code"`
	LotID       int64                      `json:"lot_id"`
	OrderLineID pgtype.Int8                `json:"order_line_id"`
	RequestID   string                     `json:"request_id"`
	Quantity    int32                      `json:"quantity"`
	Status      InventoryReservationStatus `json:"status"`
	ExpiresAt   time.Time                  `json:"expires_at"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.Code,
		arg.LotID,
		arg.OrderLineID,
		arg.RequestID,
		arg.Quantity,
		arg.Status,
		arg.ExpiresAt,
	)
	var i InventoryReservation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.LotID,
		&i.OrderLineID,
		&i.RequestID,
		&i.Quantity,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createStockLevel = `-- name: CreateStockLevel :one
INSERT INTO inventory.stock_level (
    code, product_id, supplier_id, available_quantity, reserved_quantity, total_quantity, safety_stock
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, code, product_id, supplier_id, available_quantity, reserved_quantity, total_quantity, safety_stock, created_at, updated_at, deleted_at
`

type CreateStockLevelParams struct {
	Code              string `json:"code"`
	ProductID         int64  `json:"product_id"`
	SupplierID        int64  `json:"supplier_id"`
	AvailableQuantity int32  `json:"available_quantity"`
	ReservedQuantity  int32  `json:"reserved_quantity"`
	TotalQuantity     int32  `json:"total_quantity"`
	SafetyStock       int32  `json:"safety_stock"`
}

func (q *Queries) CreateStockLevel(ctx context.Context, arg CreateStockLevelParams) (InventoryStockLevel, error) {
	row := q.db.QueryRow(ctx, createStockLevel,
		arg.Code,
		arg.ProductID,
		arg.SupplierID,
		arg.AvailableQuantity,
		arg.ReservedQuantity,
		arg.TotalQuantity,
		arg.SafetyStock,
	)
	var i InventoryStockLevel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ProductID,
		&i.SupplierID,
		&i.AvailableQuantity,
		&i.ReservedQuantity,
		&i.TotalQuantity,
		&i.SafetyStock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findExpiredReservations = `-- name: FindExpiredReservations :many
SELECT id, code, lot_id, order_line_id, request_id, quantity, status, expires_at, created_at, updated_at, deleted_at FROM inventory.reservation
WHERE status = 'reserved'
  AND expires_at < NOW()
  AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) FindExpiredReservations(ctx context.Context) ([]InventoryReservation, error) {
	rows, err := q.db.Query(ctx, findExpiredReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryReservation{}
	for rows.Next() {
		var i InventoryReservation
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.LotID,
			&i.OrderLineID,
			&i.RequestID,
			&i.Quantity,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFEFOLotsForUpdate = `-- name: GetFEFOLotsForUpdate :many
SELECT id, code, stock_level_id, lot_number, initial_quantity, available_quantity, reserved_quantity, status, is_quarantined, production_date, expires_at, created_at, updated_at, deleted_at FROM inventory.lot
WHERE stock_level_id = $1
  AND deleted_at IS NULL
  AND is_quarantined = FALSE
  AND available_quantity > 0
  AND status = 'active'
ORDER BY expires_at ASC, id ASC
FOR UPDATE
`

func (q *Queries) GetFEFOLotsForUpdate(ctx context.Context, stockLevelID int64) ([]InventoryLot, error) {
	rows, err := q.db.Query(ctx, getFEFOLotsForUpdate, stockLevelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryLot{}
	for rows.Next() {
		var i InventoryLot
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.StockLevelID,
			&i.LotNumber,
			&i.InitialQuantity,
			&i.AvailableQuantity,
			&i.ReservedQuantity,
			&i.Status,
			&i.IsQuarantined,
			&i.ProductionDate,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLotByCode = `-- name: GetLotByCode :one
SELECT id, code, stock_level_id, lot_number, initial_quantity, available_quantity, reserved_quantity, status, is_quarantined, production_date, expires_at, created_at, updated_at, deleted_at FROM inventory.lot
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLotByCode(ctx context.Context, code string) (InventoryLot, error) {
	row := q.db.QueryRow(ctx, getLotByCode, code)
	var i InventoryLot
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.StockLevelID,
		&i.LotNumber,
		&i.InitialQuantity,
		&i.AvailableQuantity,
		&i.ReservedQuantity,
		&i.Status,
		&i.IsQuarantined,
		&i.ProductionDate,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLotByID = `-- name: GetLotByID :one
SELECT id, code, stock_level_id, lot_number, initial_quantity, available_quantity, reserved_quantity, status, is_quarantined, production_date, expires_at, created_at, updated_at, deleted_at FROM inventory.lot
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLotByID(ctx context.Context, id int64) (InventoryLot, error) {
	row := q.db.QueryRow(ctx, getLotByID, id)
	var i InventoryLot
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.StockLevelID,
		&i.LotNumber,
		&i.InitialQuantity,
		&i.AvailableQuantity,
		&i.ReservedQuantity,
		&i.Status,
		&i.IsQuarantined,
		&i.ProductionDate,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReservationByCode = `-- name: GetReservationByCode :one
SELECT id, code, lot_id, order_line_id, request_id, quantity, status, expires_at, created_at, updated_at, deleted_at FROM inventory.reservation
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetReservationByCode(ctx context.Context, code string) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, getReservationByCode, code)
	var i InventoryReservation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.LotID,
		&i.OrderLineID,
		&i.RequestID,
		&i.Quantity,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT id, code, lot_id, order_line_id, request_id, quantity, status, expires_at, created_at, updated_at, deleted_at FROM inventory.reservation
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetReservationByID(ctx context.Context, id int64) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, getReservationByID, id)
	var i InventoryReservation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.LotID,
		&i.OrderLineID,
		&i.RequestID,
		&i.Quantity,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReservationsByRequestID = `-- name: GetReservationsByRequestID :many
SELECT id, code, lot_id, order_line_id, request_id, quantity, status, expires_at, created_at, updated_at, deleted_at FROM inventory.reservation
WHERE request_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetReservationsByRequestID(ctx context.Context, requestID string) ([]InventoryReservation, error) {
	rows, err := q.db.Query(ctx, getReservationsByRequestID, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryReservation{}
	for rows.Next() {
		var i InventoryReservation
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.LotID,
			&i.OrderLineID,
			&i.RequestID,
			&i.Quantity,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockLevelByID = `-- name: GetStockLevelByID :one
SELECT id, code, product_id, supplier_id, available_quantity, reserved_quantity, total_quantity, safety_stock, created_at, updated_at, deleted_at FROM inventory.stock_level
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStockLevelByID(ctx context.Context, id int64) (InventoryStockLevel, error) {
	row := q.db.QueryRow(ctx, getStockLevelByID, id)
	var i InventoryStockLevel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ProductID,
		&i.SupplierID,
		&i.AvailableQuantity,
		&i.ReservedQuantity,
		&i.TotalQuantity,
		&i.SafetyStock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getStockLevelByProductAndSupplier = `-- name: GetStockLevelByProductAndSupplier :one
SELECT id, code, product_id, supplier_id, available_quantity, reserved_quantity, total_quantity, safety_stock, created_at, updated_at, deleted_at FROM inventory.stock_level
WHERE product_id = $1 AND supplier_id = $2 AND deleted_at IS NULL
`

type GetStockLevelByProductAndSupplierParams struct {
	ProductID  int64 `json:"product_id"`
	SupplierID int64 `json:"supplier_id"`
}

func (q *Queries) GetStockLevelByProductAndSupplier(ctx context.Context, arg GetStockLevelByProductAndSupplierParams) (InventoryStockLevel, error) {
	row := q.db.QueryRow(ctx, getStockLevelByProductAndSupplier, arg.ProductID, arg.SupplierID)
	var i InventoryStockLevel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ProductID,
		&i.SupplierID,
		&i.AvailableQuantity,
		&i.ReservedQuantity,
		&i.TotalQuantity,
		&i.SafetyStock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listStockLevels = `-- name: ListStockLevels :many
SELECT id, code, product_id, supplier_id, available_quantity, reserved_quantity, total_quantity, safety_stock, created_at, updated_at, deleted_at FROM inventory.stock_level
WHERE product_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListStockLevels(ctx context.Context, productID int64) ([]InventoryStockLevel, error) {
	rows, err := q.db.Query(ctx, listStockLevels, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryStockLevel{}
	for rows.Next() {
		var i InventoryStockLevel
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ProductID,
			&i.SupplierID,
			&i.AvailableQuantity,
			&i.ReservedQuantity,
			&i.TotalQuantity,
			&i.SafetyStock,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quarantineLot = `-- name: QuarantineLot :one
UPDATE inventory.lot
SET is_quarantined = TRUE,
    status = 'quarantined',
    available_quantity = 0,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, stock_level_id, lot_number, initial_quantity, available_quantity, reserved_quantity, status, is_quarantined, production_date, expires_at, created_at, updated_at, deleted_at
`

func (q *Queries) QuarantineLot(ctx context.Context, id int64) (InventoryLot, error) {
	row := q.db.QueryRow(ctx, quarantineLot, id)
	var i InventoryLot
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.StockLevelID,
		&i.LotNumber,
		&i.InitialQuantity,
		&i.AvailableQuantity,
		&i.ReservedQuantity,
		&i.Status,
		&i.IsQuarantined,
		&i.ProductionDate,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateLotQuantities = `-- name: UpdateLotQuantities :one
UPDATE inventory.lot
SET available_quantity = $2,
    reserved_quantity = $3,
    status = $4,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, stock_level_id, lot_number, initial_quantity, available_quantity, reserved_quantity, status, is_quarantined, production_date, expires_at, created_at, updated_at, deleted_at
`

type UpdateLotQuantitiesParams struct {
	ID                int64              `json:"id"`
	AvailableQuantity int32              `json:"available_quantity"`
	ReservedQuantity  int32              `json:"reserved_quantity"`
	Status            InventoryLotStatus `json:"status"`
}

func (q *Queries) UpdateLotQuantities(ctx context.Context, arg UpdateLotQuantitiesParams) (InventoryLot, error) {
	row := q.db.QueryRow(ctx, updateLotQuantities,
		arg.ID,
		arg.AvailableQuantity,
		arg.ReservedQuantity,
		arg.Status,
	)
	var i InventoryLot
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.StockLevelID,
		&i.LotNumber,
		&i.InitialQuantity,
		&i.AvailableQuantity,
		&i.ReservedQuantity,
		&i.Status,
		&i.IsQuarantined,
		&i.ProductionDate,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateReservationStatus = `-- name: UpdateReservationStatus :one
UPDATE inventory.reservation
SET status = $2,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, lot_id, order_line_id, request_id, quantity, status, expires_at, created_at, updated_at, deleted_at
`

type UpdateReservationStatusParams struct {
	ID     int64                      `json:"id"`
	Status InventoryReservationStatus `json:"status"`
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, updateReservationStatus, arg.ID, arg.Status)
	var i InventoryReservation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.LotID,
		&i.OrderLineID,
		&i.RequestID,
		&i.Quantity,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateStockLevelQuantities = `-- name: UpdateStockLevelQuantities :one
UPDATE inventory.stock_level
SET available_quantity = $2,
    reserved_quantity = $3,
    total_quantity = $4,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, product_id, supplier_id, available_quantity, reserved_quantity, total_quantity, safety_stock, created_at, updated_at, deleted_at
`

type UpdateStockLevelQuantitiesParams struct {
	ID                int64 `json:"id"`
	AvailableQuantity int32 `json:"available_quantity"`
	ReservedQuantity  int32 `json:"reserved_quantity"`
	TotalQuantity     int32 `json:"total_quantity"`
}

func (q *Queries) UpdateStockLevelQuantities(ctx context.Context, arg UpdateStockLevelQuantitiesParams) (InventoryStockLevel, error) {
	row := q.db.QueryRow(ctx, updateStockLevelQuantities,
		arg.ID,
		arg.AvailableQuantity,
		arg.ReservedQuantity,
		arg.TotalQuantity,
	)
	var i InventoryStockLevel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ProductID,
		&i.SupplierID,
		&i.AvailableQuantity,
		&i.ReservedQuantity,
		&i.TotalQuantity,
		&i.SafetyStock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
