// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package inventory

import (
	"context"
)

type Querier interface {
	CreateLot(ctx context.Context, arg CreateLotParams) (InventoryLot, error)
	CreateQuarantineRecord(ctx context.Context, arg CreateQuarantineRecordParams) (InventoryQuarantineRecord, error)
	CreateReservation(ctx context.Context, arg CreateReservationParams) (InventoryReservation, error)
	CreateStockLevel(ctx context.Context, arg CreateStockLevelParams) (InventoryStockLevel, error)
	FindExpiredReservations(ctx context.Context) ([]InventoryReservation, error)
	GetFEFOLotsForUpdate(ctx context.Context, stockLevelID int64) ([]InventoryLot, error)
	GetLotByCode(ctx context.Context, code string) (InventoryLot, error)
	GetLotByID(ctx context.Context, id int64) (InventoryLot, error)
	GetLotByIDForUpdate(ctx context.Context, id int64) (InventoryLot, error)
	GetLotByStockAndNumberForUpdate(ctx context.Context, arg GetLotByStockAndNumberForUpdateParams) (InventoryLot, error)
	GetReservationByCode(ctx context.Context, code string) (InventoryReservation, error)
	GetReservationByID(ctx context.Context, id int64) (InventoryReservation, error)
	GetReservationsByRequestID(ctx context.Context, requestID string) ([]InventoryReservation, error)
	GetReservationsByRequestIDForUpdate(ctx context.Context, requestID string) ([]InventoryReservation, error)
	GetStockLevelByID(ctx context.Context, id int64) (InventoryStockLevel, error)
	GetStockLevelByIDForUpdate(ctx context.Context, id int64) (InventoryStockLevel, error)
	GetStockLevelByProductAndSupplier(ctx context.Context, arg GetStockLevelByProductAndSupplierParams) (InventoryStockLevel, error)
	ListStockLevels(ctx context.Context, productID int64) ([]InventoryStockLevel, error)
	QuarantineLot(ctx context.Context, id int64) (InventoryLot, error)
	UpdateLotQuantities(ctx context.Context, arg UpdateLotQuantitiesParams) (InventoryLot, error)
	UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (InventoryReservation, error)
	UpdateStockLevelQuantities(ctx context.Context, arg UpdateStockLevelQuantitiesParams) (InventoryStockLevel, error)
}

var _ Querier = (*Queries)(nil)
