// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pricing.sql

package pricing

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPriceListAssignments = `-- name: CountPriceListAssignments :one
SELECT COUNT(*)
FROM pricing.price_list_assignment
WHERE deleted_at IS NULL
  AND ($1::bigint IS NULL OR price_list_id = $1)
  AND ($2::bigint IS NULL OR buyer_profile_id = $2)
  AND ($3::boolean IS NULL OR is_active = $3)
`

type CountPriceListAssignmentsParams struct {
	Column1 int64 `json:"column_1"`
	Column2 int64 `json:"column_2"`
	Column3 bool  `json:"column_3"`
}

func (q *Queries) CountPriceListAssignments(ctx context.Context, arg CountPriceListAssignmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPriceListAssignments, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPriceListItems = `-- name: CountPriceListItems :one
SELECT COUNT(*)
FROM pricing.price_list_item
WHERE deleted_at IS NULL
  AND ($1::bigint IS NULL OR price_list_id = $1)
  AND ($2::bigint IS NULL OR product_id = $2)
  AND ($3::bigint IS NULL OR unit_id = $3)
  AND ($4::boolean IS NULL OR is_active = $4)
`

type CountPriceListItemsParams struct {
	Column1 int64 `json:"column_1"`
	Column2 int64 `json:"column_2"`
	Column3 int64 `json:"column_3"`
	Column4 bool  `json:"column_4"`
}

func (q *Queries) CountPriceListItems(ctx context.Context, arg CountPriceListItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPriceListItems,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPriceLists = `-- name: CountPriceLists :one
SELECT COUNT(*)
FROM pricing.price_list
WHERE deleted_at IS NULL
  AND ($1::pricing.price_list_status IS NULL OR status = $1)
  AND ($2::boolean IS NULL OR is_active = $2)
`

type CountPriceListsParams struct {
	Column1 PricingPriceListStatus `json:"column_1"`
	Column2 bool                   `json:"column_2"`
}

func (q *Queries) CountPriceLists(ctx context.Context, arg CountPriceListsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPriceLists, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPriceList = `-- name: CreatePriceList :one

INSERT INTO pricing.price_list (
    code, name, description, status, price_type, currency,
    effective_from, effective_to, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, code, name, status, created_at, updated_at
`

type CreatePriceListParams struct {
	Code          string                 `json:"code"`
	Name          string                 `json:"name"`
	Description   pgtype.Text            `json:"description"`
	Status        PricingPriceListStatus `json:"status"`
	PriceType     PricingPriceType       `json:"price_type"`
	Currency      string                 `json:"currency"`
	EffectiveFrom time.Time              `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz     `json:"effective_to"`
	IsActive      bool                   `json:"is_active"`
}

type CreatePriceListRow struct {
	ID        int64                  `json:"id"`
	Code      string                 `json:"code"`
	Name      string                 `json:"name"`
	Status    PricingPriceListStatus `json:"status"`
	CreatedAt time.Time              `json:"created_at"`
	UpdatedAt time.Time              `json:"updated_at"`
}

// Pricing module queries
// Price Lists, Price Items, Quantity Tiers, Buyer Assignments
func (q *Queries) CreatePriceList(ctx context.Context, arg CreatePriceListParams) (CreatePriceListRow, error) {
	row := q.db.QueryRow(ctx, createPriceList,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.PriceType,
		arg.Currency,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.IsActive,
	)
	var i CreatePriceListRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPriceListAssignment = `-- name: CreatePriceListAssignment :one
INSERT INTO pricing.price_list_assignment (
    code, price_list_id, buyer_profile_id, assigned_by,
    effective_from, effective_to, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, code, price_list_id, buyer_profile_id, assigned_by,
    effective_from, effective_to, is_active, created_at, updated_at
`

type CreatePriceListAssignmentParams struct {
	Code           string             `json:"code"`
	PriceListID    int64              `json:"price_list_id"`
	BuyerProfileID int64              `json:"buyer_profile_id"`
	AssignedBy     pgtype.Int8        `json:"assigned_by"`
	EffectiveFrom  time.Time          `json:"effective_from"`
	EffectiveTo    pgtype.Timestamptz `json:"effective_to"`
	IsActive       bool               `json:"is_active"`
}

type CreatePriceListAssignmentRow struct {
	ID             int64              `json:"id"`
	Code           string             `json:"code"`
	PriceListID    int64              `json:"price_list_id"`
	BuyerProfileID int64              `json:"buyer_profile_id"`
	AssignedBy     pgtype.Int8        `json:"assigned_by"`
	EffectiveFrom  time.Time          `json:"effective_from"`
	EffectiveTo    pgtype.Timestamptz `json:"effective_to"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

func (q *Queries) CreatePriceListAssignment(ctx context.Context, arg CreatePriceListAssignmentParams) (CreatePriceListAssignmentRow, error) {
	row := q.db.QueryRow(ctx, createPriceListAssignment,
		arg.Code,
		arg.PriceListID,
		arg.BuyerProfileID,
		arg.AssignedBy,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.IsActive,
	)
	var i CreatePriceListAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PriceListID,
		&i.BuyerProfileID,
		&i.AssignedBy,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPriceListItem = `-- name: CreatePriceListItem :one
INSERT INTO pricing.price_list_item (
    price_list_id, product_id, unit_id, currency, price_minor,
    min_quantity, max_quantity, effective_from, effective_to, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, price_list_id, product_id, unit_id, currency, price_minor,
    min_quantity, max_quantity, effective_from, effective_to, is_active,
    created_at, updated_at
`

type CreatePriceListItemParams struct {
	PriceListID   int64              `json:"price_list_id"`
	ProductID     int64              `json:"product_id"`
	UnitID        int64              `json:"unit_id"`
	Currency      string             `json:"currency"`
	PriceMinor    int64              `json:"price_minor"`
	MinQuantity   int32              `json:"min_quantity"`
	MaxQuantity   pgtype.Int4        `json:"max_quantity"`
	EffectiveFrom time.Time          `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `json:"effective_to"`
	IsActive      bool               `json:"is_active"`
}

type CreatePriceListItemRow struct {
	ID            int64              `json:"id"`
	PriceListID   int64              `json:"price_list_id"`
	ProductID     int64              `json:"product_id"`
	UnitID        int64              `json:"unit_id"`
	Currency      string             `json:"currency"`
	PriceMinor    int64              `json:"price_minor"`
	MinQuantity   int32              `json:"min_quantity"`
	MaxQuantity   pgtype.Int4        `json:"max_quantity"`
	EffectiveFrom time.Time          `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `json:"effective_to"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

func (q *Queries) CreatePriceListItem(ctx context.Context, arg CreatePriceListItemParams) (CreatePriceListItemRow, error) {
	row := q.db.QueryRow(ctx, createPriceListItem,
		arg.PriceListID,
		arg.ProductID,
		arg.UnitID,
		arg.Currency,
		arg.PriceMinor,
		arg.MinQuantity,
		arg.MaxQuantity,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.IsActive,
	)
	var i CreatePriceListItemRow
	err := row.Scan(
		&i.ID,
		&i.PriceListID,
		&i.ProductID,
		&i.UnitID,
		&i.Currency,
		&i.PriceMinor,
		&i.MinQuantity,
		&i.MaxQuantity,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuantityTier = `-- name: CreateQuantityTier :one
INSERT INTO pricing.quantity_tier (
    price_list_item_id, min_quantity, max_quantity, price_minor, is_active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, price_list_item_id, min_quantity, max_quantity, price_minor,
    is_active, created_at, updated_at
`

type CreateQuantityTierParams struct {
	PriceListItemID int64       `json:"price_list_item_id"`
	MinQuantity     int32       `json:"min_quantity"`
	MaxQuantity     pgtype.Int4 `json:"max_quantity"`
	PriceMinor      int64       `json:"price_minor"`
	IsActive        bool        `json:"is_active"`
}

type CreateQuantityTierRow struct {
	ID              int64       `json:"id"`
	PriceListItemID int64       `json:"price_list_item_id"`
	MinQuantity     int32       `json:"min_quantity"`
	MaxQuantity     pgtype.Int4 `json:"max_quantity"`
	PriceMinor      int64       `json:"price_minor"`
	IsActive        bool        `json:"is_active"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

func (q *Queries) CreateQuantityTier(ctx context.Context, arg CreateQuantityTierParams) (CreateQuantityTierRow, error) {
	row := q.db.QueryRow(ctx, createQuantityTier,
		arg.PriceListItemID,
		arg.MinQuantity,
		arg.MaxQuantity,
		arg.PriceMinor,
		arg.IsActive,
	)
	var i CreateQuantityTierRow
	err := row.Scan(
		&i.ID,
		&i.PriceListItemID,
		&i.MinQuantity,
		&i.MaxQuantity,
		&i.PriceMinor,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAssignmentForBuyer = `-- name: GetActiveAssignmentForBuyer :one
SELECT
    id, code, price_list_id, buyer_profile_id, assigned_by,
    effective_from, effective_to, is_active,
    created_at, updated_at, deleted_at
FROM pricing.price_list_assignment
WHERE deleted_at IS NULL
  AND buyer_profile_id = $1
  AND is_active = TRUE
  AND effective_from <= NOW()
  AND (effective_to IS NULL OR effective_to > NOW())
ORDER BY effective_from DESC
LIMIT 1
`

func (q *Queries) GetActiveAssignmentForBuyer(ctx context.Context, buyerProfileID int64) (PricingPriceListAssignment, error) {
	row := q.db.QueryRow(ctx, getActiveAssignmentForBuyer, buyerProfileID)
	var i PricingPriceListAssignment
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PriceListID,
		&i.BuyerProfileID,
		&i.AssignedBy,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActivePriceLists = `-- name: GetActivePriceLists :many
SELECT
    id, code, name, description, status, price_type, currency,
    effective_from, effective_to, is_active,
    created_at, updated_at, deleted_at
FROM pricing.price_list
WHERE deleted_at IS NULL
  AND is_active = TRUE
  AND status = 'active'
  AND effective_from <= NOW()
  AND (effective_to IS NULL OR effective_to > NOW())
ORDER BY created_at DESC
`

func (q *Queries) GetActivePriceLists(ctx context.Context) ([]PricingPriceList, error) {
	rows, err := q.db.Query(ctx, getActivePriceLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PricingPriceList{}
	for rows.Next() {
		var i PricingPriceList
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.PriceType,
			&i.Currency,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPriceForProduct = `-- name: GetPriceForProduct :many
SELECT
    pli.id, pli.price_list_id, pli.product_id, pli.unit_id, pli.currency,
    pli.price_minor, pli.min_quantity, pli.max_quantity,
    pli.effective_from, pli.effective_to, pli.is_active,
    pli.created_at, pli.updated_at, pli.deleted_at,
    qt.id as tier_id, qt.min_quantity as tier_min_quantity,
    qt.max_quantity as tier_max_quantity, qt.price_minor as tier_price_minor
FROM pricing.price_list_item pli
LEFT JOIN pricing.quantity_tier qt ON qt.price_list_item_id = pli.id AND qt.deleted_at IS NULL AND qt.is_active = TRUE
WHERE pli.deleted_at IS NULL
  AND pli.price_list_id = $1
  AND pli.product_id = $2
  AND pli.unit_id = $3
  AND pli.is_active = TRUE
  AND pli.effective_from <= NOW()
  AND (pli.effective_to IS NULL OR pli.effective_to > NOW())
ORDER BY pli.min_quantity, qt.min_quantity
`

type GetPriceForProductParams struct {
	PriceListID int64 `json:"price_list_id"`
	ProductID   int64 `json:"product_id"`
	UnitID      int64 `json:"unit_id"`
}

type GetPriceForProductRow struct {
	ID              int64              `json:"id"`
	PriceListID     int64              `json:"price_list_id"`
	ProductID       int64              `json:"product_id"`
	UnitID          int64              `json:"unit_id"`
	Currency        string             `json:"currency"`
	PriceMinor      int64              `json:"price_minor"`
	MinQuantity     int32              `json:"min_quantity"`
	MaxQuantity     pgtype.Int4        `json:"max_quantity"`
	EffectiveFrom   time.Time          `json:"effective_from"`
	EffectiveTo     pgtype.Timestamptz `json:"effective_to"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	TierID          pgtype.Int8        `json:"tier_id"`
	TierMinQuantity pgtype.Int4        `json:"tier_min_quantity"`
	TierMaxQuantity pgtype.Int4        `json:"tier_max_quantity"`
	TierPriceMinor  pgtype.Int8        `json:"tier_price_minor"`
}

func (q *Queries) GetPriceForProduct(ctx context.Context, arg GetPriceForProductParams) ([]GetPriceForProductRow, error) {
	rows, err := q.db.Query(ctx, getPriceForProduct, arg.PriceListID, arg.ProductID, arg.UnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPriceForProductRow{}
	for rows.Next() {
		var i GetPriceForProductRow
		if err := rows.Scan(
			&i.ID,
			&i.PriceListID,
			&i.ProductID,
			&i.UnitID,
			&i.Currency,
			&i.PriceMinor,
			&i.MinQuantity,
			&i.MaxQuantity,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TierID,
			&i.TierMinQuantity,
			&i.TierMaxQuantity,
			&i.TierPriceMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPriceForQuote = `-- name: GetPriceForQuote :many
SELECT
    pli.id, pli.price_list_id, pli.product_id, pli.unit_id, pli.currency,
    pli.price_minor, pli.min_quantity, pli.max_quantity,
    pli.effective_from, pli.effective_to, pli.is_active,
    qt.id as tier_id, qt.min_quantity as tier_min_quantity,
    qt.max_quantity as tier_max_quantity, qt.price_minor as tier_price_minor
FROM pricing.price_list_item pli
LEFT JOIN pricing.quantity_tier qt ON qt.price_list_item_id = pli.id AND qt.deleted_at IS NULL AND qt.is_active = TRUE
WHERE pli.deleted_at IS NULL
  AND pli.price_list_id = $1
  AND pli.product_id = $2
  AND pli.unit_id = $3
  AND pli.is_active = TRUE
  AND pli.effective_from <= NOW()
  AND (pli.effective_to IS NULL OR pli.effective_to > NOW())
ORDER BY pli.min_quantity, qt.min_quantity
`

type GetPriceForQuoteParams struct {
	PriceListID int64 `json:"price_list_id"`
	ProductID   int64 `json:"product_id"`
	UnitID      int64 `json:"unit_id"`
}

type GetPriceForQuoteRow struct {
	ID              int64              `json:"id"`
	PriceListID     int64              `json:"price_list_id"`
	ProductID       int64              `json:"product_id"`
	UnitID          int64              `json:"unit_id"`
	Currency        string             `json:"currency"`
	PriceMinor      int64              `json:"price_minor"`
	MinQuantity     int32              `json:"min_quantity"`
	MaxQuantity     pgtype.Int4        `json:"max_quantity"`
	EffectiveFrom   time.Time          `json:"effective_from"`
	EffectiveTo     pgtype.Timestamptz `json:"effective_to"`
	IsActive        bool               `json:"is_active"`
	TierID          pgtype.Int8        `json:"tier_id"`
	TierMinQuantity pgtype.Int4        `json:"tier_min_quantity"`
	TierMaxQuantity pgtype.Int4        `json:"tier_max_quantity"`
	TierPriceMinor  pgtype.Int8        `json:"tier_price_minor"`
}

func (q *Queries) GetPriceForQuote(ctx context.Context, arg GetPriceForQuoteParams) ([]GetPriceForQuoteRow, error) {
	rows, err := q.db.Query(ctx, getPriceForQuote, arg.PriceListID, arg.ProductID, arg.UnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPriceForQuoteRow{}
	for rows.Next() {
		var i GetPriceForQuoteRow
		if err := rows.Scan(
			&i.ID,
			&i.PriceListID,
			&i.ProductID,
			&i.UnitID,
			&i.Currency,
			&i.PriceMinor,
			&i.MinQuantity,
			&i.MaxQuantity,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.IsActive,
			&i.TierID,
			&i.TierMinQuantity,
			&i.TierMaxQuantity,
			&i.TierPriceMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPriceListAssignmentByCode = `-- name: GetPriceListAssignmentByCode :one
SELECT
    id, code, price_list_id, buyer_profile_id, assigned_by,
    effective_from, effective_to, is_active,
    created_at, updated_at, deleted_at
FROM pricing.price_list_assignment
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPriceListAssignmentByCode(ctx context.Context, code string) (PricingPriceListAssignment, error) {
	row := q.db.QueryRow(ctx, getPriceListAssignmentByCode, code)
	var i PricingPriceListAssignment
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PriceListID,
		&i.BuyerProfileID,
		&i.AssignedBy,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPriceListAssignmentByID = `-- name: GetPriceListAssignmentByID :one
SELECT
    id, code, price_list_id, buyer_profile_id, assigned_by,
    effective_from, effective_to, is_active,
    created_at, updated_at, deleted_at
FROM pricing.price_list_assignment
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPriceListAssignmentByID(ctx context.Context, id int64) (PricingPriceListAssignment, error) {
	row := q.db.QueryRow(ctx, getPriceListAssignmentByID, id)
	var i PricingPriceListAssignment
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PriceListID,
		&i.BuyerProfileID,
		&i.AssignedBy,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPriceListByCode = `-- name: GetPriceListByCode :one
SELECT
    id, code, name, description, status, price_type, currency,
    effective_from, effective_to, is_active,
    created_at, updated_at, deleted_at
FROM pricing.price_list
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPriceListByCode(ctx context.Context, code string) (PricingPriceList, error) {
	row := q.db.QueryRow(ctx, getPriceListByCode, code)
	var i PricingPriceList
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PriceType,
		&i.Currency,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPriceListByID = `-- name: GetPriceListByID :one
SELECT
    id, code, name, description, status, price_type, currency,
    effective_from, effective_to, is_active,
    created_at, updated_at, deleted_at
FROM pricing.price_list
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPriceListByID(ctx context.Context, id int64) (PricingPriceList, error) {
	row := q.db.QueryRow(ctx, getPriceListByID, id)
	var i PricingPriceList
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PriceType,
		&i.Currency,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPriceListItemByID = `-- name: GetPriceListItemByID :one
SELECT
    id, price_list_id, product_id, unit_id, currency, price_minor,
    min_quantity, max_quantity, effective_from, effective_to, is_active,
    created_at, updated_at, deleted_at
FROM pricing.price_list_item
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPriceListItemByID(ctx context.Context, id int64) (PricingPriceListItem, error) {
	row := q.db.QueryRow(ctx, getPriceListItemByID, id)
	var i PricingPriceListItem
	err := row.Scan(
		&i.ID,
		&i.PriceListID,
		&i.ProductID,
		&i.UnitID,
		&i.Currency,
		&i.PriceMinor,
		&i.MinQuantity,
		&i.MaxQuantity,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPriceListItemsByList = `-- name: GetPriceListItemsByList :many
SELECT
    id, price_list_id, product_id, unit_id, currency, price_minor,
    min_quantity, max_quantity, effective_from, effective_to, is_active,
    created_at, updated_at, deleted_at
FROM pricing.price_list_item
WHERE deleted_at IS NULL
  AND price_list_id = $1
  AND is_active = TRUE
  AND effective_from <= NOW()
  AND (effective_to IS NULL OR effective_to > NOW())
ORDER BY product_id, min_quantity
`

func (q *Queries) GetPriceListItemsByList(ctx context.Context, priceListID int64) ([]PricingPriceListItem, error) {
	rows, err := q.db.Query(ctx, getPriceListItemsByList, priceListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PricingPriceListItem{}
	for rows.Next() {
		var i PricingPriceListItem
		if err := rows.Scan(
			&i.ID,
			&i.PriceListID,
			&i.ProductID,
			&i.UnitID,
			&i.Currency,
			&i.PriceMinor,
			&i.MinQuantity,
			&i.MaxQuantity,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPriceListWithItems = `-- name: GetPriceListWithItems :one
SELECT
    pl.id, pl.code, pl.name, pl.description, pl.status, pl.price_type, pl.currency,
    pl.effective_from, pl.effective_to, pl.is_active,
    pl.created_at, pl.updated_at, pl.deleted_at
FROM pricing.price_list pl
WHERE pl.id = $1 AND pl.deleted_at IS NULL
`

func (q *Queries) GetPriceListWithItems(ctx context.Context, id int64) (PricingPriceList, error) {
	row := q.db.QueryRow(ctx, getPriceListWithItems, id)
	var i PricingPriceList
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PriceType,
		&i.Currency,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getQuantityTierByID = `-- name: GetQuantityTierByID :one
SELECT
    id, price_list_item_id, min_quantity, max_quantity, price_minor,
    is_active, created_at, updated_at, deleted_at
FROM pricing.quantity_tier
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetQuantityTierByID(ctx context.Context, id int64) (PricingQuantityTier, error) {
	row := q.db.QueryRow(ctx, getQuantityTierByID, id)
	var i PricingQuantityTier
	err := row.Scan(
		&i.ID,
		&i.PriceListItemID,
		&i.MinQuantity,
		&i.MaxQuantity,
		&i.PriceMinor,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getQuantityTiersByItem = `-- name: GetQuantityTiersByItem :many
SELECT
    id, price_list_item_id, min_quantity, max_quantity, price_minor,
    is_active, created_at, updated_at, deleted_at
FROM pricing.quantity_tier
WHERE deleted_at IS NULL
  AND price_list_item_id = $1
  AND is_active = TRUE
ORDER BY min_quantity
`

func (q *Queries) GetQuantityTiersByItem(ctx context.Context, priceListItemID int64) ([]PricingQuantityTier, error) {
	rows, err := q.db.Query(ctx, getQuantityTiersByItem, priceListItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PricingQuantityTier{}
	for rows.Next() {
		var i PricingQuantityTier
		if err := rows.Scan(
			&i.ID,
			&i.PriceListItemID,
			&i.MinQuantity,
			&i.MaxQuantity,
			&i.PriceMinor,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceListAssignments = `-- name: ListPriceListAssignments :many
SELECT
    id, code, price_list_id, buyer_profile_id, assigned_by,
    effective_from, effective_to, is_active,
    created_at, updated_at, deleted_at
FROM pricing.price_list_assignment
WHERE deleted_at IS NULL
  AND ($1::bigint IS NULL OR price_list_id = $1)
  AND ($2::bigint IS NULL OR buyer_profile_id = $2)
  AND ($3::boolean IS NULL OR is_active = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListPriceListAssignmentsParams struct {
	Column1 int64 `json:"column_1"`
	Column2 int64 `json:"column_2"`
	Column3 bool  `json:"column_3"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListPriceListAssignments(ctx context.Context, arg ListPriceListAssignmentsParams) ([]PricingPriceListAssignment, error) {
	rows, err := q.db.Query(ctx, listPriceListAssignments,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PricingPriceListAssignment{}
	for rows.Next() {
		var i PricingPriceListAssignment
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.PriceListID,
			&i.BuyerProfileID,
			&i.AssignedBy,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceListItems = `-- name: ListPriceListItems :many
SELECT
    id, price_list_id, product_id, unit_id, currency, price_minor,
    min_quantity, max_quantity, effective_from, effective_to, is_active,
    created_at, updated_at, deleted_at
FROM pricing.price_list_item
WHERE deleted_at IS NULL
  AND ($1::bigint IS NULL OR price_list_id = $1)
  AND ($2::bigint IS NULL OR product_id = $2)
  AND ($3::bigint IS NULL OR unit_id = $3)
  AND ($4::boolean IS NULL OR is_active = $4)
ORDER BY product_id, min_quantity
LIMIT $5 OFFSET $6
`

type ListPriceListItemsParams struct {
	Column1 int64 `json:"column_1"`
	Column2 int64 `json:"column_2"`
	Column3 int64 `json:"column_3"`
	Column4 bool  `json:"column_4"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListPriceListItems(ctx context.Context, arg ListPriceListItemsParams) ([]PricingPriceListItem, error) {
	rows, err := q.db.Query(ctx, listPriceListItems,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PricingPriceListItem{}
	for rows.Next() {
		var i PricingPriceListItem
		if err := rows.Scan(
			&i.ID,
			&i.PriceListID,
			&i.ProductID,
			&i.UnitID,
			&i.Currency,
			&i.PriceMinor,
			&i.MinQuantity,
			&i.MaxQuantity,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceLists = `-- name: ListPriceLists :many
SELECT
    id, code, name, description, status, price_type, currency,
    effective_from, effective_to, is_active,
    created_at, updated_at, deleted_at
FROM pricing.price_list
WHERE deleted_at IS NULL
  AND ($1::pricing.price_list_status IS NULL OR status = $1)
  AND ($2::boolean IS NULL OR is_active = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListPriceListsParams struct {
	Column1 PricingPriceListStatus `json:"column_1"`
	Column2 bool                   `json:"column_2"`
	Limit   int32                  `json:"limit"`
	Offset  int32                  `json:"offset"`
}

func (q *Queries) ListPriceLists(ctx context.Context, arg ListPriceListsParams) ([]PricingPriceList, error) {
	rows, err := q.db.Query(ctx, listPriceLists,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PricingPriceList{}
	for rows.Next() {
		var i PricingPriceList
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.PriceType,
			&i.Currency,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuantityTiers = `-- name: ListQuantityTiers :many
SELECT
    id, price_list_item_id, min_quantity, max_quantity, price_minor,
    is_active, created_at, updated_at, deleted_at
FROM pricing.quantity_tier
WHERE deleted_at IS NULL
  AND ($1::bigint IS NULL OR price_list_item_id = $1)
  AND ($2::boolean IS NULL OR is_active = $2)
ORDER BY min_quantity
`

type ListQuantityTiersParams struct {
	Column1 int64 `json:"column_1"`
	Column2 bool  `json:"column_2"`
}

func (q *Queries) ListQuantityTiers(ctx context.Context, arg ListQuantityTiersParams) ([]PricingQuantityTier, error) {
	rows, err := q.db.Query(ctx, listQuantityTiers, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PricingQuantityTier{}
	for rows.Next() {
		var i PricingQuantityTier
		if err := rows.Scan(
			&i.ID,
			&i.PriceListItemID,
			&i.MinQuantity,
			&i.MaxQuantity,
			&i.PriceMinor,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePriceList = `-- name: SoftDeletePriceList :exec
UPDATE pricing.price_list
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeletePriceList(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeletePriceList, id)
	return err
}

const softDeletePriceListAssignment = `-- name: SoftDeletePriceListAssignment :exec
UPDATE pricing.price_list_assignment
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeletePriceListAssignment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeletePriceListAssignment, id)
	return err
}

const softDeletePriceListItem = `-- name: SoftDeletePriceListItem :exec
UPDATE pricing.price_list_item
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeletePriceListItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeletePriceListItem, id)
	return err
}

const softDeleteQuantityTier = `-- name: SoftDeleteQuantityTier :exec
UPDATE pricing.quantity_tier
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteQuantityTier(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteQuantityTier, id)
	return err
}

const updatePriceList = `-- name: UpdatePriceList :one
UPDATE pricing.price_list
SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    status = COALESCE($4, status),
    price_type = COALESCE($5, price_type),
    currency = COALESCE($6, currency),
    effective_from = COALESCE($7, effective_from),
    effective_to = COALESCE($8, effective_to),
    is_active = COALESCE($9, is_active),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, name, status, updated_at
`

type UpdatePriceListParams struct {
	ID            int64                  `json:"id"`
	Name          string                 `json:"name"`
	Description   pgtype.Text            `json:"description"`
	Status        PricingPriceListStatus `json:"status"`
	PriceType     PricingPriceType       `json:"price_type"`
	Currency      string                 `json:"currency"`
	EffectiveFrom time.Time              `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz     `json:"effective_to"`
	IsActive      bool                   `json:"is_active"`
}

type UpdatePriceListRow struct {
	ID        int64                  `json:"id"`
	Code      string                 `json:"code"`
	Name      string                 `json:"name"`
	Status    PricingPriceListStatus `json:"status"`
	UpdatedAt time.Time              `json:"updated_at"`
}

func (q *Queries) UpdatePriceList(ctx context.Context, arg UpdatePriceListParams) (UpdatePriceListRow, error) {
	row := q.db.QueryRow(ctx, updatePriceList,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.PriceType,
		arg.Currency,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.IsActive,
	)
	var i UpdatePriceListRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePriceListAssignment = `-- name: UpdatePriceListAssignment :one
UPDATE pricing.price_list_assignment
SET
    price_list_id = COALESCE($2, price_list_id),
    effective_from = COALESCE($3, effective_from),
    effective_to = COALESCE($4, effective_to),
    is_active = COALESCE($5, is_active),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, price_list_id, buyer_profile_id, assigned_by,
    effective_from, effective_to, is_active, updated_at
`

type UpdatePriceListAssignmentParams struct {
	ID            int64              `json:"id"`
	PriceListID   int64              `json:"price_list_id"`
	EffectiveFrom time.Time          `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `json:"effective_to"`
	IsActive      bool               `json:"is_active"`
}

type UpdatePriceListAssignmentRow struct {
	ID             int64              `json:"id"`
	Code           string             `json:"code"`
	PriceListID    int64              `json:"price_list_id"`
	BuyerProfileID int64              `json:"buyer_profile_id"`
	AssignedBy     pgtype.Int8        `json:"assigned_by"`
	EffectiveFrom  time.Time          `json:"effective_from"`
	EffectiveTo    pgtype.Timestamptz `json:"effective_to"`
	IsActive       bool               `json:"is_active"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

func (q *Queries) UpdatePriceListAssignment(ctx context.Context, arg UpdatePriceListAssignmentParams) (UpdatePriceListAssignmentRow, error) {
	row := q.db.QueryRow(ctx, updatePriceListAssignment,
		arg.ID,
		arg.PriceListID,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.IsActive,
	)
	var i UpdatePriceListAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PriceListID,
		&i.BuyerProfileID,
		&i.AssignedBy,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsActive,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePriceListItem = `-- name: UpdatePriceListItem :one
UPDATE pricing.price_list_item
SET
    currency = COALESCE($2, currency),
    price_minor = COALESCE($3, price_minor),
    min_quantity = COALESCE($4, min_quantity),
    max_quantity = COALESCE($5, max_quantity),
    effective_from = COALESCE($6, effective_from),
    effective_to = COALESCE($7, effective_to),
    is_active = COALESCE($8, is_active),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, price_list_id, product_id, unit_id, currency, price_minor,
    min_quantity, max_quantity, effective_from, effective_to, is_active,
    updated_at
`

type UpdatePriceListItemParams struct {
	ID            int64              `json:"id"`
	Currency      string             `json:"currency"`
	PriceMinor    int64              `json:"price_minor"`
	MinQuantity   int32              `json:"min_quantity"`
	MaxQuantity   pgtype.Int4        `json:"max_quantity"`
	EffectiveFrom time.Time          `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `json:"effective_to"`
	IsActive      bool               `json:"is_active"`
}

type UpdatePriceListItemRow struct {
	ID            int64              `json:"id"`
	PriceListID   int64              `json:"price_list_id"`
	ProductID     int64              `json:"product_id"`
	UnitID        int64              `json:"unit_id"`
	Currency      string             `json:"currency"`
	PriceMinor    int64              `json:"price_minor"`
	MinQuantity   int32              `json:"min_quantity"`
	MaxQuantity   pgtype.Int4        `json:"max_quantity"`
	EffectiveFrom time.Time          `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `json:"effective_to"`
	IsActive      bool               `json:"is_active"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

func (q *Queries) UpdatePriceListItem(ctx context.Context, arg UpdatePriceListItemParams) (UpdatePriceListItemRow, error) {
	row := q.db.QueryRow(ctx, updatePriceListItem,
		arg.ID,
		arg.Currency,
		arg.PriceMinor,
		arg.MinQuantity,
		arg.MaxQuantity,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.IsActive,
	)
	var i UpdatePriceListItemRow
	err := row.Scan(
		&i.ID,
		&i.PriceListID,
		&i.ProductID,
		&i.UnitID,
		&i.Currency,
		&i.PriceMinor,
		&i.MinQuantity,
		&i.MaxQuantity,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsActive,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuantityTier = `-- name: UpdateQuantityTier :one
UPDATE pricing.quantity_tier
SET
    min_quantity = COALESCE($2, min_quantity),
    max_quantity = COALESCE($3, max_quantity),
    price_minor = COALESCE($4, price_minor),
    is_active = COALESCE($5, is_active),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, price_list_item_id, min_quantity, max_quantity, price_minor,
    is_active, updated_at
`

type UpdateQuantityTierParams struct {
	ID          int64       `json:"id"`
	MinQuantity int32       `json:"min_quantity"`
	MaxQuantity pgtype.Int4 `json:"max_quantity"`
	PriceMinor  int64       `json:"price_minor"`
	IsActive    bool        `json:"is_active"`
}

type UpdateQuantityTierRow struct {
	ID              int64       `json:"id"`
	PriceListItemID int64       `json:"price_list_item_id"`
	MinQuantity     int32       `json:"min_quantity"`
	MaxQuantity     pgtype.Int4 `json:"max_quantity"`
	PriceMinor      int64       `json:"price_minor"`
	IsActive        bool        `json:"is_active"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateQuantityTier(ctx context.Context, arg UpdateQuantityTierParams) (UpdateQuantityTierRow, error) {
	row := q.db.QueryRow(ctx, updateQuantityTier,
		arg.ID,
		arg.MinQuantity,
		arg.MaxQuantity,
		arg.PriceMinor,
		arg.IsActive,
	)
	var i UpdateQuantityTierRow
	err := row.Scan(
		&i.ID,
		&i.PriceListItemID,
		&i.MinQuantity,
		&i.MaxQuantity,
		&i.PriceMinor,
		&i.IsActive,
		&i.UpdatedAt,
	)
	return i, err
}
