// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pricing

import (
	"context"
)

type Querier interface {
	CountPriceListAssignments(ctx context.Context, arg CountPriceListAssignmentsParams) (int64, error)
	CountPriceListItems(ctx context.Context, arg CountPriceListItemsParams) (int64, error)
	CountPriceLists(ctx context.Context, arg CountPriceListsParams) (int64, error)
	// Pricing module queries
	// Price Lists, Price Items, Quantity Tiers, Buyer Assignments
	CreatePriceList(ctx context.Context, arg CreatePriceListParams) (CreatePriceListRow, error)
	CreatePriceListAssignment(ctx context.Context, arg CreatePriceListAssignmentParams) (CreatePriceListAssignmentRow, error)
	CreatePriceListItem(ctx context.Context, arg CreatePriceListItemParams) (CreatePriceListItemRow, error)
	CreateQuantityTier(ctx context.Context, arg CreateQuantityTierParams) (CreateQuantityTierRow, error)
	GetActiveAssignmentForBuyer(ctx context.Context, buyerProfileID int64) (PricingPriceListAssignment, error)
	GetActivePriceLists(ctx context.Context) ([]PricingPriceList, error)
	GetPriceForProduct(ctx context.Context, arg GetPriceForProductParams) ([]GetPriceForProductRow, error)
	GetPriceForQuote(ctx context.Context, arg GetPriceForQuoteParams) ([]GetPriceForQuoteRow, error)
	GetPriceListAssignmentByCode(ctx context.Context, code string) (PricingPriceListAssignment, error)
	GetPriceListAssignmentByID(ctx context.Context, id int64) (PricingPriceListAssignment, error)
	GetPriceListByCode(ctx context.Context, code string) (PricingPriceList, error)
	GetPriceListByID(ctx context.Context, id int64) (PricingPriceList, error)
	GetPriceListItemByID(ctx context.Context, id int64) (PricingPriceListItem, error)
	GetPriceListItemsByList(ctx context.Context, priceListID int64) ([]PricingPriceListItem, error)
	GetPriceListWithItems(ctx context.Context, id int64) (PricingPriceList, error)
	GetQuantityTierByID(ctx context.Context, id int64) (PricingQuantityTier, error)
	GetQuantityTiersByItem(ctx context.Context, priceListItemID int64) ([]PricingQuantityTier, error)
	ListPriceListAssignments(ctx context.Context, arg ListPriceListAssignmentsParams) ([]PricingPriceListAssignment, error)
	ListPriceListItems(ctx context.Context, arg ListPriceListItemsParams) ([]PricingPriceListItem, error)
	ListPriceLists(ctx context.Context, arg ListPriceListsParams) ([]PricingPriceList, error)
	ListQuantityTiers(ctx context.Context, arg ListQuantityTiersParams) ([]PricingQuantityTier, error)
	SoftDeletePriceList(ctx context.Context, id int64) error
	SoftDeletePriceListAssignment(ctx context.Context, id int64) error
	SoftDeletePriceListItem(ctx context.Context, id int64) error
	SoftDeleteQuantityTier(ctx context.Context, id int64) error
	UpdatePriceList(ctx context.Context, arg UpdatePriceListParams) (UpdatePriceListRow, error)
	UpdatePriceListAssignment(ctx context.Context, arg UpdatePriceListAssignmentParams) (UpdatePriceListAssignmentRow, error)
	UpdatePriceListItem(ctx context.Context, arg UpdatePriceListItemParams) (UpdatePriceListItemRow, error)
	UpdateQuantityTier(ctx context.Context, arg UpdateQuantityTierParams) (UpdateQuantityTierRow, error)
}

var _ Querier = (*Queries)(nil)
