// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package queries

import (
	"context"
)

const getHealthCheckRecords = `-- name: GetHealthCheckRecords :many
SELECT id, checked_at, status
FROM platform.health_check
ORDER BY checked_at DESC
LIMIT $1
`

func (q *Queries) GetHealthCheckRecords(ctx context.Context, limit int32) ([]PlatformHealthCheck, error) {
	rows, err := q.db.Query(ctx, getHealthCheckRecords, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformHealthCheck{}
	for rows.Next() {
		var i PlatformHealthCheck
		if err := rows.Scan(&i.ID, &i.CheckedAt, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const healthCheck = `-- name: HealthCheck :one

SELECT 1 AS ok
`

// Health check queries for database connectivity verification
func (q *Queries) HealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}

const healthCheckWithTimestamp = `-- name: HealthCheckWithTimestamp :one
SELECT 
    1 AS ok,
    NOW() AS server_time,
    version() AS postgres_version
`

type HealthCheckWithTimestampRow struct {
	Ok              int32       `json:"ok"`
	ServerTime      interface{} `json:"server_time"`
	PostgresVersion string      `json:"postgres_version"`
}

func (q *Queries) HealthCheckWithTimestamp(ctx context.Context) (HealthCheckWithTimestampRow, error) {
	row := q.db.QueryRow(ctx, healthCheckWithTimestamp)
	var i HealthCheckWithTimestampRow
	err := row.Scan(&i.Ok, &i.ServerTime, &i.PostgresVersion)
	return i, err
}

const insertHealthCheck = `-- name: InsertHealthCheck :one
INSERT INTO platform.health_check (status)
VALUES ($1)
RETURNING id, checked_at, status
`

func (q *Queries) InsertHealthCheck(ctx context.Context, status string) (PlatformHealthCheck, error) {
	row := q.db.QueryRow(ctx, insertHealthCheck, status)
	var i PlatformHealthCheck
	err := row.Scan(&i.ID, &i.CheckedAt, &i.Status)
	return i, err
}
