// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CatalogHandlingClassType string

const (
	CatalogHandlingClassTypeAmbient CatalogHandlingClassType = "ambient"
	CatalogHandlingClassTypeChilled CatalogHandlingClassType = "chilled"
	CatalogHandlingClassTypeFrozen  CatalogHandlingClassType = "frozen"
)

func (e *CatalogHandlingClassType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogHandlingClassType(s)
	case string:
		*e = CatalogHandlingClassType(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogHandlingClassType: %T", src)
	}
	return nil
}

type NullCatalogHandlingClassType struct {
	CatalogHandlingClassType CatalogHandlingClassType `json:"catalog_handling_class_type"`
	Valid                    bool                     `json:"valid"` // Valid is true if CatalogHandlingClassType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogHandlingClassType) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogHandlingClassType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogHandlingClassType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogHandlingClassType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogHandlingClassType), nil
}

type CatalogProductStatus string

const (
	CatalogProductStatusDraft     CatalogProductStatus = "draft"
	CatalogProductStatusPublished CatalogProductStatus = "published"
	CatalogProductStatusArchived  CatalogProductStatus = "archived"
)

func (e *CatalogProductStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogProductStatus(s)
	case string:
		*e = CatalogProductStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogProductStatus: %T", src)
	}
	return nil
}

type NullCatalogProductStatus struct {
	CatalogProductStatus CatalogProductStatus `json:"catalog_product_status"`
	Valid                bool                 `json:"valid"` // Valid is true if CatalogProductStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogProductStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogProductStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogProductStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogProductStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogProductStatus), nil
}

type CatalogUnitType string

const (
	CatalogUnitTypeBase    CatalogUnitType = "base"
	CatalogUnitTypeDerived CatalogUnitType = "derived"
)

func (e *CatalogUnitType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogUnitType(s)
	case string:
		*e = CatalogUnitType(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogUnitType: %T", src)
	}
	return nil
}

type NullCatalogUnitType struct {
	CatalogUnitType CatalogUnitType `json:"catalog_unit_type"`
	Valid           bool            `json:"valid"` // Valid is true if CatalogUnitType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogUnitType) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogUnitType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogUnitType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogUnitType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogUnitType), nil
}

type IdentityUserType string

const (
	IdentityUserTypeBuyer    IdentityUserType = "buyer"
	IdentityUserTypeSupplier IdentityUserType = "supplier"
	IdentityUserTypeStaff    IdentityUserType = "staff"
	IdentityUserTypePlatform IdentityUserType = "platform"
)

func (e *IdentityUserType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IdentityUserType(s)
	case string:
		*e = IdentityUserType(s)
	default:
		return fmt.Errorf("unsupported scan type for IdentityUserType: %T", src)
	}
	return nil
}

type NullIdentityUserType struct {
	IdentityUserType IdentityUserType `json:"identity_user_type"`
	Valid            bool             `json:"valid"` // Valid is true if IdentityUserType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIdentityUserType) Scan(value interface{}) error {
	if value == nil {
		ns.IdentityUserType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IdentityUserType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIdentityUserType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IdentityUserType), nil
}

type IdentityVerificationDecision string

const (
	IdentityVerificationDecisionApproved IdentityVerificationDecision = "approved"
	IdentityVerificationDecisionRejected IdentityVerificationDecision = "rejected"
)

func (e *IdentityVerificationDecision) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IdentityVerificationDecision(s)
	case string:
		*e = IdentityVerificationDecision(s)
	default:
		return fmt.Errorf("unsupported scan type for IdentityVerificationDecision: %T", src)
	}
	return nil
}

type NullIdentityVerificationDecision struct {
	IdentityVerificationDecision IdentityVerificationDecision `json:"identity_verification_decision"`
	Valid                        bool                         `json:"valid"` // Valid is true if IdentityVerificationDecision is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIdentityVerificationDecision) Scan(value interface{}) error {
	if value == nil {
		ns.IdentityVerificationDecision, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IdentityVerificationDecision.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIdentityVerificationDecision) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IdentityVerificationDecision), nil
}

type IdentityVerificationStatus string

const (
	IdentityVerificationStatusPending     IdentityVerificationStatus = "pending"
	IdentityVerificationStatusApproved    IdentityVerificationStatus = "approved"
	IdentityVerificationStatusRejected    IdentityVerificationStatus = "rejected"
	IdentityVerificationStatusResubmitted IdentityVerificationStatus = "resubmitted"
)

func (e *IdentityVerificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IdentityVerificationStatus(s)
	case string:
		*e = IdentityVerificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IdentityVerificationStatus: %T", src)
	}
	return nil
}

type NullIdentityVerificationStatus struct {
	IdentityVerificationStatus IdentityVerificationStatus `json:"identity_verification_status"`
	Valid                      bool                       `json:"valid"` // Valid is true if IdentityVerificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIdentityVerificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IdentityVerificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IdentityVerificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIdentityVerificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IdentityVerificationStatus), nil
}

type PricingPriceListStatus string

const (
	PricingPriceListStatusDraft    PricingPriceListStatus = "draft"
	PricingPriceListStatusActive   PricingPriceListStatus = "active"
	PricingPriceListStatusInactive PricingPriceListStatus = "inactive"
	PricingPriceListStatusArchived PricingPriceListStatus = "archived"
)

func (e *PricingPriceListStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PricingPriceListStatus(s)
	case string:
		*e = PricingPriceListStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PricingPriceListStatus: %T", src)
	}
	return nil
}

type NullPricingPriceListStatus struct {
	PricingPriceListStatus PricingPriceListStatus `json:"pricing_price_list_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if PricingPriceListStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPricingPriceListStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PricingPriceListStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PricingPriceListStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPricingPriceListStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PricingPriceListStatus), nil
}

type PricingPriceType string

const (
	PricingPriceTypeStandard    PricingPriceType = "standard"
	PricingPriceTypeContract    PricingPriceType = "contract"
	PricingPriceTypePromotional PricingPriceType = "promotional"
)

func (e *PricingPriceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PricingPriceType(s)
	case string:
		*e = PricingPriceType(s)
	default:
		return fmt.Errorf("unsupported scan type for PricingPriceType: %T", src)
	}
	return nil
}

type NullPricingPriceType struct {
	PricingPriceType PricingPriceType `json:"pricing_price_type"`
	Valid            bool             `json:"valid"` // Valid is true if PricingPriceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPricingPriceType) Scan(value interface{}) error {
	if value == nil {
		ns.PricingPriceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PricingPriceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPricingPriceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PricingPriceType), nil
}

type CatalogAttribute struct {
	ID            int64              `json:"id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	AttributeType string             `json:"attribute_type"`
	IsFilterable  bool               `json:"is_filterable"`
	IsRequired    bool               `json:"is_required"`
	SortOrder     int32              `json:"sort_order"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type CatalogAttributeValue struct {
	ID          int64              `json:"id"`
	AttributeID int64              `json:"attribute_id"`
	Value       string             `json:"value"`
	SortOrder   int32              `json:"sort_order"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type CatalogBrand struct {
	ID          int64              `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	LogoUrl     pgtype.Text        `json:"logo_url"`
	WebsiteUrl  pgtype.Text        `json:"website_url"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type CatalogCategory struct {
	ID             int64              `json:"id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	ParentID       pgtype.Int8        `json:"parent_id"`
	SortOrder      int32              `json:"sort_order"`
	IsActive       bool               `json:"is_active"`
	SeoTitle       pgtype.Text        `json:"seo_title"`
	SeoDescription pgtype.Text        `json:"seo_description"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type CatalogHandlingClass struct {
	ID              int64                    `json:"id"`
	Code            string                   `json:"code"`
	Name            CatalogHandlingClassType `json:"name"`
	Description     pgtype.Text              `json:"description"`
	SortOrder       int32                    `json:"sort_order"`
	TemperatureMinC pgtype.Int4              `json:"temperature_min_c"`
	TemperatureMaxC pgtype.Int4              `json:"temperature_max_c"`
	CreatedAt       time.Time                `json:"created_at"`
	UpdatedAt       time.Time                `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz       `json:"deleted_at"`
}

type CatalogProduct struct {
	ID               int64                    `json:"id"`
	Code             string                   `json:"code"`
	Slug             string                   `json:"slug"`
	Name             string                   `json:"name"`
	Description      pgtype.Text              `json:"description"`
	ShortDescription pgtype.Text              `json:"short_description"`
	CategoryID       int64                    `json:"category_id"`
	BrandID          pgtype.Int8              `json:"brand_id"`
	HandlingClass    CatalogHandlingClassType `json:"handling_class"`
	BaseUnitID       int64                    `json:"base_unit_id"`
	SupplierID       pgtype.Int8              `json:"supplier_id"`
	Status           CatalogProductStatus     `json:"status"`
	IsActive         bool                     `json:"is_active"`
	IsFeatured       bool                     `json:"is_featured"`
	SortOrder        int32                    `json:"sort_order"`
	SeoTitle         pgtype.Text              `json:"seo_title"`
	SeoDescription   pgtype.Text              `json:"seo_description"`
	SeoKeywords      pgtype.Text              `json:"seo_keywords"`
	BasePriceMinor   pgtype.Int8              `json:"base_price_minor"`
	Currency         string                   `json:"currency"`
	TrackInventory   bool                     `json:"track_inventory"`
	WeightGrams      pgtype.Int4              `json:"weight_grams"`
	LengthMm         pgtype.Int4              `json:"length_mm"`
	WidthMm          pgtype.Int4              `json:"width_mm"`
	HeightMm         pgtype.Int4              `json:"height_mm"`
	Gtin             pgtype.Text              `json:"gtin"`
	Sku              pgtype.Text              `json:"sku"`
	CreatedAt        time.Time                `json:"created_at"`
	UpdatedAt        time.Time                `json:"updated_at"`
	PublishedAt      pgtype.Timestamptz       `json:"published_at"`
	DeletedAt        pgtype.Timestamptz       `json:"deleted_at"`
}

type CatalogProductAttribute struct {
	ID               int64              `json:"id"`
	ProductID        int64              `json:"product_id"`
	AttributeID      int64              `json:"attribute_id"`
	AttributeValueID pgtype.Int8        `json:"attribute_value_id"`
	TextValue        pgtype.Text        `json:"text_value"`
	NumberValue      pgtype.Numeric     `json:"number_value"`
	BooleanValue     pgtype.Bool        `json:"boolean_value"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type CatalogProductMedium struct {
	ID            int64              `json:"id"`
	Code          string             `json:"code"`
	ProductID     int64              `json:"product_id"`
	Url           string             `json:"url"`
	AltText       pgtype.Text        `json:"alt_text"`
	MediaType     string             `json:"media_type"`
	SortOrder     int32              `json:"sort_order"`
	IsPrimary     bool               `json:"is_primary"`
	WidthPx       pgtype.Int4        `json:"width_px"`
	HeightPx      pgtype.Int4        `json:"height_px"`
	FileSizeBytes pgtype.Int8        `json:"file_size_bytes"`
	MimeType      pgtype.Text        `json:"mime_type"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type CatalogProductUnit struct {
	ID               int64              `json:"id"`
	ProductID        int64              `json:"product_id"`
	UnitID           int64              `json:"unit_id"`
	ConversionFactor pgtype.Numeric     `json:"conversion_factor"`
	IsDefault        bool               `json:"is_default"`
	PriceMinor       pgtype.Int8        `json:"price_minor"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type CatalogSupplier struct {
	ID          int64              `json:"id"`
	Code        string             `json:"code"`
	SupplierID  int64              `json:"supplier_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	LogoUrl     pgtype.Text        `json:"logo_url"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type CatalogUnit struct {
	ID               int64              `json:"id"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
	Symbol           string             `json:"symbol"`
	UnitType         CatalogUnitType    `json:"unit_type"`
	BaseUnitID       pgtype.Int8        `json:"base_unit_id"`
	ConversionFactor pgtype.Numeric     `json:"conversion_factor"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type IdentityAddress struct {
	ID                   int64              `json:"id"`
	Code                 string             `json:"code"`
	OwnerUserID          int64              `json:"owner_user_id"`
	OwnerType            IdentityUserType   `json:"owner_type"`
	Label                string             `json:"label"`
	RecipientName        pgtype.Text        `json:"recipient_name"`
	CompanyName          pgtype.Text        `json:"company_name"`
	Line1                string             `json:"line1"`
	Line2                pgtype.Text        `json:"line2"`
	City                 string             `json:"city"`
	StateProvince        pgtype.Text        `json:"state_province"`
	PostalCode           string             `json:"postal_code"`
	Country              string             `json:"country"`
	Phone                pgtype.Text        `json:"phone"`
	IsDefault            bool               `json:"is_default"`
	HandlingClass        pgtype.Text        `json:"handling_class"`
	DeliveryInstructions pgtype.Text        `json:"delivery_instructions"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type IdentityBuyerProfile struct {
	ID                 int64              `json:"id"`
	UserID             int64              `json:"user_id"`
	Code               string             `json:"code"`
	BusinessName       string             `json:"business_name"`
	TradingName        pgtype.Text        `json:"trading_name"`
	TaxID              pgtype.Text        `json:"tax_id"`
	RegistrationNumber pgtype.Text        `json:"registration_number"`
	Phone              pgtype.Text        `json:"phone"`
	Website            pgtype.Text        `json:"website"`
	Industry           pgtype.Text        `json:"industry"`
	EmployeeCount      pgtype.Int4        `json:"employee_count"`
	AnnualRevenueMinor pgtype.Int8        `json:"annual_revenue_minor"`
	Currency           string             `json:"currency"`
	CreditLimitMinor   pgtype.Int8        `json:"credit_limit_minor"`
	CreditTermsDays    pgtype.Int4        `json:"credit_terms_days"`
	IsOnCreditHold     bool               `json:"is_on_credit_hold"`
	CreditHoldReason   pgtype.Text        `json:"credit_hold_reason"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type IdentityCreditAccount struct {
	ID                   int64              `json:"id"`
	Code                 string             `json:"code"`
	BuyerProfileID       int64              `json:"buyer_profile_id"`
	LimitMinor           int64              `json:"limit_minor"`
	Currency             string             `json:"currency"`
	TermsDays            int32              `json:"terms_days"`
	CurrentExposureMinor int64              `json:"current_exposure_minor"`
	AvailableMinor       pgtype.Int8        `json:"available_minor"`
	IsOnHold             bool               `json:"is_on_hold"`
	HoldReason           pgtype.Text        `json:"hold_reason"`
	HoldSince            pgtype.Timestamptz `json:"hold_since"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type IdentityOtpCode struct {
	ID          int64              `json:"id"`
	Code        string             `json:"code"`
	UserID      int64              `json:"user_id"`
	OtpHash     string             `json:"otp_hash"`
	Purpose     string             `json:"purpose"`
	ExpiresAt   time.Time          `json:"expires_at"`
	UsedAt      pgtype.Timestamptz `json:"used_at"`
	Attempts    int32              `json:"attempts"`
	MaxAttempts int32              `json:"max_attempts"`
	CreatedAt   time.Time          `json:"created_at"`
}

type IdentityPasswordResetToken struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type IdentityPermission struct {
	ID          int64              `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Resource    string             `json:"resource"`
	Action      string             `json:"action"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type IdentityPriceListAssignment struct {
	ID             int64              `json:"id"`
	Code           string             `json:"code"`
	BuyerProfileID int64              `json:"buyer_profile_id"`
	PriceListID    int64              `json:"price_list_id"`
	AssignedAt     time.Time          `json:"assigned_at"`
	AssignedBy     pgtype.Int8        `json:"assigned_by"`
	EffectiveFrom  pgtype.Date        `json:"effective_from"`
	EffectiveTo    pgtype.Date        `json:"effective_to"`
	CreatedAt      time.Time          `json:"created_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type IdentityPurchaseScope struct {
	ID             int64              `json:"id"`
	Code           string             `json:"code"`
	BuyerProfileID int64              `json:"buyer_profile_id"`
	HandlingClass  string             `json:"handling_class"`
	GrantedAt      time.Time          `json:"granted_at"`
	GrantedBy      pgtype.Int8        `json:"granted_by"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      time.Time          `json:"created_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type IdentityRefreshToken struct {
	ID            int64              `json:"id"`
	Code          string             `json:"code"`
	UserID        int64              `json:"user_id"`
	TokenHash     string             `json:"token_hash"`
	FamilyID      string             `json:"family_id"`
	ExpiresAt     time.Time          `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
	CreatedAt     time.Time          `json:"created_at"`
	ReplacedByID  pgtype.Int8        `json:"replaced_by_id"`
}

type IdentityRole struct {
	ID          int64              `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type IdentityRolePermission struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

type IdentitySession struct {
	ID             int64              `json:"id"`
	Code           string             `json:"code"`
	UserID         int64              `json:"user_id"`
	RefreshTokenID pgtype.Int8        `json:"refresh_token_id"`
	IpAddress      *netip.Addr        `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	ExpiresAt      time.Time          `json:"expires_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt      time.Time          `json:"created_at"`
}

type IdentitySupplierProfile struct {
	ID                 int64              `json:"id"`
	UserID             int64              `json:"user_id"`
	Code               string             `json:"code"`
	CompanyName        string             `json:"company_name"`
	TradingName        pgtype.Text        `json:"trading_name"`
	TaxID              pgtype.Text        `json:"tax_id"`
	RegistrationNumber pgtype.Text        `json:"registration_number"`
	Phone              pgtype.Text        `json:"phone"`
	Email              pgtype.Text        `json:"email"`
	Website            pgtype.Text        `json:"website"`
	AddressLine1       pgtype.Text        `json:"address_line1"`
	AddressLine2       pgtype.Text        `json:"address_line2"`
	City               pgtype.Text        `json:"city"`
	StateProvince      pgtype.Text        `json:"state_province"`
	PostalCode         pgtype.Text        `json:"postal_code"`
	Country            string             `json:"country"`
	ContactPerson      pgtype.Text        `json:"contact_person"`
	ContactPhone       pgtype.Text        `json:"contact_phone"`
	ContactEmail       pgtype.Text        `json:"contact_email"`
	IsApproved         bool               `json:"is_approved"`
	ApprovedAt         pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy         pgtype.Int8        `json:"approved_by"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type IdentityUser struct {
	ID                  int64              `json:"id"`
	Code                string             `json:"code"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	UserType            IdentityUserType   `json:"user_type"`
	IsActive            bool               `json:"is_active"`
	IsVerified          bool               `json:"is_verified"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type IdentityUserRole struct {
	UserID     int64       `json:"user_id"`
	RoleID     int64       `json:"role_id"`
	AssignedAt time.Time   `json:"assigned_at"`
	AssignedBy pgtype.Int8 `json:"assigned_by"`
}

type IdentityVerificationApplication struct {
	ID                    int64                      `json:"id"`
	Code                  string                     `json:"code"`
	BuyerProfileID        int64                      `json:"buyer_profile_id"`
	Status                IdentityVerificationStatus `json:"status"`
	SubmittedAt           time.Time                  `json:"submitted_at"`
	DecidedAt             pgtype.Timestamptz         `json:"decided_at"`
	DecidedBy             pgtype.Int8                `json:"decided_by"`
	DecisionReason        pgtype.Text                `json:"decision_reason"`
	RejectionReason       pgtype.Text                `json:"rejection_reason"`
	LicenceNumber         pgtype.Text                `json:"licence_number"`
	LicenceExpiry         pgtype.Date                `json:"licence_expiry"`
	TradingName           pgtype.Text                `json:"trading_name"`
	BusinessAddressLine1  pgtype.Text                `json:"business_address_line1"`
	BusinessAddressLine2  pgtype.Text                `json:"business_address_line2"`
	BusinessCity          pgtype.Text                `json:"business_city"`
	BusinessStateProvince pgtype.Text                `json:"business_state_province"`
	BusinessPostalCode    pgtype.Text                `json:"business_postal_code"`
	BusinessCountry       string                     `json:"business_country"`
	CreatedAt             time.Time                  `json:"created_at"`
	UpdatedAt             time.Time                  `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz         `json:"deleted_at"`
}

type IdentityVerificationDocument struct {
	ID                        int64              `json:"id"`
	Code                      string             `json:"code"`
	VerificationApplicationID int64              `json:"verification_application_id"`
	DocumentType              string             `json:"document_type"`
	FileName                  string             `json:"file_name"`
	FilePath                  string             `json:"file_path"`
	FileSize                  int64              `json:"file_size"`
	MimeType                  string             `json:"mime_type"`
	UploadedAt                time.Time          `json:"uploaded_at"`
	UploadedBy                pgtype.Int8        `json:"uploaded_by"`
	CreatedAt                 time.Time          `json:"created_at"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
}

type PlatformHealthCheck struct {
	ID        int64     `json:"id"`
	CheckedAt time.Time `json:"checked_at"`
	Status    string    `json:"status"`
}

type PricingPriceList struct {
	ID            int64                  `json:"id"`
	Code          string                 `json:"code"`
	Name          string                 `json:"name"`
	Description   pgtype.Text            `json:"description"`
	Status        PricingPriceListStatus `json:"status"`
	PriceType     PricingPriceType       `json:"price_type"`
	Currency      string                 `json:"currency"`
	EffectiveFrom time.Time              `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz     `json:"effective_to"`
	IsActive      bool                   `json:"is_active"`
	CreatedAt     time.Time              `json:"created_at"`
	UpdatedAt     time.Time              `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz     `json:"deleted_at"`
}

type PricingPriceListAssignment struct {
	ID             int64              `json:"id"`
	Code           string             `json:"code"`
	PriceListID    int64              `json:"price_list_id"`
	BuyerProfileID int64              `json:"buyer_profile_id"`
	AssignedBy     pgtype.Int8        `json:"assigned_by"`
	EffectiveFrom  time.Time          `json:"effective_from"`
	EffectiveTo    pgtype.Timestamptz `json:"effective_to"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type PricingPriceListItem struct {
	ID            int64              `json:"id"`
	PriceListID   int64              `json:"price_list_id"`
	ProductID     int64              `json:"product_id"`
	UnitID        int64              `json:"unit_id"`
	Currency      string             `json:"currency"`
	PriceMinor    int64              `json:"price_minor"`
	MinQuantity   int32              `json:"min_quantity"`
	MaxQuantity   pgtype.Int4        `json:"max_quantity"`
	EffectiveFrom time.Time          `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `json:"effective_to"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type PricingQuantityTier struct {
	ID              int64              `json:"id"`
	PriceListItemID int64              `json:"price_list_item_id"`
	MinQuantity     int32              `json:"min_quantity"`
	MaxQuantity     pgtype.Int4        `json:"max_quantity"`
	PriceMinor      int64              `json:"price_minor"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
