// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"
)

type Querier interface {
	GetHealthCheckRecords(ctx context.Context, limit int32) ([]PlatformHealthCheck, error)
	// Health check queries for database connectivity verification
	HealthCheck(ctx context.Context) (int32, error)
	HealthCheckWithTimestamp(ctx context.Context) (HealthCheckWithTimestampRow, error)
	InsertHealthCheck(ctx context.Context, status string) (PlatformHealthCheck, error)
}

var _ Querier = (*Queries)(nil)
