// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identity

import (
	"context"
)

type Querier interface {
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	CleanupExpiredOTPCodes(ctx context.Context) error
	CleanupExpiredPasswordResetTokens(ctx context.Context) error
	CleanupExpiredRefreshTokens(ctx context.Context) error
	CleanupExpiredSessions(ctx context.Context) error
	CountUsers(ctx context.Context) (int64, error)
	CountVerificationApplications(ctx context.Context, dollar_1 IdentityVerificationStatus) (int64, error)
	// Addresses
	CreateAddress(ctx context.Context, arg CreateAddressParams) (CreateAddressRow, error)
	// Buyer Profiles
	CreateBuyerProfile(ctx context.Context, arg CreateBuyerProfileParams) (CreateBuyerProfileRow, error)
	// Credit Accounts
	CreateCreditAccount(ctx context.Context, arg CreateCreditAccountParams) (CreateCreditAccountRow, error)
	// OTP Codes
	CreateOTPCode(ctx context.Context, arg CreateOTPCodeParams) (CreateOTPCodeRow, error)
	// Password Reset Tokens
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (CreatePasswordResetTokenRow, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (CreatePermissionRow, error)
	// Price List Assignments
	CreatePriceListAssignment(ctx context.Context, arg CreatePriceListAssignmentParams) (CreatePriceListAssignmentRow, error)
	// Purchase Scopes
	CreatePurchaseScope(ctx context.Context, arg CreatePurchaseScopeParams) (CreatePurchaseScopeRow, error)
	// Refresh Tokens
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error)
	// Roles and Permissions
	CreateRole(ctx context.Context, arg CreateRoleParams) (CreateRoleRow, error)
	// Sessions
	CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error)
	// Supplier Profiles
	CreateSupplierProfile(ctx context.Context, arg CreateSupplierProfileParams) (CreateSupplierProfileRow, error)
	// Identity module queries
	// User management
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Verification Applications
	CreateVerificationApplication(ctx context.Context, arg CreateVerificationApplicationParams) (CreateVerificationApplicationRow, error)
	// Verification Documents
	CreateVerificationDocument(ctx context.Context, arg CreateVerificationDocumentParams) (CreateVerificationDocumentRow, error)
	DeletePurchaseScope(ctx context.Context, id int64) error
	GetAddressByCode(ctx context.Context, code string) (IdentityAddress, error)
	GetAddressesByOwner(ctx context.Context, arg GetAddressesByOwnerParams) ([]GetAddressesByOwnerRow, error)
	GetBuyerProfileByCode(ctx context.Context, code string) (GetBuyerProfileByCodeRow, error)
	GetBuyerProfileByUserID(ctx context.Context, userID int64) (GetBuyerProfileByUserIDRow, error)
	GetCreditAccountByBuyer(ctx context.Context, buyerProfileID int64) (IdentityCreditAccount, error)
	GetOTPCode(ctx context.Context, arg GetOTPCodeParams) (IdentityOtpCode, error)
	GetPasswordResetToken(ctx context.Context, tokenHash string) (IdentityPasswordResetToken, error)
	GetPermissionByCode(ctx context.Context, code string) (GetPermissionByCodeRow, error)
	GetPriceListAssignmentsByBuyer(ctx context.Context, buyerProfileID int64) ([]GetPriceListAssignmentsByBuyerRow, error)
	GetPurchaseScopesByBuyer(ctx context.Context, buyerProfileID int64) ([]GetPurchaseScopesByBuyerRow, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (IdentityRefreshToken, error)
	GetRoleByCode(ctx context.Context, code string) (GetRoleByCodeRow, error)
	GetSessionByCode(ctx context.Context, code string) (IdentitySession, error)
	GetSupplierProfileByCode(ctx context.Context, code string) (GetSupplierProfileByCodeRow, error)
	GetSupplierProfileByUserID(ctx context.Context, userID int64) (GetSupplierProfileByUserIDRow, error)
	GetUserByCode(ctx context.Context, code string) (IdentityUser, error)
	GetUserByEmail(ctx context.Context, email string) (IdentityUser, error)
	GetUserByID(ctx context.Context, id int64) (IdentityUser, error)
	GetUserPermissions(ctx context.Context, userID int64) ([]GetUserPermissionsRow, error)
	GetUserRoles(ctx context.Context, userID int64) ([]GetUserRolesRow, error)
	GetVerificationApplicationByBuyer(ctx context.Context, buyerProfileID int64) (GetVerificationApplicationByBuyerRow, error)
	GetVerificationApplicationByID(ctx context.Context, id int64) (IdentityVerificationApplication, error)
	GetVerificationDocuments(ctx context.Context, verificationApplicationID int64) ([]GetVerificationDocumentsRow, error)
	IncrementOTPAttempts(ctx context.Context, id int64) error
	ListPermissions(ctx context.Context) ([]ListPermissionsRow, error)
	ListRoles(ctx context.Context) ([]ListRolesRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ListVerificationApplications(ctx context.Context, arg ListVerificationApplicationsParams) ([]ListVerificationApplicationsRow, error)
	RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error
	ReplaceRefreshToken(ctx context.Context, arg ReplaceRefreshTokenParams) (ReplaceRefreshTokenRow, error)
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	RevokeRefreshTokenFamily(ctx context.Context, arg RevokeRefreshTokenFamilyParams) error
	RevokeSession(ctx context.Context, id int64) error
	RevokeUserSessions(ctx context.Context, userID int64) error
	SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) error
	SoftDeleteAddress(ctx context.Context, id int64) error
	SoftDeleteBuyerProfile(ctx context.Context, id int64) error
	SoftDeleteUser(ctx context.Context, id int64) error
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (UpdateAddressRow, error)
	UpdateBuyerProfile(ctx context.Context, arg UpdateBuyerProfileParams) (UpdateBuyerProfileRow, error)
	UpdateCreditAccountExposure(ctx context.Context, arg UpdateCreditAccountExposureParams) error
	UpdateCreditAccountHold(ctx context.Context, arg UpdateCreditAccountHoldParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpdateUserLastLogin(ctx context.Context, id int64) error
	UpdateUserLoginAttempts(ctx context.Context, arg UpdateUserLoginAttemptsParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateVerificationApplicationStatus(ctx context.Context, arg UpdateVerificationApplicationStatusParams) (UpdateVerificationApplicationStatusRow, error)
	UseOTPCode(ctx context.Context, id int64) error
	UsePasswordResetToken(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
