// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package identity

import (
	"context"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignPermissionToRole = `-- name: AssignPermissionToRole :exec
INSERT INTO identity.role_permission (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT (role_id, permission_id) DO NOTHING
`

type AssignPermissionToRoleParams struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

func (q *Queries) AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, assignPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO identity.user_role (user_id, role_id, assigned_by)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type AssignRoleToUserParams struct {
	UserID     int64       `json:"user_id"`
	RoleID     int64       `json:"role_id"`
	AssignedBy pgtype.Int8 `json:"assigned_by"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.UserID, arg.RoleID, arg.AssignedBy)
	return err
}

const cleanupExpiredOTPCodes = `-- name: CleanupExpiredOTPCodes :exec
DELETE FROM identity.otp_code
WHERE expires_at < NOW() OR used_at IS NOT NULL
`

func (q *Queries) CleanupExpiredOTPCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredOTPCodes)
	return err
}

const cleanupExpiredPasswordResetTokens = `-- name: CleanupExpiredPasswordResetTokens :exec
DELETE FROM identity.password_reset_token
WHERE expires_at < NOW() OR used_at IS NOT NULL
`

func (q *Queries) CleanupExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredPasswordResetTokens)
	return err
}

const cleanupExpiredRefreshTokens = `-- name: CleanupExpiredRefreshTokens :exec
DELETE FROM identity.refresh_token
WHERE expires_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) CleanupExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredRefreshTokens)
	return err
}

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
DELETE FROM identity.session
WHERE expires_at < NOW() - INTERVAL '7 days'
`

func (q *Queries) CleanupExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredSessions)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM identity.user WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVerificationApplications = `-- name: CountVerificationApplications :one
SELECT COUNT(*) FROM identity.verification_application
WHERE deleted_at IS NULL
  AND ($1::identity.verification_status IS NULL OR status = $1)
`

func (q *Queries) CountVerificationApplications(ctx context.Context, dollar_1 IdentityVerificationStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countVerificationApplications, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAddress = `-- name: CreateAddress :one

INSERT INTO identity.address (
    code, owner_user_id, owner_type, label,
    recipient_name, company_name, line1, line2,
    city, state_province, postal_code, country,
    phone, is_default, handling_class, delivery_instructions
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, code, owner_user_id, owner_type, label, created_at, updated_at
`

type CreateAddressParams struct {
	Code                 string           `json:"code"`
	OwnerUserID          int64            `json:"owner_user_id"`
	OwnerType            IdentityUserType `json:"owner_type"`
	Label                string           `json:"label"`
	RecipientName        pgtype.Text      `json:"recipient_name"`
	CompanyName          pgtype.Text      `json:"company_name"`
	Line1                string           `json:"line1"`
	Line2                pgtype.Text      `json:"line2"`
	City                 string           `json:"city"`
	StateProvince        pgtype.Text      `json:"state_province"`
	PostalCode           string           `json:"postal_code"`
	Country              string           `json:"country"`
	Phone                pgtype.Text      `json:"phone"`
	IsDefault            bool             `json:"is_default"`
	HandlingClass        pgtype.Text      `json:"handling_class"`
	DeliveryInstructions pgtype.Text      `json:"delivery_instructions"`
}

type CreateAddressRow struct {
	ID          int64            `json:"id"`
	Code        string           `json:"code"`
	OwnerUserID int64            `json:"owner_user_id"`
	OwnerType   IdentityUserType `json:"owner_type"`
	Label       string           `json:"label"`
	CreatedAt   time.Time        `json:"created_at"`
	UpdatedAt   time.Time        `json:"updated_at"`
}

// Addresses
func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (CreateAddressRow, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.Code,
		arg.OwnerUserID,
		arg.OwnerType,
		arg.Label,
		arg.RecipientName,
		arg.CompanyName,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.StateProvince,
		arg.PostalCode,
		arg.Country,
		arg.Phone,
		arg.IsDefault,
		arg.HandlingClass,
		arg.DeliveryInstructions,
	)
	var i CreateAddressRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OwnerUserID,
		&i.OwnerType,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBuyerProfile = `-- name: CreateBuyerProfile :one

INSERT INTO identity.buyer_profile (
    code, user_id, business_name, trading_name, tax_id,
    registration_number, phone, website, industry,
    employee_count, annual_revenue_minor, currency
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, code, user_id, business_name, created_at, updated_at
`

type CreateBuyerProfileParams struct {
	Code               string      `json:"code"`
	UserID             int64       `json:"user_id"`
	BusinessName       string      `json:"business_name"`
	TradingName        pgtype.Text `json:"trading_name"`
	TaxID              pgtype.Text `json:"tax_id"`
	RegistrationNumber pgtype.Text `json:"registration_number"`
	Phone              pgtype.Text `json:"phone"`
	Website            pgtype.Text `json:"website"`
	Industry           pgtype.Text `json:"industry"`
	EmployeeCount      pgtype.Int4 `json:"employee_count"`
	AnnualRevenueMinor pgtype.Int8 `json:"annual_revenue_minor"`
	Currency           string      `json:"currency"`
}

type CreateBuyerProfileRow struct {
	ID           int64     `json:"id"`
	Code         string    `json:"code"`
	UserID       int64     `json:"user_id"`
	BusinessName string    `json:"business_name"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// Buyer Profiles
func (q *Queries) CreateBuyerProfile(ctx context.Context, arg CreateBuyerProfileParams) (CreateBuyerProfileRow, error) {
	row := q.db.QueryRow(ctx, createBuyerProfile,
		arg.Code,
		arg.UserID,
		arg.BusinessName,
		arg.TradingName,
		arg.TaxID,
		arg.RegistrationNumber,
		arg.Phone,
		arg.Website,
		arg.Industry,
		arg.EmployeeCount,
		arg.AnnualRevenueMinor,
		arg.Currency,
	)
	var i CreateBuyerProfileRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.BusinessName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCreditAccount = `-- name: CreateCreditAccount :one

INSERT INTO identity.credit_account (
    code, buyer_profile_id, limit_minor, currency, terms_days
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, code, buyer_profile_id, limit_minor, currency, terms_days, created_at
`

type CreateCreditAccountParams struct {
	Code           string `json:"code"`
	BuyerProfileID int64  `json:"buyer_profile_id"`
	LimitMinor     int64  `json:"limit_minor"`
	Currency       string `json:"currency"`
	TermsDays      int32  `json:"terms_days"`
}

type CreateCreditAccountRow struct {
	ID             int64     `json:"id"`
	Code           string    `json:"code"`
	BuyerProfileID int64     `json:"buyer_profile_id"`
	LimitMinor     int64     `json:"limit_minor"`
	Currency       string    `json:"currency"`
	TermsDays      int32     `json:"terms_days"`
	CreatedAt      time.Time `json:"created_at"`
}

// Credit Accounts
func (q *Queries) CreateCreditAccount(ctx context.Context, arg CreateCreditAccountParams) (CreateCreditAccountRow, error) {
	row := q.db.QueryRow(ctx, createCreditAccount,
		arg.Code,
		arg.BuyerProfileID,
		arg.LimitMinor,
		arg.Currency,
		arg.TermsDays,
	)
	var i CreateCreditAccountRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.BuyerProfileID,
		&i.LimitMinor,
		&i.Currency,
		&i.TermsDays,
		&i.CreatedAt,
	)
	return i, err
}

const createOTPCode = `-- name: CreateOTPCode :one

INSERT INTO identity.otp_code (code, user_id, otp_hash, purpose, expires_at, max_attempts)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, user_id, purpose, expires_at, created_at
`

type CreateOTPCodeParams struct {
	Code        string    `json:"code"`
	UserID      int64     `json:"user_id"`
	OtpHash     string    `json:"otp_hash"`
	Purpose     string    `json:"purpose"`
	ExpiresAt   time.Time `json:"expires_at"`
	MaxAttempts int32     `json:"max_attempts"`
}

type CreateOTPCodeRow struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	UserID    int64     `json:"user_id"`
	Purpose   string    `json:"purpose"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

// OTP Codes
func (q *Queries) CreateOTPCode(ctx context.Context, arg CreateOTPCodeParams) (CreateOTPCodeRow, error) {
	row := q.db.QueryRow(ctx, createOTPCode,
		arg.Code,
		arg.UserID,
		arg.OtpHash,
		arg.Purpose,
		arg.ExpiresAt,
		arg.MaxAttempts,
	)
	var i CreateOTPCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.Purpose,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one

INSERT INTO identity.password_reset_token (code, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, code, user_id, expires_at, created_at
`

type CreatePasswordResetTokenParams struct {
	Code      string    `json:"code"`
	UserID    int64     `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

type CreatePasswordResetTokenRow struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

// Password Reset Tokens
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (CreatePasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken,
		arg.Code,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i CreatePasswordResetTokenRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO identity.permission (code, name, description, resource, action)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, name, description, resource, action, created_at
`

type CreatePermissionParams struct {
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Resource    string      `json:"resource"`
	Action      string      `json:"action"`
}

type CreatePermissionRow struct {
	ID          int64       `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Resource    string      `json:"resource"`
	Action      string      `json:"action"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (CreatePermissionRow, error) {
	row := q.db.QueryRow(ctx, createPermission,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Resource,
		arg.Action,
	)
	var i CreatePermissionRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Resource,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}

const createPriceListAssignment = `-- name: CreatePriceListAssignment :one

INSERT INTO identity.price_list_assignment (
    code, buyer_profile_id, price_list_id, assigned_by,
    effective_from, effective_to
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, code, buyer_profile_id, price_list_id, effective_from, effective_to
`

type CreatePriceListAssignmentParams struct {
	Code           string      `json:"code"`
	BuyerProfileID int64       `json:"buyer_profile_id"`
	PriceListID    int64       `json:"price_list_id"`
	AssignedBy     pgtype.Int8 `json:"assigned_by"`
	EffectiveFrom  pgtype.Date `json:"effective_from"`
	EffectiveTo    pgtype.Date `json:"effective_to"`
}

type CreatePriceListAssignmentRow struct {
	ID             int64       `json:"id"`
	Code           string      `json:"code"`
	BuyerProfileID int64       `json:"buyer_profile_id"`
	PriceListID    int64       `json:"price_list_id"`
	EffectiveFrom  pgtype.Date `json:"effective_from"`
	EffectiveTo    pgtype.Date `json:"effective_to"`
}

// Price List Assignments
func (q *Queries) CreatePriceListAssignment(ctx context.Context, arg CreatePriceListAssignmentParams) (CreatePriceListAssignmentRow, error) {
	row := q.db.QueryRow(ctx, createPriceListAssignment,
		arg.Code,
		arg.BuyerProfileID,
		arg.PriceListID,
		arg.AssignedBy,
		arg.EffectiveFrom,
		arg.EffectiveTo,
	)
	var i CreatePriceListAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.BuyerProfileID,
		&i.PriceListID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
	)
	return i, err
}

const createPurchaseScope = `-- name: CreatePurchaseScope :one

INSERT INTO identity.purchase_scope (
    code, buyer_profile_id, handling_class, granted_by, expires_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, code, buyer_profile_id, handling_class, granted_at, expires_at
`

type CreatePurchaseScopeParams struct {
	Code           string             `json:"code"`
	BuyerProfileID int64              `json:"buyer_profile_id"`
	HandlingClass  string             `json:"handling_class"`
	GrantedBy      pgtype.Int8        `json:"granted_by"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type CreatePurchaseScopeRow struct {
	ID             int64              `json:"id"`
	Code           string             `json:"code"`
	BuyerProfileID int64              `json:"buyer_profile_id"`
	HandlingClass  string             `json:"handling_class"`
	GrantedAt      time.Time          `json:"granted_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

// Purchase Scopes
func (q *Queries) CreatePurchaseScope(ctx context.Context, arg CreatePurchaseScopeParams) (CreatePurchaseScopeRow, error) {
	row := q.db.QueryRow(ctx, createPurchaseScope,
		arg.Code,
		arg.BuyerProfileID,
		arg.HandlingClass,
		arg.GrantedBy,
		arg.ExpiresAt,
	)
	var i CreatePurchaseScopeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.BuyerProfileID,
		&i.HandlingClass,
		&i.GrantedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one

INSERT INTO identity.refresh_token (
    code, user_id, token_hash, family_id, expires_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, code, user_id, family_id, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	Code      string    `json:"code"`
	UserID    int64     `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	FamilyID  string    `json:"family_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

type CreateRefreshTokenRow struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	UserID    int64     `json:"user_id"`
	FamilyID  string    `json:"family_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

// Refresh Tokens
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.Code,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.ExpiresAt,
	)
	var i CreateRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one

INSERT INTO identity.role (code, name, description, is_system)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, description, is_system, created_at
`

type CreateRoleParams struct {
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsSystem    bool        `json:"is_system"`
}

type CreateRoleRow struct {
	ID          int64       `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsSystem    bool        `json:"is_system"`
	CreatedAt   time.Time   `json:"created_at"`
}

// Roles and Permissions
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (CreateRoleRow, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.IsSystem,
	)
	var i CreateRoleRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO identity.session (code, user_id, refresh_token_id, ip_address, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	Code           string      `json:"code"`
	UserID         int64       `json:"user_id"`
	RefreshTokenID pgtype.Int8 `json:"refresh_token_id"`
	IpAddress      *netip.Addr `json:"ip_address"`
	UserAgent      pgtype.Text `json:"user_agent"`
	ExpiresAt      time.Time   `json:"expires_at"`
}

type CreateSessionRow struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

// Sessions
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.Code,
		arg.UserID,
		arg.RefreshTokenID,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSupplierProfile = `-- name: CreateSupplierProfile :one

INSERT INTO identity.supplier_profile (
    code, user_id, company_name, trading_name, tax_id,
    registration_number, phone, email, website,
    address_line1, address_line2, city, state_province,
    postal_code, country, contact_person, contact_phone, contact_email
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
) RETURNING id, code, user_id, company_name, created_at, updated_at
`

type CreateSupplierProfileParams struct {
	Code               string      `json:"code"`
	UserID             int64       `json:"user_id"`
	CompanyName        string      `json:"company_name"`
	TradingName        pgtype.Text `json:"trading_name"`
	TaxID              pgtype.Text `json:"tax_id"`
	RegistrationNumber pgtype.Text `json:"registration_number"`
	Phone              pgtype.Text `json:"phone"`
	Email              pgtype.Text `json:"email"`
	Website            pgtype.Text `json:"website"`
	AddressLine1       pgtype.Text `json:"address_line1"`
	AddressLine2       pgtype.Text `json:"address_line2"`
	City               pgtype.Text `json:"city"`
	StateProvince      pgtype.Text `json:"state_province"`
	PostalCode         pgtype.Text `json:"postal_code"`
	Country            string      `json:"country"`
	ContactPerson      pgtype.Text `json:"contact_person"`
	ContactPhone       pgtype.Text `json:"contact_phone"`
	ContactEmail       pgtype.Text `json:"contact_email"`
}

type CreateSupplierProfileRow struct {
	ID          int64     `json:"id"`
	Code        string    `json:"code"`
	UserID      int64     `json:"user_id"`
	CompanyName string    `json:"company_name"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Supplier Profiles
func (q *Queries) CreateSupplierProfile(ctx context.Context, arg CreateSupplierProfileParams) (CreateSupplierProfileRow, error) {
	row := q.db.QueryRow(ctx, createSupplierProfile,
		arg.Code,
		arg.UserID,
		arg.CompanyName,
		arg.TradingName,
		arg.TaxID,
		arg.RegistrationNumber,
		arg.Phone,
		arg.Email,
		arg.Website,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.StateProvince,
		arg.PostalCode,
		arg.Country,
		arg.ContactPerson,
		arg.ContactPhone,
		arg.ContactEmail,
	)
	var i CreateSupplierProfileRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.CompanyName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO identity.user (
    code, email, password_hash, user_type
) VALUES (
    $1, $2, $3, $4
) RETURNING id, code, email, user_type, is_active, is_verified, created_at, updated_at
`

type CreateUserParams struct {
	Code         string           `json:"code"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	UserType     IdentityUserType `json:"user_type"`
}

type CreateUserRow struct {
	ID         int64            `json:"id"`
	Code       string           `json:"code"`
	Email      string           `json:"email"`
	UserType   IdentityUserType `json:"user_type"`
	IsActive   bool             `json:"is_active"`
	IsVerified bool             `json:"is_verified"`
	CreatedAt  time.Time        `json:"created_at"`
	UpdatedAt  time.Time        `json:"updated_at"`
}

// Identity module queries
// User management
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Code,
		arg.Email,
		arg.PasswordHash,
		arg.UserType,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.UserType,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVerificationApplication = `-- name: CreateVerificationApplication :one

INSERT INTO identity.verification_application (
    code, buyer_profile_id, licence_number, licence_expiry,
    trading_name, business_address_line1, business_address_line2,
    business_city, business_state_province, business_postal_code, business_country
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, code, buyer_profile_id, status, created_at, updated_at
`

type CreateVerificationApplicationParams struct {
	Code                  string      `json:"code"`
	BuyerProfileID        int64       `json:"buyer_profile_id"`
	LicenceNumber         pgtype.Text `json:"licence_number"`
	LicenceExpiry         pgtype.Date `json:"licence_expiry"`
	TradingName           pgtype.Text `json:"trading_name"`
	BusinessAddressLine1  pgtype.Text `json:"business_address_line1"`
	BusinessAddressLine2  pgtype.Text `json:"business_address_line2"`
	BusinessCity          pgtype.Text `json:"business_city"`
	BusinessStateProvince pgtype.Text `json:"business_state_province"`
	BusinessPostalCode    pgtype.Text `json:"business_postal_code"`
	BusinessCountry       string      `json:"business_country"`
}

type CreateVerificationApplicationRow struct {
	ID             int64                      `json:"id"`
	Code           string                     `json:"code"`
	BuyerProfileID int64                      `json:"buyer_profile_id"`
	Status         IdentityVerificationStatus `json:"status"`
	CreatedAt      time.Time                  `json:"created_at"`
	UpdatedAt      time.Time                  `json:"updated_at"`
}

// Verification Applications
func (q *Queries) CreateVerificationApplication(ctx context.Context, arg CreateVerificationApplicationParams) (CreateVerificationApplicationRow, error) {
	row := q.db.QueryRow(ctx, createVerificationApplication,
		arg.Code,
		arg.BuyerProfileID,
		arg.LicenceNumber,
		arg.LicenceExpiry,
		arg.TradingName,
		arg.BusinessAddressLine1,
		arg.BusinessAddressLine2,
		arg.BusinessCity,
		arg.BusinessStateProvince,
		arg.BusinessPostalCode,
		arg.BusinessCountry,
	)
	var i CreateVerificationApplicationRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.BuyerProfileID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVerificationDocument = `-- name: CreateVerificationDocument :one

INSERT INTO identity.verification_document (
    code, verification_application_id, document_type,
    file_name, file_path, file_size, mime_type, uploaded_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, code, verification_application_id, created_at
`

type CreateVerificationDocumentParams struct {
	Code                      string      `json:"code"`
	VerificationApplicationID int64       `json:"verification_application_id"`
	DocumentType              string      `json:"document_type"`
	FileName                  string      `json:"file_name"`
	FilePath                  string      `json:"file_path"`
	FileSize                  int64       `json:"file_size"`
	MimeType                  string      `json:"mime_type"`
	UploadedBy                pgtype.Int8 `json:"uploaded_by"`
}

type CreateVerificationDocumentRow struct {
	ID                        int64     `json:"id"`
	Code                      string    `json:"code"`
	VerificationApplicationID int64     `json:"verification_application_id"`
	CreatedAt                 time.Time `json:"created_at"`
}

// Verification Documents
func (q *Queries) CreateVerificationDocument(ctx context.Context, arg CreateVerificationDocumentParams) (CreateVerificationDocumentRow, error) {
	row := q.db.QueryRow(ctx, createVerificationDocument,
		arg.Code,
		arg.VerificationApplicationID,
		arg.DocumentType,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
		arg.MimeType,
		arg.UploadedBy,
	)
	var i CreateVerificationDocumentRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.VerificationApplicationID,
		&i.CreatedAt,
	)
	return i, err
}

const deletePurchaseScope = `-- name: DeletePurchaseScope :exec
UPDATE identity.purchase_scope
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeletePurchaseScope(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePurchaseScope, id)
	return err
}

const getAddressByCode = `-- name: GetAddressByCode :one
SELECT id, code, owner_user_id, owner_type, label,
       recipient_name, company_name, line1, line2,
       city, state_province, postal_code, country,
       phone, is_default, handling_class, delivery_instructions,
       created_at, updated_at, deleted_at
FROM identity.address
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAddressByCode(ctx context.Context, code string) (IdentityAddress, error) {
	row := q.db.QueryRow(ctx, getAddressByCode, code)
	var i IdentityAddress
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OwnerUserID,
		&i.OwnerType,
		&i.Label,
		&i.RecipientName,
		&i.CompanyName,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.StateProvince,
		&i.PostalCode,
		&i.Country,
		&i.Phone,
		&i.IsDefault,
		&i.HandlingClass,
		&i.DeliveryInstructions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAddressesByOwner = `-- name: GetAddressesByOwner :many
SELECT id, code, owner_user_id, owner_type, label,
       recipient_name, company_name, line1, line2,
       city, state_province, postal_code, country,
       phone, is_default, handling_class, delivery_instructions,
       created_at, updated_at
FROM identity.address
WHERE owner_user_id = $1 AND owner_type = $2 AND deleted_at IS NULL
ORDER BY is_default DESC, created_at ASC
`

type GetAddressesByOwnerParams struct {
	OwnerUserID int64            `json:"owner_user_id"`
	OwnerType   IdentityUserType `json:"owner_type"`
}

type GetAddressesByOwnerRow struct {
	ID                   int64            `json:"id"`
	Code                 string           `json:"code"`
	OwnerUserID          int64            `json:"owner_user_id"`
	OwnerType            IdentityUserType `json:"owner_type"`
	Label                string           `json:"label"`
	RecipientName        pgtype.Text      `json:"recipient_name"`
	CompanyName          pgtype.Text      `json:"company_name"`
	Line1                string           `json:"line1"`
	Line2                pgtype.Text      `json:"line2"`
	City                 string           `json:"city"`
	StateProvince        pgtype.Text      `json:"state_province"`
	PostalCode           string           `json:"postal_code"`
	Country              string           `json:"country"`
	Phone                pgtype.Text      `json:"phone"`
	IsDefault            bool             `json:"is_default"`
	HandlingClass        pgtype.Text      `json:"handling_class"`
	DeliveryInstructions pgtype.Text      `json:"delivery_instructions"`
	CreatedAt            time.Time        `json:"created_at"`
	UpdatedAt            time.Time        `json:"updated_at"`
}

func (q *Queries) GetAddressesByOwner(ctx context.Context, arg GetAddressesByOwnerParams) ([]GetAddressesByOwnerRow, error) {
	rows, err := q.db.Query(ctx, getAddressesByOwner, arg.OwnerUserID, arg.OwnerType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAddressesByOwnerRow{}
	for rows.Next() {
		var i GetAddressesByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.OwnerUserID,
			&i.OwnerType,
			&i.Label,
			&i.RecipientName,
			&i.CompanyName,
			&i.Line1,
			&i.Line2,
			&i.City,
			&i.StateProvince,
			&i.PostalCode,
			&i.Country,
			&i.Phone,
			&i.IsDefault,
			&i.HandlingClass,
			&i.DeliveryInstructions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBuyerProfileByCode = `-- name: GetBuyerProfileByCode :one
SELECT id, code, user_id, business_name, trading_name, tax_id,
       registration_number, phone, website, industry,
       employee_count, annual_revenue_minor, currency,
       credit_limit_minor, credit_terms_days, is_on_credit_hold,
       credit_hold_reason, created_at, updated_at, deleted_at
FROM identity.buyer_profile
WHERE code = $1 AND deleted_at IS NULL
`

type GetBuyerProfileByCodeRow struct {
	ID                 int64              `json:"id"`
	Code               string             `json:"code"`
	UserID             int64              `json:"user_id"`
	BusinessName       string             `json:"business_name"`
	TradingName        pgtype.Text        `json:"trading_name"`
	TaxID              pgtype.Text        `json:"tax_id"`
	RegistrationNumber pgtype.Text        `json:"registration_number"`
	Phone              pgtype.Text        `json:"phone"`
	Website            pgtype.Text        `json:"website"`
	Industry           pgtype.Text        `json:"industry"`
	EmployeeCount      pgtype.Int4        `json:"employee_count"`
	AnnualRevenueMinor pgtype.Int8        `json:"annual_revenue_minor"`
	Currency           string             `json:"currency"`
	CreditLimitMinor   pgtype.Int8        `json:"credit_limit_minor"`
	CreditTermsDays    pgtype.Int4        `json:"credit_terms_days"`
	IsOnCreditHold     bool               `json:"is_on_credit_hold"`
	CreditHoldReason   pgtype.Text        `json:"credit_hold_reason"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetBuyerProfileByCode(ctx context.Context, code string) (GetBuyerProfileByCodeRow, error) {
	row := q.db.QueryRow(ctx, getBuyerProfileByCode, code)
	var i GetBuyerProfileByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.BusinessName,
		&i.TradingName,
		&i.TaxID,
		&i.RegistrationNumber,
		&i.Phone,
		&i.Website,
		&i.Industry,
		&i.EmployeeCount,
		&i.AnnualRevenueMinor,
		&i.Currency,
		&i.CreditLimitMinor,
		&i.CreditTermsDays,
		&i.IsOnCreditHold,
		&i.CreditHoldReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBuyerProfileByUserID = `-- name: GetBuyerProfileByUserID :one
SELECT id, code, user_id, business_name, trading_name, tax_id,
       registration_number, phone, website, industry,
       employee_count, annual_revenue_minor, currency,
       credit_limit_minor, credit_terms_days, is_on_credit_hold,
       credit_hold_reason, created_at, updated_at, deleted_at
FROM identity.buyer_profile
WHERE user_id = $1 AND deleted_at IS NULL
`

type GetBuyerProfileByUserIDRow struct {
	ID                 int64              `json:"id"`
	Code               string             `json:"code"`
	UserID             int64              `json:"user_id"`
	BusinessName       string             `json:"business_name"`
	TradingName        pgtype.Text        `json:"trading_name"`
	TaxID              pgtype.Text        `json:"tax_id"`
	RegistrationNumber pgtype.Text        `json:"registration_number"`
	Phone              pgtype.Text        `json:"phone"`
	Website            pgtype.Text        `json:"website"`
	Industry           pgtype.Text        `json:"industry"`
	EmployeeCount      pgtype.Int4        `json:"employee_count"`
	AnnualRevenueMinor pgtype.Int8        `json:"annual_revenue_minor"`
	Currency           string             `json:"currency"`
	CreditLimitMinor   pgtype.Int8        `json:"credit_limit_minor"`
	CreditTermsDays    pgtype.Int4        `json:"credit_terms_days"`
	IsOnCreditHold     bool               `json:"is_on_credit_hold"`
	CreditHoldReason   pgtype.Text        `json:"credit_hold_reason"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetBuyerProfileByUserID(ctx context.Context, userID int64) (GetBuyerProfileByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getBuyerProfileByUserID, userID)
	var i GetBuyerProfileByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.BusinessName,
		&i.TradingName,
		&i.TaxID,
		&i.RegistrationNumber,
		&i.Phone,
		&i.Website,
		&i.Industry,
		&i.EmployeeCount,
		&i.AnnualRevenueMinor,
		&i.Currency,
		&i.CreditLimitMinor,
		&i.CreditTermsDays,
		&i.IsOnCreditHold,
		&i.CreditHoldReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCreditAccountByBuyer = `-- name: GetCreditAccountByBuyer :one
SELECT id, code, buyer_profile_id, limit_minor, currency, terms_days,
       current_exposure_minor, available_minor, is_on_hold, hold_reason, hold_since,
       created_at, updated_at, deleted_at
FROM identity.credit_account
WHERE buyer_profile_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCreditAccountByBuyer(ctx context.Context, buyerProfileID int64) (IdentityCreditAccount, error) {
	row := q.db.QueryRow(ctx, getCreditAccountByBuyer, buyerProfileID)
	var i IdentityCreditAccount
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.BuyerProfileID,
		&i.LimitMinor,
		&i.Currency,
		&i.TermsDays,
		&i.CurrentExposureMinor,
		&i.AvailableMinor,
		&i.IsOnHold,
		&i.HoldReason,
		&i.HoldSince,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOTPCode = `-- name: GetOTPCode :one
SELECT id, code, user_id, otp_hash, purpose, expires_at, used_at, attempts, max_attempts, created_at
FROM identity.otp_code
WHERE user_id = $1 AND purpose = $2 AND used_at IS NULL AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

type GetOTPCodeParams struct {
	UserID  int64  `json:"user_id"`
	Purpose string `json:"purpose"`
}

func (q *Queries) GetOTPCode(ctx context.Context, arg GetOTPCodeParams) (IdentityOtpCode, error) {
	row := q.db.QueryRow(ctx, getOTPCode, arg.UserID, arg.Purpose)
	var i IdentityOtpCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.OtpHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, code, user_id, token_hash, expires_at, used_at, created_at
FROM identity.password_reset_token
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash string) (IdentityPasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, tokenHash)
	var i IdentityPasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPermissionByCode = `-- name: GetPermissionByCode :one
SELECT id, code, name, description, resource, action, created_at
FROM identity.permission
WHERE code = $1 AND deleted_at IS NULL
`

type GetPermissionByCodeRow struct {
	ID          int64       `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Resource    string      `json:"resource"`
	Action      string      `json:"action"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) GetPermissionByCode(ctx context.Context, code string) (GetPermissionByCodeRow, error) {
	row := q.db.QueryRow(ctx, getPermissionByCode, code)
	var i GetPermissionByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Resource,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}

const getPriceListAssignmentsByBuyer = `-- name: GetPriceListAssignmentsByBuyer :many
SELECT id, code, buyer_profile_id, price_list_id,
       effective_from, effective_to, assigned_at
FROM identity.price_list_assignment
WHERE buyer_profile_id = $1 AND deleted_at IS NULL
ORDER BY effective_from DESC
`

type GetPriceListAssignmentsByBuyerRow struct {
	ID             int64       `json:"id"`
	Code           string      `json:"code"`
	BuyerProfileID int64       `json:"buyer_profile_id"`
	PriceListID    int64       `json:"price_list_id"`
	EffectiveFrom  pgtype.Date `json:"effective_from"`
	EffectiveTo    pgtype.Date `json:"effective_to"`
	AssignedAt     time.Time   `json:"assigned_at"`
}

func (q *Queries) GetPriceListAssignmentsByBuyer(ctx context.Context, buyerProfileID int64) ([]GetPriceListAssignmentsByBuyerRow, error) {
	rows, err := q.db.Query(ctx, getPriceListAssignmentsByBuyer, buyerProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPriceListAssignmentsByBuyerRow{}
	for rows.Next() {
		var i GetPriceListAssignmentsByBuyerRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.BuyerProfileID,
			&i.PriceListID,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPurchaseScopesByBuyer = `-- name: GetPurchaseScopesByBuyer :many
SELECT id, code, buyer_profile_id, handling_class,
       granted_at, granted_by, expires_at, created_at
FROM identity.purchase_scope
WHERE buyer_profile_id = $1 AND deleted_at IS NULL
ORDER BY granted_at DESC
`

type GetPurchaseScopesByBuyerRow struct {
	ID             int64              `json:"id"`
	Code           string             `json:"code"`
	BuyerProfileID int64              `json:"buyer_profile_id"`
	HandlingClass  string             `json:"handling_class"`
	GrantedAt      time.Time          `json:"granted_at"`
	GrantedBy      pgtype.Int8        `json:"granted_by"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      time.Time          `json:"created_at"`
}

func (q *Queries) GetPurchaseScopesByBuyer(ctx context.Context, buyerProfileID int64) ([]GetPurchaseScopesByBuyerRow, error) {
	rows, err := q.db.Query(ctx, getPurchaseScopesByBuyer, buyerProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPurchaseScopesByBuyerRow{}
	for rows.Next() {
		var i GetPurchaseScopesByBuyerRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.BuyerProfileID,
			&i.HandlingClass,
			&i.GrantedAt,
			&i.GrantedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, code, user_id, token_hash, family_id, expires_at,
       revoked_at, revoked_reason, created_at, replaced_by_id
FROM identity.refresh_token
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (IdentityRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i IdentityRefreshToken
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, code, name, description, is_system, created_at, updated_at
FROM identity.role
WHERE code = $1 AND deleted_at IS NULL
`

type GetRoleByCodeRow struct {
	ID          int64       `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsSystem    bool        `json:"is_system"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

func (q *Queries) GetRoleByCode(ctx context.Context, code string) (GetRoleByCodeRow, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, code)
	var i GetRoleByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByCode = `-- name: GetSessionByCode :one
SELECT id, code, user_id, refresh_token_id, ip_address, user_agent,
       expires_at, revoked_at, created_at
FROM identity.session
WHERE code = $1 AND revoked_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetSessionByCode(ctx context.Context, code string) (IdentitySession, error) {
	row := q.db.QueryRow(ctx, getSessionByCode, code)
	var i IdentitySession
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.RefreshTokenID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSupplierProfileByCode = `-- name: GetSupplierProfileByCode :one
SELECT id, code, user_id, company_name, trading_name, tax_id,
       registration_number, phone, email, website,
       address_line1, address_line2, city, state_province,
       postal_code, country, contact_person, contact_phone, contact_email,
       is_approved, approved_at, approved_by, created_at, updated_at, deleted_at
FROM identity.supplier_profile
WHERE code = $1 AND deleted_at IS NULL
`

type GetSupplierProfileByCodeRow struct {
	ID                 int64              `json:"id"`
	Code               string             `json:"code"`
	UserID             int64              `json:"user_id"`
	CompanyName        string             `json:"company_name"`
	TradingName        pgtype.Text        `json:"trading_name"`
	TaxID              pgtype.Text        `json:"tax_id"`
	RegistrationNumber pgtype.Text        `json:"registration_number"`
	Phone              pgtype.Text        `json:"phone"`
	Email              pgtype.Text        `json:"email"`
	Website            pgtype.Text        `json:"website"`
	AddressLine1       pgtype.Text        `json:"address_line1"`
	AddressLine2       pgtype.Text        `json:"address_line2"`
	City               pgtype.Text        `json:"city"`
	StateProvince      pgtype.Text        `json:"state_province"`
	PostalCode         pgtype.Text        `json:"postal_code"`
	Country            string             `json:"country"`
	ContactPerson      pgtype.Text        `json:"contact_person"`
	ContactPhone       pgtype.Text        `json:"contact_phone"`
	ContactEmail       pgtype.Text        `json:"contact_email"`
	IsApproved         bool               `json:"is_approved"`
	ApprovedAt         pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy         pgtype.Int8        `json:"approved_by"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetSupplierProfileByCode(ctx context.Context, code string) (GetSupplierProfileByCodeRow, error) {
	row := q.db.QueryRow(ctx, getSupplierProfileByCode, code)
	var i GetSupplierProfileByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.CompanyName,
		&i.TradingName,
		&i.TaxID,
		&i.RegistrationNumber,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.StateProvince,
		&i.PostalCode,
		&i.Country,
		&i.ContactPerson,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.IsApproved,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSupplierProfileByUserID = `-- name: GetSupplierProfileByUserID :one
SELECT id, code, user_id, company_name, trading_name, tax_id,
       registration_number, phone, email, website,
       address_line1, address_line2, city, state_province,
       postal_code, country, contact_person, contact_phone, contact_email,
       is_approved, approved_at, approved_by, created_at, updated_at, deleted_at
FROM identity.supplier_profile
WHERE user_id = $1 AND deleted_at IS NULL
`

type GetSupplierProfileByUserIDRow struct {
	ID                 int64              `json:"id"`
	Code               string             `json:"code"`
	UserID             int64              `json:"user_id"`
	CompanyName        string             `json:"company_name"`
	TradingName        pgtype.Text        `json:"trading_name"`
	TaxID              pgtype.Text        `json:"tax_id"`
	RegistrationNumber pgtype.Text        `json:"registration_number"`
	Phone              pgtype.Text        `json:"phone"`
	Email              pgtype.Text        `json:"email"`
	Website            pgtype.Text        `json:"website"`
	AddressLine1       pgtype.Text        `json:"address_line1"`
	AddressLine2       pgtype.Text        `json:"address_line2"`
	City               pgtype.Text        `json:"city"`
	StateProvince      pgtype.Text        `json:"state_province"`
	PostalCode         pgtype.Text        `json:"postal_code"`
	Country            string             `json:"country"`
	ContactPerson      pgtype.Text        `json:"contact_person"`
	ContactPhone       pgtype.Text        `json:"contact_phone"`
	ContactEmail       pgtype.Text        `json:"contact_email"`
	IsApproved         bool               `json:"is_approved"`
	ApprovedAt         pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy         pgtype.Int8        `json:"approved_by"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetSupplierProfileByUserID(ctx context.Context, userID int64) (GetSupplierProfileByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getSupplierProfileByUserID, userID)
	var i GetSupplierProfileByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.CompanyName,
		&i.TradingName,
		&i.TaxID,
		&i.RegistrationNumber,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.StateProvince,
		&i.PostalCode,
		&i.Country,
		&i.ContactPerson,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.IsApproved,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByCode = `-- name: GetUserByCode :one
SELECT id, code, email, password_hash, user_type, is_active, is_verified,
       last_login_at, failed_login_attempts, locked_until,
       created_at, updated_at, deleted_at
FROM identity.user
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByCode(ctx context.Context, code string) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByCode, code)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.PasswordHash,
		&i.UserType,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, code, email, password_hash, user_type, is_active, is_verified,
       last_login_at, failed_login_attempts, locked_until,
       created_at, updated_at, deleted_at
FROM identity.user
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.PasswordHash,
		&i.UserType,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, code, email, password_hash, user_type, is_active, is_verified,
       last_login_at, failed_login_attempts, locked_until,
       created_at, updated_at, deleted_at
FROM identity.user
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.PasswordHash,
		&i.UserType,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT p.id, p.code, p.name, p.resource, p.action
FROM identity.permission p
JOIN identity.role_permission rp ON p.id = rp.permission_id
JOIN identity.user_role ur ON rp.role_id = ur.role_id
WHERE ur.user_id = $1 AND p.deleted_at IS NULL
`

type GetUserPermissionsRow struct {
	ID       int64  `json:"id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
	Resource string `json:"resource"`
	Action   string `json:"action"`
}

func (q *Queries) GetUserPermissions(ctx context.Context, userID int64) ([]GetUserPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserPermissionsRow{}
	for rows.Next() {
		var i GetUserPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Resource,
			&i.Action,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.code, r.name, r.description, r.is_system
FROM identity.role r
JOIN identity.user_role ur ON r.id = ur.role_id
WHERE ur.user_id = $1 AND r.deleted_at IS NULL
`

type GetUserRolesRow struct {
	ID          int64       `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsSystem    bool        `json:"is_system"`
}

func (q *Queries) GetUserRoles(ctx context.Context, userID int64) ([]GetUserRolesRow, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRolesRow{}
	for rows.Next() {
		var i GetUserRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVerificationApplicationByBuyer = `-- name: GetVerificationApplicationByBuyer :one
SELECT id, code, buyer_profile_id, status, submitted_at, decided_at,
       decided_by, decision_reason, rejection_reason,
       created_at, updated_at, deleted_at
FROM identity.verification_application
WHERE buyer_profile_id = $1 AND deleted_at IS NULL
ORDER BY submitted_at DESC
LIMIT 1
`

type GetVerificationApplicationByBuyerRow struct {
	ID              int64                      `json:"id"`
	Code            string                     `json:"code"`
	BuyerProfileID  int64                      `json:"buyer_profile_id"`
	Status          IdentityVerificationStatus `json:"status"`
	SubmittedAt     time.Time                  `json:"submitted_at"`
	DecidedAt       pgtype.Timestamptz         `json:"decided_at"`
	DecidedBy       pgtype.Int8                `json:"decided_by"`
	DecisionReason  pgtype.Text                `json:"decision_reason"`
	RejectionReason pgtype.Text                `json:"rejection_reason"`
	CreatedAt       time.Time                  `json:"created_at"`
	UpdatedAt       time.Time                  `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz         `json:"deleted_at"`
}

func (q *Queries) GetVerificationApplicationByBuyer(ctx context.Context, buyerProfileID int64) (GetVerificationApplicationByBuyerRow, error) {
	row := q.db.QueryRow(ctx, getVerificationApplicationByBuyer, buyerProfileID)
	var i GetVerificationApplicationByBuyerRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.BuyerProfileID,
		&i.Status,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.DecisionReason,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVerificationApplicationByID = `-- name: GetVerificationApplicationByID :one
SELECT id, code, buyer_profile_id, status, submitted_at, decided_at,
       decided_by, decision_reason, rejection_reason,
       licence_number, licence_expiry, trading_name,
       business_address_line1, business_address_line2,
       business_city, business_state_province, business_postal_code, business_country,
       created_at, updated_at, deleted_at
FROM identity.verification_application
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetVerificationApplicationByID(ctx context.Context, id int64) (IdentityVerificationApplication, error) {
	row := q.db.QueryRow(ctx, getVerificationApplicationByID, id)
	var i IdentityVerificationApplication
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.BuyerProfileID,
		&i.Status,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.DecisionReason,
		&i.RejectionReason,
		&i.LicenceNumber,
		&i.LicenceExpiry,
		&i.TradingName,
		&i.BusinessAddressLine1,
		&i.BusinessAddressLine2,
		&i.BusinessCity,
		&i.BusinessStateProvince,
		&i.BusinessPostalCode,
		&i.BusinessCountry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVerificationDocuments = `-- name: GetVerificationDocuments :many
SELECT id, code, verification_application_id, document_type,
       file_name, file_path, file_size, mime_type,
       uploaded_at, uploaded_by, created_at
FROM identity.verification_document
WHERE verification_application_id = $1 AND deleted_at IS NULL
ORDER BY uploaded_at DESC
`

type GetVerificationDocumentsRow struct {
	ID                        int64       `json:"id"`
	Code                      string      `json:"code"`
	VerificationApplicationID int64       `json:"verification_application_id"`
	DocumentType              string      `json:"document_type"`
	FileName                  string      `json:"file_name"`
	FilePath                  string      `json:"file_path"`
	FileSize                  int64       `json:"file_size"`
	MimeType                  string      `json:"mime_type"`
	UploadedAt                time.Time   `json:"uploaded_at"`
	UploadedBy                pgtype.Int8 `json:"uploaded_by"`
	CreatedAt                 time.Time   `json:"created_at"`
}

func (q *Queries) GetVerificationDocuments(ctx context.Context, verificationApplicationID int64) ([]GetVerificationDocumentsRow, error) {
	rows, err := q.db.Query(ctx, getVerificationDocuments, verificationApplicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVerificationDocumentsRow{}
	for rows.Next() {
		var i GetVerificationDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.VerificationApplicationID,
			&i.DocumentType,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.UploadedAt,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE identity.otp_code
SET attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, id)
	return err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, code, name, description, resource, action, created_at
FROM identity.permission
WHERE deleted_at IS NULL
ORDER BY resource, action
`

type ListPermissionsRow struct {
	ID          int64       `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Resource    string      `json:"resource"`
	Action      string      `json:"action"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) ListPermissions(ctx context.Context) ([]ListPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPermissionsRow{}
	for rows.Next() {
		var i ListPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Resource,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, code, name, description, is_system, created_at
FROM identity.role
WHERE deleted_at IS NULL
ORDER BY code
`

type ListRolesRow struct {
	ID          int64       `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsSystem    bool        `json:"is_system"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, code, email, user_type, is_active, is_verified,
       last_login_at, created_at, updated_at
FROM identity.user
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID          int64              `json:"id"`
	Code        string             `json:"code"`
	Email       string             `json:"email"`
	UserType    IdentityUserType   `json:"user_type"`
	IsActive    bool               `json:"is_active"`
	IsVerified  bool               `json:"is_verified"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Email,
			&i.UserType,
			&i.IsActive,
			&i.IsVerified,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationApplications = `-- name: ListVerificationApplications :many
SELECT id, code, buyer_profile_id, status, submitted_at, decided_at,
       decided_by, decision_reason, rejection_reason,
       created_at, updated_at
FROM identity.verification_application
WHERE deleted_at IS NULL
  AND ($1::identity.verification_status IS NULL OR status = $1)
ORDER BY submitted_at DESC
LIMIT $2 OFFSET $3
`

type ListVerificationApplicationsParams struct {
	Column1 IdentityVerificationStatus `json:"column_1"`
	Limit   int32                      `json:"limit"`
	Offset  int32                      `json:"offset"`
}

type ListVerificationApplicationsRow struct {
	ID              int64                      `json:"id"`
	Code            string                     `json:"code"`
	BuyerProfileID  int64                      `json:"buyer_profile_id"`
	Status          IdentityVerificationStatus `json:"status"`
	SubmittedAt     time.Time                  `json:"submitted_at"`
	DecidedAt       pgtype.Timestamptz         `json:"decided_at"`
	DecidedBy       pgtype.Int8                `json:"decided_by"`
	DecisionReason  pgtype.Text                `json:"decision_reason"`
	RejectionReason pgtype.Text                `json:"rejection_reason"`
	CreatedAt       time.Time                  `json:"created_at"`
	UpdatedAt       time.Time                  `json:"updated_at"`
}

func (q *Queries) ListVerificationApplications(ctx context.Context, arg ListVerificationApplicationsParams) ([]ListVerificationApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listVerificationApplications, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVerificationApplicationsRow{}
	for rows.Next() {
		var i ListVerificationApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.BuyerProfileID,
			&i.Status,
			&i.SubmittedAt,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.DecisionReason,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM identity.user_role
WHERE user_id = $1 AND role_id = $2
`

type RemoveRoleFromUserParams struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.Exec(ctx, removeRoleFromUser, arg.UserID, arg.RoleID)
	return err
}

const replaceRefreshToken = `-- name: ReplaceRefreshToken :one
WITH old AS (
    UPDATE identity.refresh_token
    SET revoked_at = NOW(), revoked_reason = 'rotated', replaced_by_id = $2
    WHERE id = $1 AND revoked_at IS NULL
    RETURNING family_id
)
INSERT INTO identity.refresh_token (code, user_id, token_hash, family_id, expires_at)
SELECT $3, rt.user_id, $4, rt.family_id, $5
FROM identity.refresh_token rt
JOIN old ON rt.family_id = old.family_id
WHERE rt.id = $1
RETURNING id, code, user_id, family_id, expires_at, created_at
`

type ReplaceRefreshTokenParams struct {
	ID           int64       `json:"id"`
	ReplacedByID pgtype.Int8 `json:"replaced_by_id"`
	Code         string      `json:"code"`
	TokenHash    string      `json:"token_hash"`
	ExpiresAt    time.Time   `json:"expires_at"`
}

type ReplaceRefreshTokenRow struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	UserID    int64     `json:"user_id"`
	FamilyID  string    `json:"family_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ReplaceRefreshToken(ctx context.Context, arg ReplaceRefreshTokenParams) (ReplaceRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, replaceRefreshToken,
		arg.ID,
		arg.ReplacedByID,
		arg.Code,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i ReplaceRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE identity.refresh_token
SET revoked_at = NOW(), revoked_reason = $2
WHERE id = $1
`

type RevokeRefreshTokenParams struct {
	ID            int64       `json:"id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.ID, arg.RevokedReason)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE identity.refresh_token
SET revoked_at = NOW(), revoked_reason = $2
WHERE family_id = $1 AND revoked_at IS NULL
`

type RevokeRefreshTokenFamilyParams struct {
	FamilyID      string      `json:"family_id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, arg RevokeRefreshTokenFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, arg.FamilyID, arg.RevokedReason)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE identity.session
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE identity.session
SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const setDefaultAddress = `-- name: SetDefaultAddress :exec
UPDATE identity.address
SET is_default = CASE WHEN id = $1 THEN TRUE ELSE FALSE END,
    updated_at = NOW()
WHERE owner_user_id = $2 AND owner_type = $3 AND deleted_at IS NULL
`

type SetDefaultAddressParams struct {
	ID          int64            `json:"id"`
	OwnerUserID int64            `json:"owner_user_id"`
	OwnerType   IdentityUserType `json:"owner_type"`
}

func (q *Queries) SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) error {
	_, err := q.db.Exec(ctx, setDefaultAddress, arg.ID, arg.OwnerUserID, arg.OwnerType)
	return err
}

const softDeleteAddress = `-- name: SoftDeleteAddress :exec
UPDATE identity.address
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteAddress(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteAddress, id)
	return err
}

const softDeleteBuyerProfile = `-- name: SoftDeleteBuyerProfile :exec
UPDATE identity.buyer_profile
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteBuyerProfile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteBuyerProfile, id)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE identity.user
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE identity.address
SET label = COALESCE($2, label),
    recipient_name = COALESCE($3, recipient_name),
    company_name = COALESCE($4, company_name),
    line1 = COALESCE($5, line1),
    line2 = COALESCE($6, line2),
    city = COALESCE($7, city),
    state_province = COALESCE($8, state_province),
    postal_code = COALESCE($9, postal_code),
    country = COALESCE($10, country),
    phone = COALESCE($11, phone),
    is_default = COALESCE($12, is_default),
    handling_class = COALESCE($13, handling_class),
    delivery_instructions = COALESCE($14, delivery_instructions),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, owner_user_id, owner_type, label, created_at, updated_at
`

type UpdateAddressParams struct {
	ID                   int64       `json:"id"`
	Label                string      `json:"label"`
	RecipientName        pgtype.Text `json:"recipient_name"`
	CompanyName          pgtype.Text `json:"company_name"`
	Line1                string      `json:"line1"`
	Line2                pgtype.Text `json:"line2"`
	City                 string      `json:"city"`
	StateProvince        pgtype.Text `json:"state_province"`
	PostalCode           string      `json:"postal_code"`
	Country              string      `json:"country"`
	Phone                pgtype.Text `json:"phone"`
	IsDefault            bool        `json:"is_default"`
	HandlingClass        pgtype.Text `json:"handling_class"`
	DeliveryInstructions pgtype.Text `json:"delivery_instructions"`
}

type UpdateAddressRow struct {
	ID          int64            `json:"id"`
	Code        string           `json:"code"`
	OwnerUserID int64            `json:"owner_user_id"`
	OwnerType   IdentityUserType `json:"owner_type"`
	Label       string           `json:"label"`
	CreatedAt   time.Time        `json:"created_at"`
	UpdatedAt   time.Time        `json:"updated_at"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (UpdateAddressRow, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.ID,
		arg.Label,
		arg.RecipientName,
		arg.CompanyName,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.StateProvince,
		arg.PostalCode,
		arg.Country,
		arg.Phone,
		arg.IsDefault,
		arg.HandlingClass,
		arg.DeliveryInstructions,
	)
	var i UpdateAddressRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OwnerUserID,
		&i.OwnerType,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBuyerProfile = `-- name: UpdateBuyerProfile :one
UPDATE identity.buyer_profile
SET business_name = COALESCE($2, business_name),
    trading_name = COALESCE($3, trading_name),
    tax_id = COALESCE($4, tax_id),
    registration_number = COALESCE($5, registration_number),
    phone = COALESCE($6, phone),
    website = COALESCE($7, website),
    industry = COALESCE($8, industry),
    employee_count = COALESCE($9, employee_count),
    annual_revenue_minor = COALESCE($10, annual_revenue_minor),
    currency = COALESCE($11, currency),
    credit_limit_minor = COALESCE($12, credit_limit_minor),
    credit_terms_days = COALESCE($13, credit_terms_days),
    is_on_credit_hold = COALESCE($14, is_on_credit_hold),
    credit_hold_reason = COALESCE($15, credit_hold_reason),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, user_id, business_name, created_at, updated_at
`

type UpdateBuyerProfileParams struct {
	ID                 int64       `json:"id"`
	BusinessName       string      `json:"business_name"`
	TradingName        pgtype.Text `json:"trading_name"`
	TaxID              pgtype.Text `json:"tax_id"`
	RegistrationNumber pgtype.Text `json:"registration_number"`
	Phone              pgtype.Text `json:"phone"`
	Website            pgtype.Text `json:"website"`
	Industry           pgtype.Text `json:"industry"`
	EmployeeCount      pgtype.Int4 `json:"employee_count"`
	AnnualRevenueMinor pgtype.Int8 `json:"annual_revenue_minor"`
	Currency           string      `json:"currency"`
	CreditLimitMinor   pgtype.Int8 `json:"credit_limit_minor"`
	CreditTermsDays    pgtype.Int4 `json:"credit_terms_days"`
	IsOnCreditHold     bool        `json:"is_on_credit_hold"`
	CreditHoldReason   pgtype.Text `json:"credit_hold_reason"`
}

type UpdateBuyerProfileRow struct {
	ID           int64     `json:"id"`
	Code         string    `json:"code"`
	UserID       int64     `json:"user_id"`
	BusinessName string    `json:"business_name"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) UpdateBuyerProfile(ctx context.Context, arg UpdateBuyerProfileParams) (UpdateBuyerProfileRow, error) {
	row := q.db.QueryRow(ctx, updateBuyerProfile,
		arg.ID,
		arg.BusinessName,
		arg.TradingName,
		arg.TaxID,
		arg.RegistrationNumber,
		arg.Phone,
		arg.Website,
		arg.Industry,
		arg.EmployeeCount,
		arg.AnnualRevenueMinor,
		arg.Currency,
		arg.CreditLimitMinor,
		arg.CreditTermsDays,
		arg.IsOnCreditHold,
		arg.CreditHoldReason,
	)
	var i UpdateBuyerProfileRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.BusinessName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCreditAccountExposure = `-- name: UpdateCreditAccountExposure :exec
UPDATE identity.credit_account
SET current_exposure_minor = $2,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateCreditAccountExposureParams struct {
	ID                   int64 `json:"id"`
	CurrentExposureMinor int64 `json:"current_exposure_minor"`
}

func (q *Queries) UpdateCreditAccountExposure(ctx context.Context, arg UpdateCreditAccountExposureParams) error {
	_, err := q.db.Exec(ctx, updateCreditAccountExposure, arg.ID, arg.CurrentExposureMinor)
	return err
}

const updateCreditAccountHold = `-- name: UpdateCreditAccountHold :exec
UPDATE identity.credit_account
SET is_on_hold = $2,
    hold_reason = $3,
    hold_since = CASE WHEN $2 THEN NOW() ELSE NULL END,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateCreditAccountHoldParams struct {
	ID         int64       `json:"id"`
	IsOnHold   bool        `json:"is_on_hold"`
	HoldReason pgtype.Text `json:"hold_reason"`
}

func (q *Queries) UpdateCreditAccountHold(ctx context.Context, arg UpdateCreditAccountHoldParams) error {
	_, err := q.db.Exec(ctx, updateCreditAccountHold, arg.ID, arg.IsOnHold, arg.HoldReason)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE identity.user
SET email = COALESCE($2, email),
    user_type = COALESCE($3, user_type),
    is_active = COALESCE($4, is_active),
    is_verified = COALESCE($5, is_verified),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, email, user_type, is_active, is_verified, created_at, updated_at
`

type UpdateUserParams struct {
	ID         int64            `json:"id"`
	Email      string           `json:"email"`
	UserType   IdentityUserType `json:"user_type"`
	IsActive   bool             `json:"is_active"`
	IsVerified bool             `json:"is_verified"`
}

type UpdateUserRow struct {
	ID         int64            `json:"id"`
	Code       string           `json:"code"`
	Email      string           `json:"email"`
	UserType   IdentityUserType `json:"user_type"`
	IsActive   bool             `json:"is_active"`
	IsVerified bool             `json:"is_verified"`
	CreatedAt  time.Time        `json:"created_at"`
	UpdatedAt  time.Time        `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.UserType,
		arg.IsActive,
		arg.IsVerified,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.UserType,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE identity.user
SET last_login_at = NOW(),
    failed_login_attempts = 0,
    locked_until = NULL,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserLoginAttempts = `-- name: UpdateUserLoginAttempts :exec
UPDATE identity.user
SET failed_login_attempts = $2,
    locked_until = $3,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserLoginAttemptsParams struct {
	ID                  int64              `json:"id"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) UpdateUserLoginAttempts(ctx context.Context, arg UpdateUserLoginAttemptsParams) error {
	_, err := q.db.Exec(ctx, updateUserLoginAttempts, arg.ID, arg.FailedLoginAttempts, arg.LockedUntil)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE identity.user
SET password_hash = $2,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateVerificationApplicationStatus = `-- name: UpdateVerificationApplicationStatus :one
UPDATE identity.verification_application
SET status = $2,
    decided_at = CASE WHEN $2 IN ('approved', 'rejected') THEN NOW() ELSE decided_at END,
    decided_by = CASE WHEN $2 IN ('approved', 'rejected') THEN $3 ELSE decided_by END,
    decision_reason = CASE WHEN $2 = 'approved' THEN $4 ELSE decision_reason END,
    rejection_reason = CASE WHEN $2 = 'rejected' THEN $4 ELSE rejection_reason END,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, buyer_profile_id, status, decided_at, decided_by
`

type UpdateVerificationApplicationStatusParams struct {
	ID             int64                      `json:"id"`
	Status         IdentityVerificationStatus `json:"status"`
	DecidedBy      pgtype.Int8                `json:"decided_by"`
	DecisionReason pgtype.Text                `json:"decision_reason"`
}

type UpdateVerificationApplicationStatusRow struct {
	ID             int64                      `json:"id"`
	Code           string                     `json:"code"`
	BuyerProfileID int64                      `json:"buyer_profile_id"`
	Status         IdentityVerificationStatus `json:"status"`
	DecidedAt      pgtype.Timestamptz         `json:"decided_at"`
	DecidedBy      pgtype.Int8                `json:"decided_by"`
}

func (q *Queries) UpdateVerificationApplicationStatus(ctx context.Context, arg UpdateVerificationApplicationStatusParams) (UpdateVerificationApplicationStatusRow, error) {
	row := q.db.QueryRow(ctx, updateVerificationApplicationStatus,
		arg.ID,
		arg.Status,
		arg.DecidedBy,
		arg.DecisionReason,
	)
	var i UpdateVerificationApplicationStatusRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.BuyerProfileID,
		&i.Status,
		&i.DecidedAt,
		&i.DecidedBy,
	)
	return i, err
}

const useOTPCode = `-- name: UseOTPCode :exec
UPDATE identity.otp_code
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) UseOTPCode(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, useOTPCode, id)
	return err
}

const usePasswordResetToken = `-- name: UsePasswordResetToken :exec
UPDATE identity.password_reset_token
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) UsePasswordResetToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, usePasswordResetToken, id)
	return err
}
