// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package catalog

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProduct = `-- name: ArchiveProduct :exec
UPDATE catalog.product
SET status = 'archived', updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) ArchiveProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, archiveProduct, id)
	return err
}

const countBrands = `-- name: CountBrands :one
SELECT COUNT(*)
FROM catalog.brand
WHERE deleted_at IS NULL AND is_active = TRUE
`

func (q *Queries) CountBrands(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBrands)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCategories = `-- name: CountCategories :one
SELECT COUNT(*)
FROM catalog.category
WHERE deleted_at IS NULL
  AND ($1::int8 = 0 OR parent_id = $1)
`

func (q *Queries) CountCategories(ctx context.Context, dollar_1 int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*)
FROM catalog.product,
    (SELECT
        $1::text AS p_status,
        $2::bigint AS p_category_id,
        $3::bigint AS p_brand_id,
        $4::text AS p_handling_class,
        $5::bigint AS p_supplier_id,
        $6::text AS p_query
    ) params
WHERE deleted_at IS NULL
  AND (params.p_status = '' OR status = params.p_status::catalog.product_status)
  AND (params.p_category_id = 0 OR category_id = params.p_category_id)
  AND (params.p_brand_id = 0 OR brand_id = params.p_brand_id)
  AND (params.p_handling_class = '' OR handling_class = params.p_handling_class::catalog_handling_class_type)
  AND (params.p_supplier_id = 0 OR supplier_id = params.p_supplier_id)
  AND (params.p_query IS NULL OR name ILIKE '%' || params.p_query || '%' OR description ILIKE '%' || params.p_query || '%')
`

type CountProductsParams struct {
	Column1 string `json:"column_1"`
	Column2 int64  `json:"column_2"`
	Column3 int64  `json:"column_3"`
	Column4 string `json:"column_4"`
	Column5 int64  `json:"column_5"`
	Column6 string `json:"column_6"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchProducts = `-- name: CountSearchProducts :one
SELECT COUNT(*)
FROM catalog.product p
LEFT JOIN catalog.category c ON p.category_id = c.id AND c.deleted_at IS NULL
LEFT JOIN catalog.brand b ON p.brand_id = b.id AND b.deleted_at IS NULL
WHERE p.deleted_at IS NULL
  AND p.status = 'published'
  AND p.is_active = TRUE
  AND ($1::bigint = 0 OR p.category_id = $1)
  AND ($2::bigint = 0 OR p.brand_id = $2)
  AND ($3::catalog_handling_class_type = '' OR p.handling_class = $3)
  AND ($4::bigint = 0 OR p.supplier_id = $4)
  AND (
    $5 = ''
    OR p.name ILIKE '%' || $5 || '%'
    OR p.description ILIKE '%' || $5 || '%'
    OR p.short_description ILIKE '%' || $5 || '%'
    OR c.name ILIKE '%' || $5 || '%'
    OR b.name ILIKE '%' || $5 || '%'
    OR p.code ILIKE '%' || $5 || '%'
    OR p.sku ILIKE '%' || $5 || '%'
  )
`

type CountSearchProductsParams struct {
	Column1 int64                    `json:"column_1"`
	Column2 int64                    `json:"column_2"`
	Column3 CatalogHandlingClassType `json:"column_3"`
	Column4 int64                    `json:"column_4"`
	Column5 interface{}              `json:"column_5"`
}

func (q *Queries) CountSearchProducts(ctx context.Context, arg CountSearchProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchProducts,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuppliers = `-- name: CountSuppliers :one
SELECT COUNT(*)
FROM catalog.supplier
WHERE deleted_at IS NULL
`

func (q *Queries) CountSuppliers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppliers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnits = `-- name: CountUnits :one
SELECT COUNT(*)
FROM catalog.unit
WHERE deleted_at IS NULL AND is_active = TRUE
`

func (q *Queries) CountUnits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBrand = `-- name: CreateBrand :one
INSERT INTO catalog.brand (
    code, name, slug, description, logo_url, website_url
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, code, slug, name, created_at, updated_at
`

type CreateBrandParams struct {
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	WebsiteUrl  pgtype.Text `json:"website_url"`
}

type CreateBrandRow struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) (CreateBrandRow, error) {
	row := q.db.QueryRow(ctx, createBrand,
		arg.Code,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.LogoUrl,
		arg.WebsiteUrl,
	)
	var i CreateBrandRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO catalog.category (
    code, name, slug, description, parent_id, sort_order,
    seo_title, seo_description
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, code, slug, name, created_at, updated_at
`

type CreateCategoryParams struct {
	Code           string      `json:"code"`
	Name           string      `json:"name"`
	Slug           string      `json:"slug"`
	Description    pgtype.Text `json:"description"`
	ParentID       pgtype.Int8 `json:"parent_id"`
	SortOrder      int32       `json:"sort_order"`
	SeoTitle       pgtype.Text `json:"seo_title"`
	SeoDescription pgtype.Text `json:"seo_description"`
}

type CreateCategoryRow struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Code,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ParentID,
		arg.SortOrder,
		arg.SeoTitle,
		arg.SeoDescription,
	)
	var i CreateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one

INSERT INTO catalog.product (
    code, slug, name, description, short_description,
    category_id, brand_id, handling_class, base_unit_id, supplier_id,
    status, is_active, is_featured, sort_order,
    base_price_minor, currency, track_inventory,
    weight_grams, length_mm, width_mm, height_mm,
    gtin, sku,
    seo_title, seo_description, seo_keywords
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21,
    $22, $23, $24, $25, $26
) RETURNING id, code, slug, name, status, created_at, updated_at
`

type CreateProductParams struct {
	Code             string                   `json:"code"`
	Slug             string                   `json:"slug"`
	Name             string                   `json:"name"`
	Description      pgtype.Text              `json:"description"`
	ShortDescription pgtype.Text              `json:"short_description"`
	CategoryID       int64                    `json:"category_id"`
	BrandID          pgtype.Int8              `json:"brand_id"`
	HandlingClass    CatalogHandlingClassType `json:"handling_class"`
	BaseUnitID       int64                    `json:"base_unit_id"`
	SupplierID       pgtype.Int8              `json:"supplier_id"`
	Status           CatalogProductStatus     `json:"status"`
	IsActive         bool                     `json:"is_active"`
	IsFeatured       bool                     `json:"is_featured"`
	SortOrder        int32                    `json:"sort_order"`
	BasePriceMinor   pgtype.Int8              `json:"base_price_minor"`
	Currency         string                   `json:"currency"`
	TrackInventory   bool                     `json:"track_inventory"`
	WeightGrams      pgtype.Int4              `json:"weight_grams"`
	LengthMm         pgtype.Int4              `json:"length_mm"`
	WidthMm          pgtype.Int4              `json:"width_mm"`
	HeightMm         pgtype.Int4              `json:"height_mm"`
	Gtin             pgtype.Text              `json:"gtin"`
	Sku              pgtype.Text              `json:"sku"`
	SeoTitle         pgtype.Text              `json:"seo_title"`
	SeoDescription   pgtype.Text              `json:"seo_description"`
	SeoKeywords      pgtype.Text              `json:"seo_keywords"`
}

type CreateProductRow struct {
	ID        int64                `json:"id"`
	Code      string               `json:"code"`
	Slug      string               `json:"slug"`
	Name      string               `json:"name"`
	Status    CatalogProductStatus `json:"status"`
	CreatedAt time.Time            `json:"created_at"`
	UpdatedAt time.Time            `json:"updated_at"`
}

// Catalog module queries
// Products, Categories, Brands, Units, Handling Classes, Suppliers, Facets
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Code,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.ShortDescription,
		arg.CategoryID,
		arg.BrandID,
		arg.HandlingClass,
		arg.BaseUnitID,
		arg.SupplierID,
		arg.Status,
		arg.IsActive,
		arg.IsFeatured,
		arg.SortOrder,
		arg.BasePriceMinor,
		arg.Currency,
		arg.TrackInventory,
		arg.WeightGrams,
		arg.LengthMm,
		arg.WidthMm,
		arg.HeightMm,
		arg.Gtin,
		arg.Sku,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.SeoKeywords,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProductMedia = `-- name: CreateProductMedia :one
INSERT INTO catalog.product_media (
    code, product_id, url, alt_text, media_type, sort_order,
    is_primary, width_px, height_px, file_size_bytes, mime_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, code, product_id, created_at
`

type CreateProductMediaParams struct {
	Code          string      `json:"code"`
	ProductID     int64       `json:"product_id"`
	Url           string      `json:"url"`
	AltText       pgtype.Text `json:"alt_text"`
	MediaType     string      `json:"media_type"`
	SortOrder     int32       `json:"sort_order"`
	IsPrimary     bool        `json:"is_primary"`
	WidthPx       pgtype.Int4 `json:"width_px"`
	HeightPx      pgtype.Int4 `json:"height_px"`
	FileSizeBytes pgtype.Int8 `json:"file_size_bytes"`
	MimeType      pgtype.Text `json:"mime_type"`
}

type CreateProductMediaRow struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	ProductID int64     `json:"product_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateProductMedia(ctx context.Context, arg CreateProductMediaParams) (CreateProductMediaRow, error) {
	row := q.db.QueryRow(ctx, createProductMedia,
		arg.Code,
		arg.ProductID,
		arg.Url,
		arg.AltText,
		arg.MediaType,
		arg.SortOrder,
		arg.IsPrimary,
		arg.WidthPx,
		arg.HeightPx,
		arg.FileSizeBytes,
		arg.MimeType,
	)
	var i CreateProductMediaRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ProductID,
		&i.CreatedAt,
	)
	return i, err
}

const createProductUnit = `-- name: CreateProductUnit :one
INSERT INTO catalog.product_unit (
    product_id, unit_id, conversion_factor, is_default, price_minor
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, product_id, unit_id, conversion_factor, is_default, price_minor, is_active, created_at
`

type CreateProductUnitParams struct {
	ProductID        int64          `json:"product_id"`
	UnitID           int64          `json:"unit_id"`
	ConversionFactor pgtype.Numeric `json:"conversion_factor"`
	IsDefault        bool           `json:"is_default"`
	PriceMinor       pgtype.Int8    `json:"price_minor"`
}

type CreateProductUnitRow struct {
	ID               int64          `json:"id"`
	ProductID        int64          `json:"product_id"`
	UnitID           int64          `json:"unit_id"`
	ConversionFactor pgtype.Numeric `json:"conversion_factor"`
	IsDefault        bool           `json:"is_default"`
	PriceMinor       pgtype.Int8    `json:"price_minor"`
	IsActive         bool           `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
}

func (q *Queries) CreateProductUnit(ctx context.Context, arg CreateProductUnitParams) (CreateProductUnitRow, error) {
	row := q.db.QueryRow(ctx, createProductUnit,
		arg.ProductID,
		arg.UnitID,
		arg.ConversionFactor,
		arg.IsDefault,
		arg.PriceMinor,
	)
	var i CreateProductUnitRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UnitID,
		&i.ConversionFactor,
		&i.IsDefault,
		&i.PriceMinor,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO catalog.supplier (
    code, supplier_id, name, slug, description, logo_url
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, code, slug, name, created_at, updated_at
`

type CreateSupplierParams struct {
	Code        string      `json:"code"`
	SupplierID  int64       `json:"supplier_id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
}

type CreateSupplierRow struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (CreateSupplierRow, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.Code,
		arg.SupplierID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.LogoUrl,
	)
	var i CreateSupplierRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUnit = `-- name: CreateUnit :one
INSERT INTO catalog.unit (
    code, name, symbol, unit_type, base_unit_id, conversion_factor
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, code, name, symbol, created_at, updated_at
`

type CreateUnitParams struct {
	Code             string          `json:"code"`
	Name             string          `json:"name"`
	Symbol           string          `json:"symbol"`
	UnitType         CatalogUnitType `json:"unit_type"`
	BaseUnitID       pgtype.Int8     `json:"base_unit_id"`
	ConversionFactor pgtype.Numeric  `json:"conversion_factor"`
}

type CreateUnitRow struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Symbol    string    `json:"symbol"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (CreateUnitRow, error) {
	row := q.db.QueryRow(ctx, createUnit,
		arg.Code,
		arg.Name,
		arg.Symbol,
		arg.UnitType,
		arg.BaseUnitID,
		arg.ConversionFactor,
	)
	var i CreateUnitRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductAttribute = `-- name: DeleteProductAttribute :exec
UPDATE catalog.product_attribute
SET deleted_at = NOW(), updated_at = NOW()
WHERE product_id = $1 AND attribute_id = $2
`

type DeleteProductAttributeParams struct {
	ProductID   int64 `json:"product_id"`
	AttributeID int64 `json:"attribute_id"`
}

func (q *Queries) DeleteProductAttribute(ctx context.Context, arg DeleteProductAttributeParams) error {
	_, err := q.db.Exec(ctx, deleteProductAttribute, arg.ProductID, arg.AttributeID)
	return err
}

const deleteProductMedia = `-- name: DeleteProductMedia :exec
UPDATE catalog.product_media
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteProductMedia(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProductMedia, id)
	return err
}

const deleteProductUnit = `-- name: DeleteProductUnit :exec
UPDATE catalog.product_unit
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteProductUnit(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProductUnit, id)
	return err
}

const getAttributeFacets = `-- name: GetAttributeFacets :many
SELECT
    a.id AS attribute_id,
    a.code AS attribute_code,
    a.name AS attribute_name,
    a.attribute_type,
    av.id AS value_id,
    av.value AS value_name,
    COUNT(DISTINCT pa.product_id) AS count
FROM catalog.product_attribute pa
JOIN catalog.attribute a ON pa.attribute_id = a.id AND a.deleted_at IS NULL
JOIN catalog.attribute_value av ON pa.attribute_value_id = av.id AND av.deleted_at IS NULL
JOIN catalog.product p ON pa.product_id = p.id AND p.deleted_at IS NULL AND p.status = 'published' AND p.is_active = TRUE
WHERE a.is_filterable = TRUE
  AND ($1::int8 = 0 OR a.id = $1)
GROUP BY a.id, a.code, a.name, a.attribute_type, av.id, av.value
ORDER BY a.sort_order, a.name, av.sort_order, av.value
`

type GetAttributeFacetsRow struct {
	AttributeID   int64  `json:"attribute_id"`
	AttributeCode string `json:"attribute_code"`
	AttributeName string `json:"attribute_name"`
	AttributeType string `json:"attribute_type"`
	ValueID       int64  `json:"value_id"`
	ValueName     string `json:"value_name"`
	Count         int64  `json:"count"`
}

func (q *Queries) GetAttributeFacets(ctx context.Context, dollar_1 int64) ([]GetAttributeFacetsRow, error) {
	rows, err := q.db.Query(ctx, getAttributeFacets, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAttributeFacetsRow{}
	for rows.Next() {
		var i GetAttributeFacetsRow
		if err := rows.Scan(
			&i.AttributeID,
			&i.AttributeCode,
			&i.AttributeName,
			&i.AttributeType,
			&i.ValueID,
			&i.ValueName,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBrandByCode = `-- name: GetBrandByCode :one
SELECT id, code, name, slug, description, logo_url, website_url,
       is_active, created_at, updated_at, deleted_at
FROM catalog.brand
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBrandByCode(ctx context.Context, code string) (CatalogBrand, error) {
	row := q.db.QueryRow(ctx, getBrandByCode, code)
	var i CatalogBrand
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBrandByID = `-- name: GetBrandByID :one
SELECT id, code, name, slug, description, logo_url, website_url,
       is_active, created_at, updated_at, deleted_at
FROM catalog.brand
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBrandByID(ctx context.Context, id int64) (CatalogBrand, error) {
	row := q.db.QueryRow(ctx, getBrandByID, id)
	var i CatalogBrand
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBrandBySlug = `-- name: GetBrandBySlug :one
SELECT id, code, name, slug, description, logo_url, website_url,
       is_active, created_at, updated_at, deleted_at
FROM catalog.brand
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBrandBySlug(ctx context.Context, slug string) (CatalogBrand, error) {
	row := q.db.QueryRow(ctx, getBrandBySlug, slug)
	var i CatalogBrand
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryBreadcrumbs = `-- name: GetCategoryBreadcrumbs :many
WITH RECURSIVE breadcrumbs AS (
    SELECT c.id, c.code, c.name, c.slug, c.description, c.parent_id, c.sort_order,
           c.is_active, c.seo_title, c.seo_description, c.created_at, c.updated_at, c.deleted_at, 0 as level
    FROM catalog.category c
    WHERE c.id = $1 AND c.deleted_at IS NULL
    UNION ALL
    SELECT c.id, c.code, c.name, c.slug, c.description, c.parent_id, c.sort_order,
           c.is_active, c.seo_title, c.seo_description, c.created_at, c.updated_at, c.deleted_at, b.level + 1
    FROM catalog.category c
    JOIN breadcrumbs b ON c.id = b.parent_id
    WHERE c.deleted_at IS NULL
)
SELECT id, code, name, slug, description, parent_id, sort_order,
       is_active, seo_title, seo_description, created_at, updated_at, deleted_at
FROM breadcrumbs ORDER BY level DESC
`

type GetCategoryBreadcrumbsRow struct {
	ID             int64              `json:"id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	ParentID       pgtype.Int8        `json:"parent_id"`
	SortOrder      int32              `json:"sort_order"`
	IsActive       bool               `json:"is_active"`
	SeoTitle       pgtype.Text        `json:"seo_title"`
	SeoDescription pgtype.Text        `json:"seo_description"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetCategoryBreadcrumbs(ctx context.Context, id int64) ([]GetCategoryBreadcrumbsRow, error) {
	rows, err := q.db.Query(ctx, getCategoryBreadcrumbs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryBreadcrumbsRow{}
	for rows.Next() {
		var i GetCategoryBreadcrumbsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.SortOrder,
			&i.IsActive,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByCode = `-- name: GetCategoryByCode :one
SELECT id, code, name, slug, description, parent_id, sort_order,
       is_active, seo_title, seo_description, created_at, updated_at, deleted_at
FROM catalog.category
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategoryByCode(ctx context.Context, code string) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByCode, code)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.SortOrder,
		&i.IsActive,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, code, name, slug, description, parent_id, sort_order,
       is_active, seo_title, seo_description, created_at, updated_at, deleted_at
FROM catalog.category
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int64) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.SortOrder,
		&i.IsActive,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, code, name, slug, description, parent_id, sort_order,
       is_active, seo_title, seo_description, created_at, updated_at, deleted_at
FROM catalog.category
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.SortOrder,
		&i.IsActive,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryChildren = `-- name: GetCategoryChildren :many
SELECT id, code, name, slug, description, parent_id, sort_order,
       is_active, seo_title, seo_description, created_at, updated_at, deleted_at
FROM catalog.category
WHERE parent_id = $1 AND deleted_at IS NULL
ORDER BY sort_order, name
`

func (q *Queries) GetCategoryChildren(ctx context.Context, parentID pgtype.Int8) ([]CatalogCategory, error) {
	rows, err := q.db.Query(ctx, getCategoryChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogCategory{}
	for rows.Next() {
		var i CatalogCategory
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.SortOrder,
			&i.IsActive,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryTree = `-- name: GetCategoryTree :many
WITH RECURSIVE category_tree AS (
    SELECT id, code, name, slug, description, parent_id, sort_order,
           is_active, seo_title, seo_description, created_at, updated_at, deleted_at, 0 as level
    FROM catalog.category
    WHERE parent_id IS NULL AND deleted_at IS NULL
    UNION ALL
    SELECT c.id, c.code, c.name, c.slug, c.description, c.parent_id, c.sort_order,
           c.is_active, c.seo_title, c.seo_description, c.created_at, c.updated_at, c.deleted_at, ct.level + 1
    FROM catalog.category c
    JOIN category_tree ct ON c.parent_id = ct.id
    WHERE c.deleted_at IS NULL
)
SELECT id, code, name, slug, description, parent_id, sort_order, is_active, seo_title, seo_description, created_at, updated_at, deleted_at, level FROM category_tree ORDER BY level, sort_order, name
`

type GetCategoryTreeRow struct {
	ID             int64              `json:"id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	ParentID       pgtype.Int8        `json:"parent_id"`
	SortOrder      int32              `json:"sort_order"`
	IsActive       bool               `json:"is_active"`
	SeoTitle       pgtype.Text        `json:"seo_title"`
	SeoDescription pgtype.Text        `json:"seo_description"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	Level          int32              `json:"level"`
}

func (q *Queries) GetCategoryTree(ctx context.Context) ([]GetCategoryTreeRow, error) {
	rows, err := q.db.Query(ctx, getCategoryTree)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryTreeRow{}
	for rows.Next() {
		var i GetCategoryTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.SortOrder,
			&i.IsActive,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFacets = `-- name: GetFacets :many
SELECT 'category' AS facet_type, c.code AS value_id, c.name AS value_name, COUNT(DISTINCT p.id) AS count
FROM catalog.product p
JOIN catalog.category c ON p.category_id = c.id
WHERE p.deleted_at IS NULL AND p.status = 'published' AND p.is_active = TRUE
  AND c.deleted_at IS NULL AND c.is_active = TRUE
GROUP BY c.code, c.name
UNION ALL
SELECT 'brand' AS facet_type, b.code AS value_id, b.name AS value_name, COUNT(DISTINCT p.id) AS count
FROM catalog.product p
JOIN catalog.brand b ON p.brand_id = b.id
WHERE p.deleted_at IS NULL AND p.status = 'published' AND p.is_active = TRUE
  AND b.deleted_at IS NULL AND b.is_active = TRUE
GROUP BY b.code, b.name
UNION ALL
SELECT 'handling_class' AS facet_type, p.handling_class AS value_id, hc.name AS value_name, COUNT(*) AS count
FROM catalog.product p
JOIN catalog.handling_class hc ON p.handling_class = hc.name
WHERE p.deleted_at IS NULL AND p.status = 'published' AND p.is_active = TRUE
  AND hc.deleted_at IS NULL
GROUP BY p.handling_class, hc.name
UNION ALL
SELECT 'supplier' AS facet_type, s.code AS value_id, s.name AS value_name, COUNT(DISTINCT p.id) AS count
FROM catalog.product p
JOIN catalog.supplier s ON p.supplier_id = s.id
WHERE p.deleted_at IS NULL AND p.status = 'published' AND p.is_active = TRUE
  AND s.deleted_at IS NULL AND s.is_active = TRUE
GROUP BY s.code, s.name
ORDER BY facet_type, value_name
`

type GetFacetsRow struct {
	FacetType string `json:"facet_type"`
	ValueID   string `json:"value_id"`
	ValueName string `json:"value_name"`
	Count     int64  `json:"count"`
}

func (q *Queries) GetFacets(ctx context.Context) ([]GetFacetsRow, error) {
	rows, err := q.db.Query(ctx, getFacets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFacetsRow{}
	for rows.Next() {
		var i GetFacetsRow
		if err := rows.Scan(
			&i.FacetType,
			&i.ValueID,
			&i.ValueName,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilteredFacets = `-- name: GetFilteredFacets :many
WITH filtered_products AS (
    SELECT p.id
    FROM catalog.product p,
        (SELECT
            $1::bigint AS p_category_id,
            $2::bigint AS p_brand_id,
            $3::text AS p_handling_class,
            $4::bigint AS p_supplier_id,
            $5::text AS p_query
        ) params
    WHERE p.deleted_at IS NULL AND p.status = 'published' AND p.is_active = TRUE
      AND (params.p_category_id IS NULL OR p.category_id = params.p_category_id)
      AND (params.p_brand_id IS NULL OR p.brand_id = params.p_brand_id)
      AND (params.p_handling_class = '' OR p.handling_class = params.p_handling_class::catalog_handling_class_type)
      AND (params.p_supplier_id IS NULL OR p.supplier_id = params.p_supplier_id)
      AND (params.p_query IS NULL OR p.name ILIKE '%' || params.p_query || '%' OR p.description ILIKE '%' || params.p_query || '%')
)
SELECT 'category' AS facet_type, c.code AS value_id, c.name AS value_name, COUNT(DISTINCT fp.id) AS count
FROM filtered_products fp
JOIN catalog.product prod ON fp.id = prod.id
JOIN catalog.category c ON prod.category_id = c.id
WHERE c.deleted_at IS NULL AND c.is_active = TRUE
GROUP BY c.code, c.name
UNION ALL
SELECT 'brand' AS facet_type, b.code AS value_id, b.name AS value_name, COUNT(DISTINCT fp.id) AS count
FROM filtered_products fp
JOIN catalog.product prod ON fp.id = prod.id
JOIN catalog.brand b ON prod.brand_id = b.id
WHERE b.deleted_at IS NULL AND b.is_active = TRUE
GROUP BY b.code, b.name
UNION ALL
SELECT 'handling_class' AS facet_type, prod.handling_class::text AS value_id, hc.name::text AS value_name, COUNT(DISTINCT fp.id) AS count
FROM filtered_products fp
JOIN catalog.product prod ON fp.id = prod.id
JOIN catalog.handling_class hc ON prod.handling_class = hc.name
WHERE hc.deleted_at IS NULL
GROUP BY prod.handling_class, hc.name
UNION ALL
SELECT 'supplier' AS facet_type, s.code AS value_id, s.name AS value_name, COUNT(DISTINCT fp.id) AS count
FROM filtered_products fp
JOIN catalog.product prod ON fp.id = prod.id
JOIN catalog.supplier s ON prod.supplier_id = s.id
WHERE s.deleted_at IS NULL AND s.is_active = TRUE
GROUP BY s.code, s.name
ORDER BY facet_type, value_name
`

type GetFilteredFacetsParams struct {
	Column1 int64  `json:"column_1"`
	Column2 int64  `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 int64  `json:"column_4"`
	Column5 string `json:"column_5"`
}

type GetFilteredFacetsRow struct {
	FacetType string `json:"facet_type"`
	ValueID   string `json:"value_id"`
	ValueName string `json:"value_name"`
	Count     int64  `json:"count"`
}

func (q *Queries) GetFilteredFacets(ctx context.Context, arg GetFilteredFacetsParams) ([]GetFilteredFacetsRow, error) {
	rows, err := q.db.Query(ctx, getFilteredFacets,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFilteredFacetsRow{}
	for rows.Next() {
		var i GetFilteredFacetsRow
		if err := rows.Scan(
			&i.FacetType,
			&i.ValueID,
			&i.ValueName,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHandlingClassByCode = `-- name: GetHandlingClassByCode :one
SELECT id, code, name, description, sort_order,
       temperature_min_c, temperature_max_c,
       is_active, created_at, updated_at, deleted_at
FROM catalog.handling_class
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetHandlingClassByCode(ctx context.Context, code string) (CatalogHandlingClass, error) {
	row := q.db.QueryRow(ctx, getHandlingClassByCode, code)
	var i CatalogHandlingClass
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.TemperatureMinC,
		&i.TemperatureMaxC,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getHandlingClassByID = `-- name: GetHandlingClassByID :one
SELECT id, code, name, description, sort_order,
       temperature_min_c, temperature_max_c,
       is_active, created_at, updated_at, deleted_at
FROM catalog.handling_class
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetHandlingClassByID(ctx context.Context, id int64) (CatalogHandlingClass, error) {
	row := q.db.QueryRow(ctx, getHandlingClassByID, id)
	var i CatalogHandlingClass
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.TemperatureMinC,
		&i.TemperatureMaxC,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductByCode = `-- name: GetProductByCode :one
SELECT
    id, code, slug, name, description, short_description,
    category_id, brand_id, handling_class, base_unit_id, supplier_id,
    status, is_active, is_featured, sort_order,
    base_price_minor, currency, track_inventory,
    weight_grams, length_mm, width_mm, height_mm,
    gtin, sku,
    seo_title, seo_description, seo_keywords,
    created_at, updated_at, published_at, deleted_at
FROM catalog.product
WHERE code = $1 AND deleted_at IS NULL
`

type GetProductByCodeRow struct {
	ID               int64                    `json:"id"`
	Code             string                   `json:"code"`
	Slug             string                   `json:"slug"`
	Name             string                   `json:"name"`
	Description      pgtype.Text              `json:"description"`
	ShortDescription pgtype.Text              `json:"short_description"`
	CategoryID       int64                    `json:"category_id"`
	BrandID          pgtype.Int8              `json:"brand_id"`
	HandlingClass    CatalogHandlingClassType `json:"handling_class"`
	BaseUnitID       int64                    `json:"base_unit_id"`
	SupplierID       pgtype.Int8              `json:"supplier_id"`
	Status           CatalogProductStatus     `json:"status"`
	IsActive         bool                     `json:"is_active"`
	IsFeatured       bool                     `json:"is_featured"`
	SortOrder        int32                    `json:"sort_order"`
	BasePriceMinor   pgtype.Int8              `json:"base_price_minor"`
	Currency         string                   `json:"currency"`
	TrackInventory   bool                     `json:"track_inventory"`
	WeightGrams      pgtype.Int4              `json:"weight_grams"`
	LengthMm         pgtype.Int4              `json:"length_mm"`
	WidthMm          pgtype.Int4              `json:"width_mm"`
	HeightMm         pgtype.Int4              `json:"height_mm"`
	Gtin             pgtype.Text              `json:"gtin"`
	Sku              pgtype.Text              `json:"sku"`
	SeoTitle         pgtype.Text              `json:"seo_title"`
	SeoDescription   pgtype.Text              `json:"seo_description"`
	SeoKeywords      pgtype.Text              `json:"seo_keywords"`
	CreatedAt        time.Time                `json:"created_at"`
	UpdatedAt        time.Time                `json:"updated_at"`
	PublishedAt      pgtype.Timestamptz       `json:"published_at"`
	DeletedAt        pgtype.Timestamptz       `json:"deleted_at"`
}

func (q *Queries) GetProductByCode(ctx context.Context, code string) (GetProductByCodeRow, error) {
	row := q.db.QueryRow(ctx, getProductByCode, code)
	var i GetProductByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ShortDescription,
		&i.CategoryID,
		&i.BrandID,
		&i.HandlingClass,
		&i.BaseUnitID,
		&i.SupplierID,
		&i.Status,
		&i.IsActive,
		&i.IsFeatured,
		&i.SortOrder,
		&i.BasePriceMinor,
		&i.Currency,
		&i.TrackInventory,
		&i.WeightGrams,
		&i.LengthMm,
		&i.WidthMm,
		&i.HeightMm,
		&i.Gtin,
		&i.Sku,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.SeoKeywords,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    id, code, slug, name, description, short_description,
    category_id, brand_id, handling_class, base_unit_id, supplier_id,
    status, is_active, is_featured, sort_order,
    base_price_minor, currency, track_inventory,
    weight_grams, length_mm, width_mm, height_mm,
    gtin, sku,
    seo_title, seo_description, seo_keywords,
    created_at, updated_at, published_at, deleted_at
FROM catalog.product
WHERE id = $1 AND deleted_at IS NULL
`

type GetProductByIDRow struct {
	ID               int64                    `json:"id"`
	Code             string                   `json:"code"`
	Slug             string                   `json:"slug"`
	Name             string                   `json:"name"`
	Description      pgtype.Text              `json:"description"`
	ShortDescription pgtype.Text              `json:"short_description"`
	CategoryID       int64                    `json:"category_id"`
	BrandID          pgtype.Int8              `json:"brand_id"`
	HandlingClass    CatalogHandlingClassType `json:"handling_class"`
	BaseUnitID       int64                    `json:"base_unit_id"`
	SupplierID       pgtype.Int8              `json:"supplier_id"`
	Status           CatalogProductStatus     `json:"status"`
	IsActive         bool                     `json:"is_active"`
	IsFeatured       bool                     `json:"is_featured"`
	SortOrder        int32                    `json:"sort_order"`
	BasePriceMinor   pgtype.Int8              `json:"base_price_minor"`
	Currency         string                   `json:"currency"`
	TrackInventory   bool                     `json:"track_inventory"`
	WeightGrams      pgtype.Int4              `json:"weight_grams"`
	LengthMm         pgtype.Int4              `json:"length_mm"`
	WidthMm          pgtype.Int4              `json:"width_mm"`
	HeightMm         pgtype.Int4              `json:"height_mm"`
	Gtin             pgtype.Text              `json:"gtin"`
	Sku              pgtype.Text              `json:"sku"`
	SeoTitle         pgtype.Text              `json:"seo_title"`
	SeoDescription   pgtype.Text              `json:"seo_description"`
	SeoKeywords      pgtype.Text              `json:"seo_keywords"`
	CreatedAt        time.Time                `json:"created_at"`
	UpdatedAt        time.Time                `json:"updated_at"`
	PublishedAt      pgtype.Timestamptz       `json:"published_at"`
	DeletedAt        pgtype.Timestamptz       `json:"deleted_at"`
}

func (q *Queries) GetProductByID(ctx context.Context, id int64) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ShortDescription,
		&i.CategoryID,
		&i.BrandID,
		&i.HandlingClass,
		&i.BaseUnitID,
		&i.SupplierID,
		&i.Status,
		&i.IsActive,
		&i.IsFeatured,
		&i.SortOrder,
		&i.BasePriceMinor,
		&i.Currency,
		&i.TrackInventory,
		&i.WeightGrams,
		&i.LengthMm,
		&i.WidthMm,
		&i.HeightMm,
		&i.Gtin,
		&i.Sku,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.SeoKeywords,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT
    p.id, p.code, p.slug, p.name, p.description, p.short_description,
    p.category_id, p.brand_id, p.handling_class, p.base_unit_id, p.supplier_id,
    p.status, p.is_active, p.is_featured, p.sort_order,
    p.base_price_minor, p.currency, p.track_inventory,
    p.weight_grams, p.length_mm, p.width_mm, p.height_mm,
    p.gtin, p.sku,
    p.seo_title, p.seo_description, p.seo_keywords,
    p.created_at, p.updated_at, p.published_at,
    c.name AS category_name,
    c.slug AS category_slug,
    b.name AS brand_name,
    b.slug AS brand_slug,
    hc.name AS handling_class_name,
    hc.code AS handling_class_code,
    u.name AS base_unit_name,
    u.symbol AS base_unit_symbol,
    s.name AS supplier_name,
    s.slug AS supplier_slug
FROM catalog.product p
LEFT JOIN catalog.category c ON p.category_id = c.id AND c.deleted_at IS NULL
LEFT JOIN catalog.brand b ON p.brand_id = b.id AND b.deleted_at IS NULL
LEFT JOIN catalog.handling_class hc ON p.handling_class = hc.name
LEFT JOIN catalog.unit u ON p.base_unit_id = u.id AND u.deleted_at IS NULL
LEFT JOIN catalog.supplier s ON p.supplier_id = s.id AND s.deleted_at IS NULL
WHERE p.slug = $1 AND p.deleted_at IS NULL
`

type GetProductBySlugRow struct {
	ID                int64                        `json:"id"`
	Code              string                       `json:"code"`
	Slug              string                       `json:"slug"`
	Name              string                       `json:"name"`
	Description       pgtype.Text                  `json:"description"`
	ShortDescription  pgtype.Text                  `json:"short_description"`
	CategoryID        int64                        `json:"category_id"`
	BrandID           pgtype.Int8                  `json:"brand_id"`
	HandlingClass     CatalogHandlingClassType     `json:"handling_class"`
	BaseUnitID        int64                        `json:"base_unit_id"`
	SupplierID        pgtype.Int8                  `json:"supplier_id"`
	Status            CatalogProductStatus         `json:"status"`
	IsActive          bool                         `json:"is_active"`
	IsFeatured        bool                         `json:"is_featured"`
	SortOrder         int32                        `json:"sort_order"`
	BasePriceMinor    pgtype.Int8                  `json:"base_price_minor"`
	Currency          string                       `json:"currency"`
	TrackInventory    bool                         `json:"track_inventory"`
	WeightGrams       pgtype.Int4                  `json:"weight_grams"`
	LengthMm          pgtype.Int4                  `json:"length_mm"`
	WidthMm           pgtype.Int4                  `json:"width_mm"`
	HeightMm          pgtype.Int4                  `json:"height_mm"`
	Gtin              pgtype.Text                  `json:"gtin"`
	Sku               pgtype.Text                  `json:"sku"`
	SeoTitle          pgtype.Text                  `json:"seo_title"`
	SeoDescription    pgtype.Text                  `json:"seo_description"`
	SeoKeywords       pgtype.Text                  `json:"seo_keywords"`
	CreatedAt         time.Time                    `json:"created_at"`
	UpdatedAt         time.Time                    `json:"updated_at"`
	PublishedAt       pgtype.Timestamptz           `json:"published_at"`
	CategoryName      pgtype.Text                  `json:"category_name"`
	CategorySlug      pgtype.Text                  `json:"category_slug"`
	BrandName         pgtype.Text                  `json:"brand_name"`
	BrandSlug         pgtype.Text                  `json:"brand_slug"`
	HandlingClassName NullCatalogHandlingClassType `json:"handling_class_name"`
	HandlingClassCode pgtype.Text                  `json:"handling_class_code"`
	BaseUnitName      pgtype.Text                  `json:"base_unit_name"`
	BaseUnitSymbol    pgtype.Text                  `json:"base_unit_symbol"`
	SupplierName      pgtype.Text                  `json:"supplier_name"`
	SupplierSlug      pgtype.Text                  `json:"supplier_slug"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ShortDescription,
		&i.CategoryID,
		&i.BrandID,
		&i.HandlingClass,
		&i.BaseUnitID,
		&i.SupplierID,
		&i.Status,
		&i.IsActive,
		&i.IsFeatured,
		&i.SortOrder,
		&i.BasePriceMinor,
		&i.Currency,
		&i.TrackInventory,
		&i.WeightGrams,
		&i.LengthMm,
		&i.WidthMm,
		&i.HeightMm,
		&i.Gtin,
		&i.Sku,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.SeoKeywords,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.CategoryName,
		&i.CategorySlug,
		&i.BrandName,
		&i.BrandSlug,
		&i.HandlingClassName,
		&i.HandlingClassCode,
		&i.BaseUnitName,
		&i.BaseUnitSymbol,
		&i.SupplierName,
		&i.SupplierSlug,
	)
	return i, err
}

const getSupplierByCode = `-- name: GetSupplierByCode :one
SELECT id, code, supplier_id, name, slug, description, logo_url,
       is_active, created_at, updated_at, deleted_at
FROM catalog.supplier
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSupplierByCode(ctx context.Context, code string) (CatalogSupplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByCode, code)
	var i CatalogSupplier
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.SupplierID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSupplierByID = `-- name: GetSupplierByID :one
SELECT id, code, supplier_id, name, slug, description, logo_url,
       is_active, created_at, updated_at, deleted_at
FROM catalog.supplier
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSupplierByID(ctx context.Context, id int64) (CatalogSupplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByID, id)
	var i CatalogSupplier
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.SupplierID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSupplierBySlug = `-- name: GetSupplierBySlug :one
SELECT id, code, supplier_id, name, slug, description, logo_url,
       is_active, created_at, updated_at, deleted_at
FROM catalog.supplier
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSupplierBySlug(ctx context.Context, slug string) (CatalogSupplier, error) {
	row := q.db.QueryRow(ctx, getSupplierBySlug, slug)
	var i CatalogSupplier
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.SupplierID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUnitByCode = `-- name: GetUnitByCode :one
SELECT id, code, name, symbol, unit_type, base_unit_id, conversion_factor,
       is_active, created_at, updated_at, deleted_at
FROM catalog.unit
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUnitByCode(ctx context.Context, code string) (CatalogUnit, error) {
	row := q.db.QueryRow(ctx, getUnitByCode, code)
	var i CatalogUnit
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.UnitType,
		&i.BaseUnitID,
		&i.ConversionFactor,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUnitByID = `-- name: GetUnitByID :one
SELECT id, code, name, symbol, unit_type, base_unit_id, conversion_factor,
       is_active, created_at, updated_at, deleted_at
FROM catalog.unit
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUnitByID(ctx context.Context, id int64) (CatalogUnit, error) {
	row := q.db.QueryRow(ctx, getUnitByID, id)
	var i CatalogUnit
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.UnitType,
		&i.BaseUnitID,
		&i.ConversionFactor,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBrands = `-- name: ListBrands :many
SELECT id, code, name, slug, description, logo_url, website_url,
       is_active, created_at, updated_at, deleted_at
FROM catalog.brand
WHERE deleted_at IS NULL AND is_active = TRUE
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListBrandsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBrands(ctx context.Context, arg ListBrandsParams) ([]CatalogBrand, error) {
	rows, err := q.db.Query(ctx, listBrands, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogBrand{}
	for rows.Next() {
		var i CatalogBrand
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.LogoUrl,
			&i.WebsiteUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrandsAdmin = `-- name: ListBrandsAdmin :many
SELECT id, code, name, slug, description, logo_url, website_url,
       is_active, created_at, updated_at, deleted_at
FROM catalog.brand
WHERE deleted_at IS NULL
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListBrandsAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBrandsAdmin(ctx context.Context, arg ListBrandsAdminParams) ([]CatalogBrand, error) {
	rows, err := q.db.Query(ctx, listBrandsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogBrand{}
	for rows.Next() {
		var i CatalogBrand
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.LogoUrl,
			&i.WebsiteUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, code, name, slug, description, parent_id, sort_order,
       is_active, seo_title, seo_description, created_at, updated_at, deleted_at
FROM catalog.category
WHERE deleted_at IS NULL
  AND ($1::int8 = 0 OR parent_id = $1)
ORDER BY sort_order, name
LIMIT $2 OFFSET $3
`

type ListCategoriesParams struct {
	Column1 int64 `json:"column_1"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]CatalogCategory, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogCategory{}
	for rows.Next() {
		var i CatalogCategory
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.SortOrder,
			&i.IsActive,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHandlingClasses = `-- name: ListHandlingClasses :many
SELECT id, code, name, description, sort_order,
       temperature_min_c, temperature_max_c,
       is_active, created_at, updated_at, deleted_at
FROM catalog.handling_class
WHERE deleted_at IS NULL
ORDER BY sort_order, name
`

func (q *Queries) ListHandlingClasses(ctx context.Context) ([]CatalogHandlingClass, error) {
	rows, err := q.db.Query(ctx, listHandlingClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogHandlingClass{}
	for rows.Next() {
		var i CatalogHandlingClass
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.TemperatureMinC,
			&i.TemperatureMaxC,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductAttributes = `-- name: ListProductAttributes :many
SELECT pa.id, pa.product_id, pa.attribute_id, pa.attribute_value_id,
       pa.text_value, pa.number_value, pa.boolean_value,
       pa.created_at, pa.updated_at, pa.deleted_at,
       a.code AS attribute_code, a.name AS attribute_name, a.attribute_type,
       av.value AS attribute_value_name, av.id AS attribute_value_id
FROM catalog.product_attribute pa
JOIN catalog.attribute a ON pa.attribute_id = a.id AND a.deleted_at IS NULL
LEFT JOIN catalog.attribute_value av ON pa.attribute_value_id = av.id AND av.deleted_at IS NULL
WHERE pa.product_id = $1 AND pa.deleted_at IS NULL
ORDER BY a.sort_order, a.name
`

type ListProductAttributesRow struct {
	ID                 int64              `json:"id"`
	ProductID          int64              `json:"product_id"`
	AttributeID        int64              `json:"attribute_id"`
	AttributeValueID   pgtype.Int8        `json:"attribute_value_id"`
	TextValue          pgtype.Text        `json:"text_value"`
	NumberValue        pgtype.Numeric     `json:"number_value"`
	BooleanValue       pgtype.Bool        `json:"boolean_value"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	AttributeCode      string             `json:"attribute_code"`
	AttributeName      string             `json:"attribute_name"`
	AttributeType      string             `json:"attribute_type"`
	AttributeValueName pgtype.Text        `json:"attribute_value_name"`
	AttributeValueID_2 pgtype.Int8        `json:"attribute_value_id_2"`
}

func (q *Queries) ListProductAttributes(ctx context.Context, productID int64) ([]ListProductAttributesRow, error) {
	rows, err := q.db.Query(ctx, listProductAttributes, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductAttributesRow{}
	for rows.Next() {
		var i ListProductAttributesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.AttributeID,
			&i.AttributeValueID,
			&i.TextValue,
			&i.NumberValue,
			&i.BooleanValue,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AttributeCode,
			&i.AttributeName,
			&i.AttributeType,
			&i.AttributeValueName,
			&i.AttributeValueID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductMedia = `-- name: ListProductMedia :many
SELECT id, code, product_id, url, alt_text, media_type, sort_order,
       is_primary, width_px, height_px, file_size_bytes, mime_type,
       created_at, updated_at, deleted_at
FROM catalog.product_media
WHERE product_id = $1 AND deleted_at IS NULL
ORDER BY is_primary DESC, sort_order
`

func (q *Queries) ListProductMedia(ctx context.Context, productID int64) ([]CatalogProductMedium, error) {
	rows, err := q.db.Query(ctx, listProductMedia, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogProductMedium{}
	for rows.Next() {
		var i CatalogProductMedium
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ProductID,
			&i.Url,
			&i.AltText,
			&i.MediaType,
			&i.SortOrder,
			&i.IsPrimary,
			&i.WidthPx,
			&i.HeightPx,
			&i.FileSizeBytes,
			&i.MimeType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductUnits = `-- name: ListProductUnits :many
SELECT pu.id, pu.product_id, pu.unit_id, pu.conversion_factor, pu.is_default,
       pu.price_minor, pu.is_active, pu.created_at, pu.updated_at, pu.deleted_at,
       u.code, u.name, u.symbol
FROM catalog.product_unit pu
JOIN catalog.unit u ON pu.unit_id = u.id AND u.deleted_at IS NULL
WHERE pu.product_id = $1 AND pu.deleted_at IS NULL
ORDER BY pu.is_default DESC, u.name
`

type ListProductUnitsRow struct {
	ID               int64              `json:"id"`
	ProductID        int64              `json:"product_id"`
	UnitID           int64              `json:"unit_id"`
	ConversionFactor pgtype.Numeric     `json:"conversion_factor"`
	IsDefault        bool               `json:"is_default"`
	PriceMinor       pgtype.Int8        `json:"price_minor"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
	Symbol           string             `json:"symbol"`
}

func (q *Queries) ListProductUnits(ctx context.Context, productID int64) ([]ListProductUnitsRow, error) {
	rows, err := q.db.Query(ctx, listProductUnits, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductUnitsRow{}
	for rows.Next() {
		var i ListProductUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UnitID,
			&i.ConversionFactor,
			&i.IsDefault,
			&i.PriceMinor,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Code,
			&i.Name,
			&i.Symbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
    id, code, slug, name, description, short_description,
    category_id, brand_id, handling_class, base_unit_id, supplier_id,
    status, is_active, is_featured, sort_order,
    base_price_minor, currency, track_inventory,
    weight_grams, length_mm, width_mm, height_mm,
    gtin, sku,
    seo_title, seo_description, seo_keywords,
    created_at, updated_at, published_at, deleted_at
FROM catalog.product,
    (SELECT
        $1::text AS p_status,
        $2::bigint AS p_category_id,
        $3::bigint AS p_brand_id,
        $4::text AS p_handling_class,
        $5::bigint AS p_supplier_id,
        $6::text AS p_query
    ) params
WHERE deleted_at IS NULL
  AND (params.p_status = '' OR status = params.p_status::catalog.product_status)
  AND (params.p_category_id = 0 OR category_id = params.p_category_id)
  AND (params.p_brand_id = 0 OR brand_id = params.p_brand_id)
  AND (params.p_handling_class = '' OR handling_class = params.p_handling_class::catalog_handling_class_type)
  AND (params.p_supplier_id = 0 OR supplier_id = params.p_supplier_id)
  AND (params.p_query IS NULL OR name ILIKE '%' || params.p_query || '%' OR description ILIKE '%' || params.p_query || '%')
ORDER BY
    CASE WHEN $7 = 'name_asc' THEN name END ASC,
    CASE WHEN $7 = 'name_desc' THEN name END DESC,
    CASE WHEN $7 = 'price_asc' THEN base_price_minor END ASC,
    CASE WHEN $7 = 'price_desc' THEN base_price_minor END DESC,
    CASE WHEN $7 = 'created_desc' OR $7 IS NULL THEN created_at END DESC,
    CASE WHEN $7 = 'created_asc' THEN created_at END ASC,
    CASE WHEN $7 = 'featured' THEN is_featured END DESC
LIMIT $8 OFFSET $9
`

type ListProductsParams struct {
	Column1 string      `json:"column_1"`
	Column2 int64       `json:"column_2"`
	Column3 int64       `json:"column_3"`
	Column4 string      `json:"column_4"`
	Column5 int64       `json:"column_5"`
	Column6 string      `json:"column_6"`
	Column7 interface{} `json:"column_7"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListProductsRow struct {
	ID               int64                    `json:"id"`
	Code             string                   `json:"code"`
	Slug             string                   `json:"slug"`
	Name             string                   `json:"name"`
	Description      pgtype.Text              `json:"description"`
	ShortDescription pgtype.Text              `json:"short_description"`
	CategoryID       int64                    `json:"category_id"`
	BrandID          pgtype.Int8              `json:"brand_id"`
	HandlingClass    CatalogHandlingClassType `json:"handling_class"`
	BaseUnitID       int64                    `json:"base_unit_id"`
	SupplierID       pgtype.Int8              `json:"supplier_id"`
	Status           CatalogProductStatus     `json:"status"`
	IsActive         bool                     `json:"is_active"`
	IsFeatured       bool                     `json:"is_featured"`
	SortOrder        int32                    `json:"sort_order"`
	BasePriceMinor   pgtype.Int8              `json:"base_price_minor"`
	Currency         string                   `json:"currency"`
	TrackInventory   bool                     `json:"track_inventory"`
	WeightGrams      pgtype.Int4              `json:"weight_grams"`
	LengthMm         pgtype.Int4              `json:"length_mm"`
	WidthMm          pgtype.Int4              `json:"width_mm"`
	HeightMm         pgtype.Int4              `json:"height_mm"`
	Gtin             pgtype.Text              `json:"gtin"`
	Sku              pgtype.Text              `json:"sku"`
	SeoTitle         pgtype.Text              `json:"seo_title"`
	SeoDescription   pgtype.Text              `json:"seo_description"`
	SeoKeywords      pgtype.Text              `json:"seo_keywords"`
	CreatedAt        time.Time                `json:"created_at"`
	UpdatedAt        time.Time                `json:"updated_at"`
	PublishedAt      pgtype.Timestamptz       `json:"published_at"`
	DeletedAt        pgtype.Timestamptz       `json:"deleted_at"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ShortDescription,
			&i.CategoryID,
			&i.BrandID,
			&i.HandlingClass,
			&i.BaseUnitID,
			&i.SupplierID,
			&i.Status,
			&i.IsActive,
			&i.IsFeatured,
			&i.SortOrder,
			&i.BasePriceMinor,
			&i.Currency,
			&i.TrackInventory,
			&i.WeightGrams,
			&i.LengthMm,
			&i.WidthMm,
			&i.HeightMm,
			&i.Gtin,
			&i.Sku,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.SeoKeywords,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, code, supplier_id, name, slug, description, logo_url,
       is_active, created_at, updated_at, deleted_at
FROM catalog.supplier
WHERE deleted_at IS NULL AND is_active = TRUE
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListSuppliersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]CatalogSupplier, error) {
	rows, err := q.db.Query(ctx, listSuppliers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogSupplier{}
	for rows.Next() {
		var i CatalogSupplier
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.SupplierID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.LogoUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppliersAdmin = `-- name: ListSuppliersAdmin :many
SELECT id, code, supplier_id, name, slug, description, logo_url,
       is_active, created_at, updated_at, deleted_at
FROM catalog.supplier
WHERE deleted_at IS NULL
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListSuppliersAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSuppliersAdmin(ctx context.Context, arg ListSuppliersAdminParams) ([]CatalogSupplier, error) {
	rows, err := q.db.Query(ctx, listSuppliersAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogSupplier{}
	for rows.Next() {
		var i CatalogSupplier
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.SupplierID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.LogoUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many
SELECT id, code, name, symbol, unit_type, base_unit_id, conversion_factor,
       is_active, created_at, updated_at, deleted_at
FROM catalog.unit
WHERE deleted_at IS NULL AND is_active = TRUE
ORDER BY unit_type, name
LIMIT $1 OFFSET $2
`

type ListUnitsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUnits(ctx context.Context, arg ListUnitsParams) ([]CatalogUnit, error) {
	rows, err := q.db.Query(ctx, listUnits, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogUnit{}
	for rows.Next() {
		var i CatalogUnit
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.UnitType,
			&i.BaseUnitID,
			&i.ConversionFactor,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishProduct = `-- name: PublishProduct :exec
UPDATE catalog.product
SET status = 'published', published_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) PublishProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, publishProduct, id)
	return err
}

const searchProducts = `-- name: SearchProducts :many
SELECT
    p.id, p.code, p.slug, p.name, p.short_description,
    p.category_id, p.brand_id, p.handling_class, p.base_unit_id, p.supplier_id,
    p.status, p.is_active, p.is_featured, p.sort_order,
    p.base_price_minor, p.currency, p.track_inventory,
    p.created_at, p.updated_at, p.published_at,
    c.name AS category_name,
    c.slug AS category_slug,
    b.name AS brand_name,
    b.slug AS brand_slug,
    hc.name AS handling_class_name,
    hc.code AS handling_class_code,
    u.name AS base_unit_name,
    u.symbol AS base_unit_symbol,
    ts_rank_cd(
        setweight(to_tsvector('simple', p.name), 'A') ||
        setweight(to_tsvector('simple', p.description), 'B') ||
        setweight(to_tsvector('simple', p.short_description), 'B') ||
        setweight(to_tsvector('simple', c.name), 'C') ||
        setweight(to_tsvector('simple', b.name), 'C'),
        plainto_tsquery('simple', $1)
    ) AS rank
FROM catalog.product p
LEFT JOIN catalog.category c ON p.category_id = c.id AND c.deleted_at IS NULL
LEFT JOIN catalog.brand b ON p.brand_id = b.id AND b.deleted_at IS NULL
LEFT JOIN catalog.handling_class hc ON p.handling_class = hc.name
LEFT JOIN catalog.unit u ON p.base_unit_id = u.id AND u.deleted_at IS NULL
WHERE p.deleted_at IS NULL
  AND p.status = 'published'
  AND p.is_active = TRUE
  AND ($2::bigint = 0 OR p.category_id = $2)
  AND ($3::bigint = 0 OR p.brand_id = $3)
  AND ($4::catalog_handling_class_type = '' OR p.handling_class = $4)
  AND ($5::bigint = 0 OR p.supplier_id = $5)
  AND (
    $1 = ''
    OR p.name ILIKE '%' || $1 || '%'
    OR p.description ILIKE '%' || $1 || '%'
    OR p.short_description ILIKE '%' || $1 || '%'
    OR c.name ILIKE '%' || $1 || '%'
    OR b.name ILIKE '%' || $1 || '%'
    OR p.code ILIKE '%' || $1 || '%'
    OR p.sku ILIKE '%' || $1 || '%'
  )
ORDER BY rank DESC NULLS LAST, p.is_featured DESC, p.name ASC
LIMIT $6 OFFSET $7
`

type SearchProductsParams struct {
	PlaintoTsquery string                   `json:"plainto_tsquery"`
	Column2        int64                    `json:"column_2"`
	Column3        int64                    `json:"column_3"`
	Column4        CatalogHandlingClassType `json:"column_4"`
	Column5        int64                    `json:"column_5"`
	Limit          int32                    `json:"limit"`
	Offset         int32                    `json:"offset"`
}

type SearchProductsRow struct {
	ID                int64                        `json:"id"`
	Code              string                       `json:"code"`
	Slug              string                       `json:"slug"`
	Name              string                       `json:"name"`
	ShortDescription  pgtype.Text                  `json:"short_description"`
	CategoryID        int64                        `json:"category_id"`
	BrandID           pgtype.Int8                  `json:"brand_id"`
	HandlingClass     CatalogHandlingClassType     `json:"handling_class"`
	BaseUnitID        int64                        `json:"base_unit_id"`
	SupplierID        pgtype.Int8                  `json:"supplier_id"`
	Status            CatalogProductStatus         `json:"status"`
	IsActive          bool                         `json:"is_active"`
	IsFeatured        bool                         `json:"is_featured"`
	SortOrder         int32                        `json:"sort_order"`
	BasePriceMinor    pgtype.Int8                  `json:"base_price_minor"`
	Currency          string                       `json:"currency"`
	TrackInventory    bool                         `json:"track_inventory"`
	CreatedAt         time.Time                    `json:"created_at"`
	UpdatedAt         time.Time                    `json:"updated_at"`
	PublishedAt       pgtype.Timestamptz           `json:"published_at"`
	CategoryName      pgtype.Text                  `json:"category_name"`
	CategorySlug      pgtype.Text                  `json:"category_slug"`
	BrandName         pgtype.Text                  `json:"brand_name"`
	BrandSlug         pgtype.Text                  `json:"brand_slug"`
	HandlingClassName NullCatalogHandlingClassType `json:"handling_class_name"`
	HandlingClassCode pgtype.Text                  `json:"handling_class_code"`
	BaseUnitName      pgtype.Text                  `json:"base_unit_name"`
	BaseUnitSymbol    pgtype.Text                  `json:"base_unit_symbol"`
	Rank              float32                      `json:"rank"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error) {
	rows, err := q.db.Query(ctx, searchProducts,
		arg.PlaintoTsquery,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProductsRow{}
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Slug,
			&i.Name,
			&i.ShortDescription,
			&i.CategoryID,
			&i.BrandID,
			&i.HandlingClass,
			&i.BaseUnitID,
			&i.SupplierID,
			&i.Status,
			&i.IsActive,
			&i.IsFeatured,
			&i.SortOrder,
			&i.BasePriceMinor,
			&i.Currency,
			&i.TrackInventory,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.CategoryName,
			&i.CategorySlug,
			&i.BrandName,
			&i.BrandSlug,
			&i.HandlingClassName,
			&i.HandlingClassCode,
			&i.BaseUnitName,
			&i.BaseUnitSymbol,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBrand = `-- name: SoftDeleteBrand :exec
UPDATE catalog.brand
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteBrand(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteBrand, id)
	return err
}

const softDeleteCategory = `-- name: SoftDeleteCategory :exec
UPDATE catalog.category
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteCategory, id)
	return err
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE catalog.product
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, id)
	return err
}

const softDeleteSupplier = `-- name: SoftDeleteSupplier :exec
UPDATE catalog.supplier
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteSupplier(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteSupplier, id)
	return err
}

const softDeleteUnit = `-- name: SoftDeleteUnit :exec
UPDATE catalog.unit
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteUnit(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteUnit, id)
	return err
}

const updateBrand = `-- name: UpdateBrand :one
UPDATE catalog.brand
SET
    name = COALESCE($2, name),
    slug = COALESCE($3, slug),
    description = COALESCE($4, description),
    logo_url = COALESCE($5, logo_url),
    website_url = COALESCE($6, website_url),
    is_active = COALESCE($7, is_active),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, slug, name, updated_at
`

type UpdateBrandParams struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	WebsiteUrl  pgtype.Text `json:"website_url"`
	IsActive    bool        `json:"is_active"`
}

type UpdateBrandRow struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateBrand(ctx context.Context, arg UpdateBrandParams) (UpdateBrandRow, error) {
	row := q.db.QueryRow(ctx, updateBrand,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.LogoUrl,
		arg.WebsiteUrl,
		arg.IsActive,
	)
	var i UpdateBrandRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE catalog.category
SET
    name = COALESCE($2, name),
    slug = COALESCE($3, slug),
    description = COALESCE($4, description),
    parent_id = COALESCE($5, parent_id),
    sort_order = COALESCE($6, sort_order),
    is_active = COALESCE($7, is_active),
    seo_title = COALESCE($8, seo_title),
    seo_description = COALESCE($9, seo_description),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, slug, name, updated_at
`

type UpdateCategoryParams struct {
	ID             int64       `json:"id"`
	Name           string      `json:"name"`
	Slug           string      `json:"slug"`
	Description    pgtype.Text `json:"description"`
	ParentID       pgtype.Int8 `json:"parent_id"`
	SortOrder      int32       `json:"sort_order"`
	IsActive       bool        `json:"is_active"`
	SeoTitle       pgtype.Text `json:"seo_title"`
	SeoDescription pgtype.Text `json:"seo_description"`
}

type UpdateCategoryRow struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (UpdateCategoryRow, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ParentID,
		arg.SortOrder,
		arg.IsActive,
		arg.SeoTitle,
		arg.SeoDescription,
	)
	var i UpdateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE catalog.product
SET
    slug = COALESCE($2, slug),
    name = COALESCE($3, name),
    description = COALESCE($4, description),
    short_description = COALESCE($5, short_description),
    category_id = COALESCE($6, category_id),
    brand_id = COALESCE($7, brand_id),
    handling_class = COALESCE($8, handling_class),
    base_unit_id = COALESCE($9, base_unit_id),
    supplier_id = COALESCE($10, supplier_id),
    status = COALESCE($11, status),
    is_active = COALESCE($12, is_active),
    is_featured = COALESCE($13, is_featured),
    sort_order = COALESCE($14, sort_order),
    base_price_minor = COALESCE($15, base_price_minor),
    currency = COALESCE($16, currency),
    track_inventory = COALESCE($17, track_inventory),
    weight_grams = COALESCE($18, weight_grams),
    length_mm = COALESCE($19, length_mm),
    width_mm = COALESCE($20, width_mm),
    height_mm = COALESCE($21, height_mm),
    gtin = COALESCE($22, gtin),
    sku = COALESCE($23, sku),
    seo_title = COALESCE($24, seo_title),
    seo_description = COALESCE($25, seo_description),
    seo_keywords = COALESCE($26, seo_keywords),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, slug, name, status, updated_at
`

type UpdateProductParams struct {
	ID               int64                    `json:"id"`
	Slug             string                   `json:"slug"`
	Name             string                   `json:"name"`
	Description      pgtype.Text              `json:"description"`
	ShortDescription pgtype.Text              `json:"short_description"`
	CategoryID       int64                    `json:"category_id"`
	BrandID          pgtype.Int8              `json:"brand_id"`
	HandlingClass    CatalogHandlingClassType `json:"handling_class"`
	BaseUnitID       int64                    `json:"base_unit_id"`
	SupplierID       pgtype.Int8              `json:"supplier_id"`
	Status           CatalogProductStatus     `json:"status"`
	IsActive         bool                     `json:"is_active"`
	IsFeatured       bool                     `json:"is_featured"`
	SortOrder        int32                    `json:"sort_order"`
	BasePriceMinor   pgtype.Int8              `json:"base_price_minor"`
	Currency         string                   `json:"currency"`
	TrackInventory   bool                     `json:"track_inventory"`
	WeightGrams      pgtype.Int4              `json:"weight_grams"`
	LengthMm         pgtype.Int4              `json:"length_mm"`
	WidthMm          pgtype.Int4              `json:"width_mm"`
	HeightMm         pgtype.Int4              `json:"height_mm"`
	Gtin             pgtype.Text              `json:"gtin"`
	Sku              pgtype.Text              `json:"sku"`
	SeoTitle         pgtype.Text              `json:"seo_title"`
	SeoDescription   pgtype.Text              `json:"seo_description"`
	SeoKeywords      pgtype.Text              `json:"seo_keywords"`
}

type UpdateProductRow struct {
	ID        int64                `json:"id"`
	Code      string               `json:"code"`
	Slug      string               `json:"slug"`
	Name      string               `json:"name"`
	Status    CatalogProductStatus `json:"status"`
	UpdatedAt time.Time            `json:"updated_at"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.ShortDescription,
		arg.CategoryID,
		arg.BrandID,
		arg.HandlingClass,
		arg.BaseUnitID,
		arg.SupplierID,
		arg.Status,
		arg.IsActive,
		arg.IsFeatured,
		arg.SortOrder,
		arg.BasePriceMinor,
		arg.Currency,
		arg.TrackInventory,
		arg.WeightGrams,
		arg.LengthMm,
		arg.WidthMm,
		arg.HeightMm,
		arg.Gtin,
		arg.Sku,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.SeoKeywords,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductMedia = `-- name: UpdateProductMedia :exec
UPDATE catalog.product_media
SET alt_text = COALESCE($2, alt_text),
    media_type = COALESCE($3, media_type),
    sort_order = COALESCE($4, sort_order),
    is_primary = COALESCE($5, is_primary),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateProductMediaParams struct {
	ID        int64       `json:"id"`
	AltText   pgtype.Text `json:"alt_text"`
	MediaType string      `json:"media_type"`
	SortOrder int32       `json:"sort_order"`
	IsPrimary bool        `json:"is_primary"`
}

func (q *Queries) UpdateProductMedia(ctx context.Context, arg UpdateProductMediaParams) error {
	_, err := q.db.Exec(ctx, updateProductMedia,
		arg.ID,
		arg.AltText,
		arg.MediaType,
		arg.SortOrder,
		arg.IsPrimary,
	)
	return err
}

const updateProductUnit = `-- name: UpdateProductUnit :exec
UPDATE catalog.product_unit
SET conversion_factor = COALESCE($2, conversion_factor),
    is_default = COALESCE($3, is_default),
    price_minor = COALESCE($4, price_minor),
    is_active = COALESCE($5, is_active),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateProductUnitParams struct {
	ID               int64          `json:"id"`
	ConversionFactor pgtype.Numeric `json:"conversion_factor"`
	IsDefault        bool           `json:"is_default"`
	PriceMinor       pgtype.Int8    `json:"price_minor"`
	IsActive         bool           `json:"is_active"`
}

func (q *Queries) UpdateProductUnit(ctx context.Context, arg UpdateProductUnitParams) error {
	_, err := q.db.Exec(ctx, updateProductUnit,
		arg.ID,
		arg.ConversionFactor,
		arg.IsDefault,
		arg.PriceMinor,
		arg.IsActive,
	)
	return err
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE catalog.supplier
SET
    name = COALESCE($2, name),
    slug = COALESCE($3, slug),
    description = COALESCE($4, description),
    logo_url = COALESCE($5, logo_url),
    is_active = COALESCE($6, is_active),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, slug, name, updated_at
`

type UpdateSupplierParams struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	IsActive    bool        `json:"is_active"`
}

type UpdateSupplierRow struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (UpdateSupplierRow, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.LogoUrl,
		arg.IsActive,
	)
	var i UpdateSupplierRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUnit = `-- name: UpdateUnit :one
UPDATE catalog.unit
SET
    name = COALESCE($2, name),
    symbol = COALESCE($3, symbol),
    unit_type = COALESCE($4, unit_type),
    base_unit_id = COALESCE($5, base_unit_id),
    conversion_factor = COALESCE($6, conversion_factor),
    is_active = COALESCE($7, is_active),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, name, symbol, updated_at
`

type UpdateUnitParams struct {
	ID               int64           `json:"id"`
	Name             string          `json:"name"`
	Symbol           string          `json:"symbol"`
	UnitType         CatalogUnitType `json:"unit_type"`
	BaseUnitID       pgtype.Int8     `json:"base_unit_id"`
	ConversionFactor pgtype.Numeric  `json:"conversion_factor"`
	IsActive         bool            `json:"is_active"`
}

type UpdateUnitRow struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Symbol    string    `json:"symbol"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (UpdateUnitRow, error) {
	row := q.db.QueryRow(ctx, updateUnit,
		arg.ID,
		arg.Name,
		arg.Symbol,
		arg.UnitType,
		arg.BaseUnitID,
		arg.ConversionFactor,
		arg.IsActive,
	)
	var i UpdateUnitRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProductAttribute = `-- name: UpsertProductAttribute :one
INSERT INTO catalog.product_attribute (
    product_id, attribute_id, attribute_value_id, text_value, number_value, boolean_value
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (product_id, attribute_id, attribute_value_id) DO UPDATE SET
    text_value = EXCLUDED.text_value,
    number_value = EXCLUDED.number_value,
    boolean_value = EXCLUDED.boolean_value,
    updated_at = NOW()
RETURNING id, product_id, attribute_id, attribute_value_id, text_value, number_value, boolean_value, created_at
`

type UpsertProductAttributeParams struct {
	ProductID        int64          `json:"product_id"`
	AttributeID      int64          `json:"attribute_id"`
	AttributeValueID pgtype.Int8    `json:"attribute_value_id"`
	TextValue        pgtype.Text    `json:"text_value"`
	NumberValue      pgtype.Numeric `json:"number_value"`
	BooleanValue     pgtype.Bool    `json:"boolean_value"`
}

type UpsertProductAttributeRow struct {
	ID               int64          `json:"id"`
	ProductID        int64          `json:"product_id"`
	AttributeID      int64          `json:"attribute_id"`
	AttributeValueID pgtype.Int8    `json:"attribute_value_id"`
	TextValue        pgtype.Text    `json:"text_value"`
	NumberValue      pgtype.Numeric `json:"number_value"`
	BooleanValue     pgtype.Bool    `json:"boolean_value"`
	CreatedAt        time.Time      `json:"created_at"`
}

func (q *Queries) UpsertProductAttribute(ctx context.Context, arg UpsertProductAttributeParams) (UpsertProductAttributeRow, error) {
	row := q.db.QueryRow(ctx, upsertProductAttribute,
		arg.ProductID,
		arg.AttributeID,
		arg.AttributeValueID,
		arg.TextValue,
		arg.NumberValue,
		arg.BooleanValue,
	)
	var i UpsertProductAttributeRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AttributeID,
		&i.AttributeValueID,
		&i.TextValue,
		&i.NumberValue,
		&i.BooleanValue,
		&i.CreatedAt,
	)
	return i, err
}
