// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package catalog

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveProduct(ctx context.Context, id int64) error
	CountBrands(ctx context.Context) (int64, error)
	CountCategories(ctx context.Context, dollar_1 int64) (int64, error)
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CountSearchProducts(ctx context.Context, arg CountSearchProductsParams) (int64, error)
	CountSuppliers(ctx context.Context) (int64, error)
	CountUnits(ctx context.Context) (int64, error)
	CreateBrand(ctx context.Context, arg CreateBrandParams) (CreateBrandRow, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error)
	// Catalog module queries
	// Products, Categories, Brands, Units, Handling Classes, Suppliers, Facets
	CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error)
	CreateProductMedia(ctx context.Context, arg CreateProductMediaParams) (CreateProductMediaRow, error)
	CreateProductUnit(ctx context.Context, arg CreateProductUnitParams) (CreateProductUnitRow, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (CreateSupplierRow, error)
	CreateUnit(ctx context.Context, arg CreateUnitParams) (CreateUnitRow, error)
	DeleteProductAttribute(ctx context.Context, arg DeleteProductAttributeParams) error
	DeleteProductMedia(ctx context.Context, id int64) error
	DeleteProductUnit(ctx context.Context, id int64) error
	GetAttributeFacets(ctx context.Context, dollar_1 int64) ([]GetAttributeFacetsRow, error)
	GetBrandByCode(ctx context.Context, code string) (CatalogBrand, error)
	GetBrandByID(ctx context.Context, id int64) (CatalogBrand, error)
	GetBrandBySlug(ctx context.Context, slug string) (CatalogBrand, error)
	GetCategoryBreadcrumbs(ctx context.Context, id int64) ([]GetCategoryBreadcrumbsRow, error)
	GetCategoryByCode(ctx context.Context, code string) (CatalogCategory, error)
	GetCategoryByID(ctx context.Context, id int64) (CatalogCategory, error)
	GetCategoryBySlug(ctx context.Context, slug string) (CatalogCategory, error)
	GetCategoryChildren(ctx context.Context, parentID pgtype.Int8) ([]CatalogCategory, error)
	GetCategoryTree(ctx context.Context) ([]GetCategoryTreeRow, error)
	GetFacets(ctx context.Context) ([]GetFacetsRow, error)
	GetFilteredFacets(ctx context.Context, arg GetFilteredFacetsParams) ([]GetFilteredFacetsRow, error)
	GetHandlingClassByCode(ctx context.Context, code string) (CatalogHandlingClass, error)
	GetHandlingClassByID(ctx context.Context, id int64) (CatalogHandlingClass, error)
	GetProductByCode(ctx context.Context, code string) (GetProductByCodeRow, error)
	GetProductByID(ctx context.Context, id int64) (GetProductByIDRow, error)
	GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error)
	GetSupplierByCode(ctx context.Context, code string) (CatalogSupplier, error)
	GetSupplierByID(ctx context.Context, id int64) (CatalogSupplier, error)
	GetSupplierBySlug(ctx context.Context, slug string) (CatalogSupplier, error)
	GetUnitByCode(ctx context.Context, code string) (CatalogUnit, error)
	GetUnitByID(ctx context.Context, id int64) (CatalogUnit, error)
	ListBrands(ctx context.Context, arg ListBrandsParams) ([]CatalogBrand, error)
	ListBrandsAdmin(ctx context.Context, arg ListBrandsAdminParams) ([]CatalogBrand, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]CatalogCategory, error)
	ListHandlingClasses(ctx context.Context) ([]CatalogHandlingClass, error)
	ListProductAttributes(ctx context.Context, productID int64) ([]ListProductAttributesRow, error)
	ListProductMedia(ctx context.Context, productID int64) ([]CatalogProductMedium, error)
	ListProductUnits(ctx context.Context, productID int64) ([]ListProductUnitsRow, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]CatalogSupplier, error)
	ListSuppliersAdmin(ctx context.Context, arg ListSuppliersAdminParams) ([]CatalogSupplier, error)
	ListUnits(ctx context.Context, arg ListUnitsParams) ([]CatalogUnit, error)
	PublishProduct(ctx context.Context, id int64) error
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error)
	SoftDeleteBrand(ctx context.Context, id int64) error
	SoftDeleteCategory(ctx context.Context, id int64) error
	SoftDeleteProduct(ctx context.Context, id int64) error
	SoftDeleteSupplier(ctx context.Context, id int64) error
	SoftDeleteUnit(ctx context.Context, id int64) error
	UpdateBrand(ctx context.Context, arg UpdateBrandParams) (UpdateBrandRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (UpdateCategoryRow, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error)
	UpdateProductMedia(ctx context.Context, arg UpdateProductMediaParams) error
	UpdateProductUnit(ctx context.Context, arg UpdateProductUnitParams) error
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (UpdateSupplierRow, error)
	UpdateUnit(ctx context.Context, arg UpdateUnitParams) (UpdateUnitRow, error)
	UpsertProductAttribute(ctx context.Context, arg UpsertProductAttributeParams) (UpsertProductAttributeRow, error)
}

var _ Querier = (*Queries)(nil)
